import { BOUNTY_FACTION_PICKER, CORE_COMPANION_PICKER, FORM_TYPE_PICKER, WEATHER_PICKER, PLAYER_ACTOR_VALUE_PICKER, REFERENCE_ACTOR_VALUE_PICKER, SHIP_ACTOR_VALUE_PICKER, GAME_SETTING_PICKER, OPEN_STATE_PICKER, POPULAR_LOCATION_PICKER, type ReferenceIdPicker } from './reference-ids';
import { UNTESTED_COMMANDS } from './untested-commands';

export type CommandCategory =
  | 'Gameplay'
  | 'Player'
  | 'Inventory'
  | 'Skills'
  | 'Camera'
  | 'World'
  | 'Targets'
  | 'Quests'
  | 'Ship'
  | 'Untested';

export type CommandRisk = 'caution' | 'danger';
export type CommandTestStatus = 'verified' | 'untested' | 'inconclusive' | 'failed' | 'needs-adjustment';

export type CommandInput = {
  key: string;
  label: string;
  type: 'number' | 'text';
  defaultValue?: string | number;
  placeholder?: string;
  min?: number;
  max?: number;
  step?: number;
  pattern?: string;
  hint?: string;
  picker?: ReferenceIdPicker;
  browserPicker?: {
    browser: 'id' | 'quest';
    buttonLabel: string;
    allowedTypes?: string[];
    allowedCategories?: string[];
  };
  questStageFor?: string;
  optional?: boolean;
};

export type CommandDefinition = {
  id: string;
  title: string;
  category: CommandCategory;
  description: string;
  command: string;
  inputs?: CommandInput[];
  tags?: string[];
  warning?: string;
  risk?: CommandRisk;
  testStatus?: CommandTestStatus;
  captureOutput?: boolean;
  closeBeforeExecute?: boolean;
  unavailableReason?: string;
  effectiveTotal?: boolean;
  verifyInGame?: boolean;
  catalogSearch?: {
    recordTypeInput?: string;
  };
  intakeGroup?:
    | 'Ready to Test'
    | 'Executed — Effect Unconfirmed'
    | 'Executed — Issues'
    | 'Blocked — Known Crash'
    | 'Engine Console Commands'
    | 'Script Functions';
};

const HEX_ID_PATTERN = '^[0-9A-Fa-f]{1,8}$';
const AXIS_PATTERN = '^[xXyYzZ]$';
const ACTOR_VALUE_PATTERN = '^[A-Za-z0-9_]{1,64}$';
const GAME_SETTING_PATTERN = '^[A-Za-z0-9_]{1,80}$';
const HELP_SEARCH_PATTERN = '^[^\"\r\n]{1,80}$';
const RECORD_TYPE_PATTERN = '^[A-Za-z0-9_]{2,8}$';

const hexInput = (key: string, label: string, placeholder = '0000000F', hint = '1-8 hexadecimal characters'): CommandInput => ({
  key,
  label,
  type: 'text',
  placeholder,
  pattern: HEX_ID_PATTERN,
  hint,
});

const itemFormIdInput = (hint = 'Choose an included item or enter its Form ID.'): CommandInput => ({
  ...hexInput('formId', 'Form ID', '0000000F', hint),
  browserPicker: {
    browser: 'id',
    buttonLabel: 'Browse Items',
    allowedTypes: ['WEAP', 'ARMO', 'AMMO', 'ALCH', 'MISC', 'BOOK'],
  },
});

const questIdInput = (): CommandInput => ({
  ...hexInput('questId', 'Quest ID', '00003448', 'Choose a quest or enter its Form ID.'),
  browserPicker: { browser: 'quest', buttonLabel: 'Choose Quest' },
});

// Command syntax is curated from current Starfield console-command references.
// Only commands marked "verified" have been personally confirmed through CCC so far.
export const COMMANDS: CommandDefinition[] = [
  // GAMEPLAY
  {
    id: 'god-mode',
    title: 'God Mode',
    category: 'Gameplay',
    description: 'Toggle invulnerability, infinite ammo, and other god-mode effects.',
    command: 'tgm',
    tags: ['cheat', 'invincible', 'ammo', 'toggle'],
    testStatus: 'verified',
  },
  {
    id: 'immortal-mode',
    title: 'Immortal Mode',
    category: 'Gameplay',
    description: 'Toggle immortal mode. You can take damage, but health will not drop to zero.',
    command: 'tim',
    tags: ['immortal', 'health', 'toggle'],
    testStatus: 'verified',
  },
  {
    id: 'toggle-collision',
    title: 'Toggle Collision',
    category: 'Gameplay',
    description: 'Toggle collision so the player can move through geometry and into the air.',
    command: 'tcl',
    tags: ['noclip', 'movement', 'toggle'],
    testStatus: 'verified',
  },
  {
    id: 'toggle-detection',
    title: 'Toggle Detection',
    category: 'Gameplay',
    description: 'Toggle whether NPCs can detect the player.',
    command: 'tdetect',
    tags: ['stealth', 'detection', 'toggle'],
    testStatus: 'verified',
  },
  {
    id: 'toggle-combat-ai',
    title: 'Toggle Combat AI',
    category: 'Gameplay',
    description: 'Toggle combat behavior for NPCs.',
    command: 'tcai',
    tags: ['ai', 'combat', 'npc', 'toggle'],
    testStatus: 'verified',
  },
  {
    id: 'toggle-ai',
    title: 'Toggle All AI',
    category: 'Gameplay',
    description: 'Toggle general NPC AI processing globally.',
    command: 'tai',
    tags: ['ai', 'npc', 'toggle'],
    warning: 'This affects NPC behavior globally. Run the command again to restore AI processing.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'kill-hostiles',
    title: 'Kill Nearby Hostiles',
    category: 'Gameplay',
    description: 'Kill hostile actors in the nearby area.',
    command: 'kah',
    tags: ['kill', 'hostile', 'combat'],
    warning: 'This can kill nearby hostile actors immediately, including enemies involved in scripted encounters.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'kill-all-nearby',
    title: 'Kill Everyone Nearby',
    category: 'Gameplay',
    description: 'Kill actors in the nearby area.',
    command: 'killall',
    tags: ['kill', 'npc', 'all'],
    warning: 'This can kill friendly, neutral, or quest-related actors in the area. Use only on a disposable save.',
    risk: 'danger',
    testStatus: 'verified',
  },
  {
    id: 'speech-success-on',
    title: 'Always Succeed Speech Challenges',
    category: 'Gameplay',
    description: 'Force speech challenges to succeed.',
    command: 'setforcespeechchallengealwayssucceed 1',
    tags: ['speech', 'persuasion', 'dialogue'],
    warning: 'This changes speech-challenge behavior until disabled.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'speech-success-off',
    title: 'Restore Normal Speech Challenges',
    category: 'Gameplay',
    description: 'Disable forced speech-challenge success.',
    command: 'setforcespeechchallengealwayssucceed 0',
    tags: ['speech', 'persuasion', 'dialogue', 'restore'],
    testStatus: 'verified',
  },
  {
    id: 'clear-bounty',
    title: 'Pay Bounty',
    category: 'Gameplay',
    description: 'Pay the current bounty for a faction using your credits. You avoid jail and keep stolen goods.',
    command: 'player.paycrimegold 0 0 {factionId}',
    inputs: [{
      ...hexInput('factionId', 'Faction', '00010B30', 'Choose a faction or enter its Form ID.'),
      picker: BOUNTY_FACTION_PICKER,
    }],
    tags: ['crime', 'bounty', 'faction', 'credits', 'pay'],
    warning: 'This pays the selected faction bounty from your current credits. It is not a free bounty removal.',
    risk: 'caution',
    testStatus: 'verified',
  },

  // PLAYER
  {
    id: 'add-xp',
    title: 'Add Experience',
    category: 'Player',
    description: 'Add experience points to the player. Normal level-up processing should award perk points.',
    command: 'player.modav experience {amount}',
    inputs: [
      { key: 'amount', label: 'XP Amount', type: 'number', defaultValue: 1000, min: 1, step: 1 },
    ],
    tags: ['xp', 'experience', 'level', 'perk points'],
    warning: 'Large XP amounts can cause many levels to process at once. Make a save first.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-level',
    title: 'Increase Player Level',
    category: 'Player',
    description: 'Raise the player directly to the chosen level. Starfield does not allow this command to lower your level.',
    command: 'player.setlevel {level}',
    inputs: [
      { key: 'level', label: 'New Level', type: 'number', defaultValue: 10, min: 1, step: 1, hint: 'Increase only. Reload an earlier save to undo.' },
    ],
    tags: ['level', 'progression', 'increase'],
    warning: 'This is effectively one-way on the current save: Starfield refuses requests below your current level. It also bypasses normal XP progression, so save first and reload if you need to undo it.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'modify-carry-weight',
    title: 'Adjust Carry Weight (+/-)',
    category: 'Player',
    description: 'Add to or subtract from your current maximum carry weight. Positive numbers add capacity; negative numbers remove it.',
    command: 'player.modav carryweight {amount}',
    inputs: [
      { key: 'amount', label: 'Change Amount', type: 'number', defaultValue: 100, step: 1 },
    ],
    tags: ['carry', 'weight', 'actor value', 'modav', 'add', 'subtract'],
    warning: 'This changes carry weight relative to its current value. Positive values add capacity and negative values subtract it. Extreme values may produce undesirable saved actor values.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-carry-weight-total',
    title: 'Set Carry Weight Effective Total',
    category: 'Player',
    description: 'Set the final carry-weight total while compensating for active equipment, perks, and other modifiers.',
    command: 'ccc.seteffectivetotal player CarryWeight {value}',
    inputs: [
      { key: 'value', label: 'Effective Carry Weight', type: 'number', defaultValue: 250, min: 1, max: 1000000, step: 1, hint: 'CCC previews the calculated base before applying it.' },
    ],
    tags: ['carry', 'weight', 'actor value', 'effective total', 'modifier'],
    warning: 'CCC calculates a base value from the modifiers active at execution time. Changing equipment, perks, or effects afterward can change the effective total again.',
    risk: 'caution',
    effectiveTotal: true,
    testStatus: 'verified',
  },
  {
    id: 'player-scale',
    title: 'Change Player Size',
    category: 'Player',
    description: 'Resize the player character only. This is different from Set Target / Reference Scale. 1 is the normal scale.',
    command: 'player.setscale {scale}',
    inputs: [
      { key: 'scale', label: 'Scale', type: 'number', defaultValue: 1, min: 0.1, max: 3, step: 0.05, hint: 'Default: 1' },
    ],
    tags: ['scale', 'size', 'height', 'player'],
    warning: 'Non-default player scale can affect camera position, animation alignment, collision, and interactions. Use 1 to restore normal scale.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'movement-speed',
    title: 'Set Movement Speed',
    category: 'Player',
    description: 'Set the player movement-speed multiplier. 100 is the normal baseline.',
    command: 'player.setav speedmult {value}',
    inputs: [
      { key: 'value', label: 'Speed Multiplier', type: 'number', defaultValue: 100, min: 1, max: 1000, step: 1, hint: 'Default: 100' },
    ],
    tags: ['speed', 'movement'],
    warning: 'Extreme values can make movement difficult to control. Use 100 to restore the normal baseline.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'max-health',
    title: 'Set Max Health',
    category: 'Player',
    description: 'Set the player health actor value.',
    command: 'player.setav health {value}',
    inputs: [
      { key: 'value', label: 'Health', type: 'number', defaultValue: 500, min: 1, step: 1 },
    ],
    tags: ['health', 'actor value'],
    warning: 'This directly changes a saved player actor value.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'restore-player-health',
    title: 'Restore Player Health',
    category: 'Player',
    description: 'Restore the player to full health without changing the maximum health actor value.',
    command: 'player.resethealth',
    tags: ['health', 'heal', 'restore', 'resethealth'],
    testStatus: 'verified',
  },
  {
    id: 'inspect-player-actor-value',
    title: 'Inspect Player Actor Value',
    category: 'Player',
    description: 'Read any player actor value by name and capture the result in CCC.',
    command: 'player.getav {actorValue}',
    inputs: [
      { key: 'actorValue', label: 'Actor Value', type: 'text', defaultValue: 'Health', pattern: ACTOR_VALUE_PATTERN, hint: 'Choose a common value or enter a name manually.', picker: PLAYER_ACTOR_VALUE_PICKER },
    ],
    tags: ['inspect', 'player', 'actor value', 'getav', 'health', 'carry weight', 'speed', 'read only'],
    captureOutput: true,
    testStatus: 'verified',
  },
  {
    id: 'force-enable-player-controls',
    title: 'Force Enable Player Controls',
    category: 'Player',
    description: 'Force-enable player controls when a stuck input layer leaves movement or interaction disabled.',
    command: 'fepc',
    tags: ['controls', 'input', 'stuck', 'fix', 'forceenableplayercontrols'],
    warning: 'This overrides control-disable layers instead of fixing the script or scene that created them. Use Reset Forced Player Controls afterward if needed.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'reset-force-enabled-player-controls',
    title: 'Reset Forced Player Controls',
    category: 'Player',
    description: 'Remove the Force Enable Player Controls override and return control handling to normal game layers.',
    command: 'resetforceenabledplayercontrols',
    tags: ['controls', 'input', 'restore', 'reset'],
    testStatus: 'verified',
  },
  {
    id: 'character-creator-full',
    title: 'Open Full Character Creator (Advanced)',
    category: 'Player',
    description: 'Open the original full character creator, including background and trait options.',
    command: 'showlooksmenu player 1',
    tags: ['appearance', 'character', 'creator', 'traits', 'background'],
    warning: 'VERY DANGEROUS: opening showlooksmenu player 1 resets your current appearance and enters the original character-creation flow. In current Starfield there is no reliable way to fully cancel back to gameplay; you may have to complete the profile/name flow to exit. It can also change background, traits, name, and pronouns. Make a manual save first. Use Open Appearance Editor for safer appearance-only changes.',
    risk: 'danger',
    testStatus: 'verified',
  },
  {
    id: 'character-creator-partial',
    title: 'Open Appearance Editor',
    category: 'Player',
    description: 'Open the partial character editor while leaving background and traits intact.',
    command: 'showlooksmenu player 2',
    tags: ['appearance', 'character', 'creator'],
    testStatus: 'verified',
  },
  {
    id: 'teleport-player-to-ref',
    title: 'Teleport Player to Reference',
    category: 'Player',
    description: 'Teleport the player to an existing NPC or object using its Reference ID.',
    command: 'player.moveto {refId}',
    inputs: [hexInput('refId', 'Reference ID', '000BDA6A')],
    tags: ['teleport', 'moveto', 'reference', 'npc'],
    warning: 'Teleporting to an arbitrary reference can place you inside geometry, in unloaded areas, or in dangerous locations.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-player-position-axis',
    title: 'Set Player Coordinate Axis',
    category: 'Player',
    description: 'Set the player to an absolute coordinate on a single X, Y, or Z axis. This is not a relative movement amount.',
    command: 'player.setpos {axis} {value}',
    inputs: [
      { key: 'axis', label: 'Axis', type: 'text', defaultValue: 'x', pattern: AXIS_PATTERN, hint: 'x, y, or z' },
      { key: 'value', label: 'Coordinate', type: 'number', placeholder: '5', step: 0.1, hint: 'Absolute coordinate; small changes can move far.' },
    ],
    tags: ['position', 'coordinate', 'movement', 'axis', 'spacewalk', 'setpos'],
    warning: 'This sets an absolute coordinate, not an offset. Even values around 15 can move the player a surprising distance vertically. Save first and enter the value deliberately.',
    risk: 'caution',
    testStatus: 'verified',
  },

  // INVENTORY
  {
    id: 'show-player-inventory',
    title: 'Show Player Inventory',
    category: 'Inventory',
    description: 'List the player inventory with quantities, names, and Form IDs. Results open in a scrollable window and can be reopened from Activity Log.',
    command: 'player.showinventory',
    tags: ['inventory', 'form id', 'inspect', 'showinventory', 'read only'],
    captureOutput: true,
    testStatus: 'verified',
  },
  {
    id: 'search-form-ids',
    title: 'Search Form IDs',
    category: 'Inventory',
    description: 'Search CCC’s included ID catalog by name, Editor ID, Form ID, category, or record type.',
    command: 'ID Browser search: {search}',
    inputs: [
      { key: 'search', label: 'Search', type: 'text', placeholder: 'drum beat', pattern: HELP_SEARCH_PATTERN, hint: 'Name or partial name; quotes are not allowed.' },
    ],
    tags: ['form id', 'search', 'lookup', 'id browser', 'read only'],
    catalogSearch: {},
    testStatus: 'untested',
  },
  {
    id: 'search-form-ids-by-type',
    title: 'Search Form IDs by Type',
    category: 'Inventory',
    description: 'Search CCC’s included records by name while applying an exact type such as WEAP, ARMO, NPC_, PERK, or QUST.',
    command: 'ID Browser search: {search} [{recordType}]',
    inputs: [
      { key: 'search', label: 'Search', type: 'text', placeholder: 'drum beat', pattern: HELP_SEARCH_PATTERN, hint: 'Name or partial name.' },
      { key: 'recordType', label: 'Record Type', type: 'text', defaultValue: 'WEAP', pattern: RECORD_TYPE_PATTERN, hint: 'Choose a type or enter its code.', picker: FORM_TYPE_PICKER },
    ],
    tags: ['form id', 'search', 'lookup', 'weapon', 'armor', 'npc', 'quest', 'id browser', 'read only'],
    catalogSearch: { recordTypeInput: 'recordType' },
    testStatus: 'untested',
  },
  {
    id: 'add-credits',
    title: 'Add Credits',
    category: 'Inventory',
    description: 'Add credits to the player inventory. CCC limits each execution to 100,000,000 credits.',
    command: 'player.additem 0000000F {amount}',
    tags: ['money', 'credits', 'inventory'],
    inputs: [
      { key: 'amount', label: 'Amount', type: 'number', defaultValue: 10000, min: 1, max: 100000000, step: 1, hint: 'Max 100,000,000 per use. Run again for more.' },
    ],
    warning: 'Starfield does not behave well when the player credit total approaches or exceeds 999,999,999. CCC caps each execution at 100,000,000, but it cannot see your current credit balance. Avoid pushing the total near the game limit.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'add-digipicks',
    title: 'Add Digipicks',
    category: 'Inventory',
    description: 'Add a chosen number of digipicks to the player inventory.',
    command: 'player.additem 0000000A {amount}',
    tags: ['digipick', 'lockpick', 'inventory'],
    inputs: [
      { key: 'amount', label: 'Amount', type: 'number', defaultValue: 25, min: 1, step: 1 },
    ],
    testStatus: 'verified',
  },
  {
    id: 'add-med-packs',
    title: 'Add Med Packs',
    category: 'Inventory',
    description: 'Add standard Med Packs to the player inventory.',
    command: 'player.additem 0000ABF9 {amount}',
    tags: ['med pack', 'health', 'aid', 'inventory'],
    inputs: [
      { key: 'amount', label: 'Amount', type: 'number', defaultValue: 10, min: 1, step: 1 },
    ],
    testStatus: 'verified',
  },
  {
    id: 'add-ship-parts',
    title: 'Add Ship Parts',
    category: 'Inventory',
    description: 'Add Ship Parts used to repair spaceship hull damage.',
    command: 'player.additem 0003FB19 {amount}',
    tags: ['ship parts', 'ship repair', 'aid', 'inventory'],
    inputs: [
      { key: 'amount', label: 'Amount', type: 'number', defaultValue: 10, min: 1, step: 1 },
    ],
    testStatus: 'verified',
  },
  {
    id: 'add-item',
    title: 'Add Item by Form ID',
    category: 'Inventory',
    description: 'Add an arbitrary item to the player inventory using its Form ID.',
    command: 'player.additem {formId} {amount}',
    tags: ['item', 'formid', 'inventory', 'advanced'],
    inputs: [
      itemFormIdInput(),
      { key: 'amount', label: 'Amount', type: 'number', defaultValue: 1, min: 1, step: 1 },
    ],
    warning: 'Use a valid Form ID. Invalid IDs or unusual quest/scripted items may have unintended results.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'remove-item',
    title: 'Remove Item by Form ID',
    category: 'Inventory',
    description: 'Remove a chosen quantity of an item from the player inventory.',
    command: 'player.removeitem {formId} {amount}',
    tags: ['item', 'remove', 'formid', 'inventory'],
    inputs: [
      itemFormIdInput('Choose an included item or use Player Inventory to find its Form ID.'),
      { key: 'amount', label: 'Amount', type: 'number', defaultValue: 1, min: 1, step: 1 },
    ],
    warning: 'Removing quest items or scripted items can break quests or inventory scripts.',
    risk: 'danger',
    testStatus: 'verified',
  },
  {
    id: 'equip-item',
    title: 'Equip Item by Form ID',
    category: 'Inventory',
    description: 'Equip an item on the player. If the item is missing, the command may add it.',
    command: 'player.equipitem {formId}',
    tags: ['equip', 'item', 'weapon', 'armor'],
    inputs: [{
      ...hexInput('formId', 'Form ID', '00228829', 'Choose an included weapon or armor, or use Player Inventory.'),
      browserPicker: { browser: 'id', buttonLabel: 'Browse Equipment', allowedTypes: ['WEAP', 'ARMO'] },
    }],
    warning: 'Use an equippable item Form ID. Some unusual or scripted equipment can behave unexpectedly.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'unequip-item',
    title: 'Unequip Item by Form ID',
    category: 'Inventory',
    description: 'Unequip a specific item from the player.',
    command: 'player.unequipitem {formId}',
    tags: ['unequip', 'item', 'weapon', 'armor'],
    inputs: [{
      ...hexInput('formId', 'Form ID', '00228829', 'Choose an included weapon or armor, or use Player Inventory.'),
      browserPicker: { browser: 'id', buttonLabel: 'Browse Equipment', allowedTypes: ['WEAP', 'ARMO'] },
    }],
    testStatus: 'verified',
  },
  {
    id: 'drop-item',
    title: 'Drop Item by Form ID',
    category: 'Inventory',
    description: 'Drop a chosen quantity of an item from the player inventory into the world.',
    command: 'player.drop {formId} {amount}',
    tags: ['drop', 'item', 'inventory'],
    inputs: [
      itemFormIdInput('Choose an included item or use Player Inventory to find its Form ID.'),
      { key: 'amount', label: 'Amount', type: 'number', defaultValue: 1, min: 1, step: 1 },
    ],
    warning: 'Do not use this on quest items or items you cannot safely recover.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'spawn-by-base-id',
    title: 'Spawn Object / NPC by Base ID',
    category: 'Inventory',
    description: 'Create one or more new instances of an object, creature, NPC, or other Base ID at the player.',
    command: 'player.placeatme {baseId} {amount}',
    tags: ['spawn', 'placeatme', 'base id', 'npc', 'object'],
    inputs: [
      {
        ...hexInput('baseId', 'Base ID', '0019121F', 'Browse included base records or enter a known Base ID.'),
        browserPicker: { browser: 'id', buttonLabel: 'Browse Base IDs' },
      },
      { key: 'amount', label: 'Amount', type: 'number', defaultValue: 1, min: 1, max: 100, step: 1 },
    ],
    warning: 'This creates new instances. Spawning unique NPCs can create duplicates and spawning many objects can destabilize or crash the game.',
    risk: 'danger',
    testStatus: 'verified',
  },

  {
    id: 'set-boostpack-horizontal',
    title: 'Set Boostpack Horizontal Base Value',
    category: 'Player',
    description: 'Set the base BoostpackHorizontalPercentage value. Starfield adds active equipment/perk modifiers to this base.',
    command: 'player.setav BoostpackHorizontalPercentage {value}',
    inputs: [
      { key: 'value', label: 'Horizontal Base Value', type: 'number', defaultValue: 100, min: 0, max: 10000, step: 1, hint: 'Do not paste the inspected effective total when modifiers are active.' },
    ],
    tags: ['boostpack', 'horizontal', 'movement', 'actor value', 'setav'],
    warning: 'TESTED BEHAVIOR: GetAV reports the effective total, but SetAV changes the base value. Entering the inspected total can stack with active modifiers and increase the final result.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-boostpack-initial-thrust',
    title: 'Set Boostpack Initial Thrust Base',
    category: 'Player',
    description: 'Set the base BoostpackThrustInitial value; modifiers are added separately.',
    command: 'player.setav BoostpackThrustInitial {value}',
    inputs: [
      { key: 'value', label: 'Initial Thrust Base', type: 'number', defaultValue: 500, min: 0, max: 10000, step: 1, hint: 'Do not paste the inspected effective total when modifiers are active.' },
    ],
    tags: ['boostpack', 'thrust', 'movement', 'actor value', 'setav'],
    warning: 'TESTED BEHAVIOR: GetAV reports the effective total, but SetAV changes the base value. Entering that total can stack with modifiers. Extreme thrust values can make movement difficult to control.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-boostpack-horizontal-total',
    title: 'Set Boostpack Horizontal Effective Total',
    category: 'Player',
    description: 'Set the final BoostpackHorizontalPercentage total while preserving the currently detected modifier contribution.',
    command: 'ccc.seteffectivetotal player BoostpackHorizontalPercentage {value}',
    inputs: [{ key: 'value', label: 'Desired Effective Total', type: 'number', defaultValue: 100, min: 0, max: 10000, step: 1 }],
    tags: ['boostpack', 'horizontal', 'effective total', 'actor value'],
    warning: 'CCC calculates a new base from the current base and effective values. Review the calculation before applying it.',
    risk: 'caution',
    testStatus: 'verified',
    effectiveTotal: true,
  },
  {
    id: 'set-boostpack-sustained-thrust',
    title: 'Set Boostpack Sustained Thrust Base',
    category: 'Player',
    description: 'Set the base BoostpackThrustSustained value; modifiers are added separately.',
    command: 'player.setav BoostpackThrustSustained {value}',
    inputs: [
      { key: 'value', label: 'Sustained Thrust Base', type: 'number', defaultValue: 100, min: 0, max: 10000, step: 1, hint: 'Do not paste the inspected effective total when modifiers are active.' },
    ],
    tags: ['boostpack', 'thrust', 'movement', 'actor value', 'setav'],
    warning: 'TESTED BEHAVIOR: GetAV reports the effective total, but SetAV changes the base value. Entering that total can stack with modifiers. Extreme thrust values can make movement difficult to control.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-boostpack-initial-thrust-total',
    title: 'Set Boostpack Initial Thrust Effective Total',
    category: 'Player',
    description: 'Set the final BoostpackThrustInitial total while preserving the currently detected modifier contribution.',
    command: 'ccc.seteffectivetotal player BoostpackThrustInitial {value}',
    inputs: [{ key: 'value', label: 'Desired Effective Total', type: 'number', defaultValue: 500, min: 0, max: 10000, step: 1 }],
    tags: ['boostpack', 'initial thrust', 'effective total', 'actor value'],
    warning: 'Extreme thrust values can make movement difficult to control. Review CCC\'s calculated base before applying it.',
    risk: 'caution',
    testStatus: 'verified',
    effectiveTotal: true,
  },
  {
    id: 'set-boostpack-time-to-sustained',
    title: 'Set Boostpack Transition-Time Base',
    category: 'Player',
    description: 'Set the base BoostpackTimetoSustained value controlling the transition to sustained thrust.',
    command: 'player.setav BoostpackTimetoSustained {value}',
    inputs: [
      { key: 'value', label: 'Transition-Time Base', type: 'number', defaultValue: 1, min: 0, max: 100, step: 0.1, hint: 'Do not paste the inspected effective total when modifiers are active.' },
    ],
    tags: ['boostpack', 'thrust', 'time', 'movement', 'actor value', 'setav'],
    warning: 'TESTED BEHAVIOR: GetAV reports the effective total, but SetAV changes the base value. Entering that total can stack with modifiers. Large values can make boost behavior feel delayed or broken.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-boostpack-sustained-thrust-total',
    title: 'Set Boostpack Sustained Thrust Effective Total',
    category: 'Player',
    description: 'Set the final BoostpackThrustSustained total while preserving the currently detected modifier contribution.',
    command: 'ccc.seteffectivetotal player BoostpackThrustSustained {value}',
    inputs: [{ key: 'value', label: 'Desired Effective Total', type: 'number', defaultValue: 100, min: 0, max: 10000, step: 1 }],
    tags: ['boostpack', 'sustained thrust', 'effective total', 'actor value'],
    warning: 'Extreme thrust values can make movement difficult to control. Review CCC\'s calculated base before applying it.',
    risk: 'caution',
    testStatus: 'verified',
    effectiveTotal: true,
  },
  {
    id: 'set-boostpack-time-to-sustained-total',
    title: 'Set Boostpack Transition-Time Effective Total',
    category: 'Player',
    description: 'Set the final BoostpackTimetoSustained total while preserving the currently detected modifier contribution.',
    command: 'ccc.seteffectivetotal player BoostpackTimetoSustained {value}',
    inputs: [{ key: 'value', label: 'Desired Effective Total', type: 'number', defaultValue: 1, min: 0, max: 100, step: 0.1 }],
    tags: ['boostpack', 'transition time', 'effective total', 'actor value'],
    warning: 'Large values can make boost behavior feel delayed or broken. Review CCC\'s calculated base before applying it.',
    risk: 'caution',
    testStatus: 'verified',
    effectiveTotal: true,
  },

  // SKILLS / POWERS / EFFECTS
  {
    id: 'add-skill-points',
    title: 'Add Skill Points',
    category: 'Skills',
    description: 'Add spendable skill points without directly forcing a perk rank.',
    command: 'CGF "Game.AddPerkPoints" {amount}',
    tags: ['perk points', 'skill points', 'skills', 'progression'],
    inputs: [
      { key: 'amount', label: 'Skill Points', type: 'number', defaultValue: 1, min: 1, max: 1000, step: 1 },
    ],
    warning: 'This changes character progression by adding spendable skill points. Add only the amount you actually want.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'add-perk',
    title: 'Add Perk / Skill by Form ID',
    category: 'Skills',
    description: 'Add a perk, skill, trait, or background by Form ID.',
    command: 'player.addperk {formId}',
    tags: ['perk', 'skill', 'trait', 'background', 'formid'],
    inputs: [{
      ...hexInput('formId', 'Form ID', '002C59D9', 'Browse included perks, skills, traits, and backgrounds or enter a Form ID.'),
      browserPicker: { browser: 'id', buttonLabel: 'Browse Perks', allowedTypes: ['PERK'], allowedCategories: ['Perks'] },
    }],
    warning: 'Adding progression records without normal prerequisites may produce unusual progression states.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'remove-perk',
    title: 'Remove Perk / Skill by Form ID',
    category: 'Skills',
    description: 'Remove a perk, skill, trait, or background by Form ID.',
    command: 'player.removeperk {formId}',
    tags: ['perk', 'skill', 'trait', 'background', 'formid'],
    inputs: [{
      ...hexInput('formId', 'Form ID', '002C59D9', 'Browse included perks, skills, traits, and backgrounds or enter a Form ID.'),
      browserPicker: { browser: 'id', buttonLabel: 'Browse Perks', allowedTypes: ['PERK'], allowedCategories: ['Perks'] },
    }],
    warning: 'Removing progression records can create inconsistent character progression. Make a save first.',
    risk: 'danger',
    testStatus: 'verified',
  },
  {
    id: 'all-powers',
    title: 'Grant All Powers',
    category: 'Skills',
    description: 'Grant all Starborn powers.',
    command: 'psb',
    tags: ['powers', 'starborn', 'spellbook'],
    warning: 'This grants a large set of progression content at once and can permanently alter power progression.',
    risk: 'danger',
    testStatus: 'verified',
  },
  {
    id: 'set-star-power',
    title: 'Set Star Power',
    category: 'Skills',
    description: 'Set the player Starborn power resource actor value.',
    command: 'player.setav starpower {value}',
    tags: ['starborn', 'power', 'actor value'],
    inputs: [
      { key: 'value', label: 'Star Power', type: 'number', defaultValue: 100, min: 0, step: 1 },
    ],
    warning: 'This directly changes a player actor value.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-star-power-recharge-rate',
    title: 'Set Star Power Recharge Rate',
    category: 'Skills',
    description: 'Set the Starpowerratemult actor value that controls Starborn power-meter regeneration.',
    command: 'player.setav starpowerratemult {value}',
    inputs: [
      { key: 'value', label: 'Recharge Multiplier', type: 'number', defaultValue: 100, min: 0, max: 100000, step: 1, hint: 'Inspect starpowerratemult first to record your current value.' },
    ],
    tags: ['starborn', 'power', 'recharge', 'starpowerratemult', 'actor value'],
    warning: 'This directly overrides a saved player actor value. Record the current starpowerratemult value before changing it so you can restore it later.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'add-spell',
    title: 'Add Power / Spell by Form ID',
    category: 'Skills',
    description: 'Add a Starborn power or another known spell record to the player by Form ID.',
    command: 'player.addspell {formId}',
    tags: ['spell', 'effect', 'power', 'status'],
    inputs: [{
      ...hexInput('formId', 'Power / Spell ID', '002BACBA', 'Browse included Starborn powers or enter a known spell Form ID.'),
      browserPicker: { browser: 'id', buttonLabel: 'Browse Powers', allowedTypes: ['SPEL'], allowedCategories: ['Powers'] },
    }],
    warning: 'Adding arbitrary effects can create persistent or unintended status effects. Only use IDs you understand.',
    risk: 'danger',
    testStatus: 'verified',
  },
  {
    id: 'remove-spell',
    title: 'Remove Spell / Status Effect by Form ID',
    category: 'Skills',
    description: 'Remove a spell or stuck status-effect record from the player by Form ID.',
    command: 'player.removespell {formId}',
    tags: ['spell', 'status effect', 'weather bug', 'fix'],
    inputs: [{
      ...hexInput('formId', 'Power / Effect ID', '00163FE7', 'Browse included powers and removable effects or enter a Form ID.'),
      browserPicker: { browser: 'id', buttonLabel: 'Browse Effects', allowedTypes: ['SPEL'], allowedCategories: ['Powers', 'Effects'] },
    }],
    warning: 'Removing the wrong effect can remove legitimate powers or scripted effects. Confirm the effect ID first.',
    risk: 'caution',
    testStatus: 'verified',
  },

  // CAMERA
  {
    id: 'free-camera',
    title: 'Toggle Free Camera',
    category: 'Camera',
    description: 'Toggle free-camera mode while the world continues running.',
    command: 'tfc',
    tags: ['camera', 'photo', 'toggle'],
    testStatus: 'verified',
  },
  {
    id: 'free-camera-freeze',
    title: 'Enter Free Camera + Freeze',
    category: 'Camera',
    description: 'Enter free camera while freezing world animation. Use Toggle Free Camera to exit and resume gameplay.',
    command: 'tfc 1',
    tags: ['camera', 'photo', 'freeze', 'enter'],
    warning: 'Do not run tfc 1 a second time to exit. Use Toggle Free Camera (tfc) to return to normal camera/gameplay.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'toggle-hud',
    title: 'Toggle HUD / Interface',
    category: 'Camera',
    description: 'Toggle the game interface for clean screenshots.',
    command: 'tm',
    tags: ['hud', 'ui', 'photo', 'toggle'],
    warning: 'This hides the game UI, including the normal console display. Run the command again to restore it.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'free-camera-speed',
    title: 'Set Free Camera Speed',
    category: 'Camera',
    description: 'Set the movement-speed multiplier for the free camera. The normal/default value is 2.',
    command: 'sucsm {speed}',
    tags: ['camera', 'photo', 'speed', 'sucsm'],
    inputs: [
      { key: 'speed', label: 'Camera Speed', type: 'number', defaultValue: 2, min: 0.1, max: 100, step: 0.1, hint: 'Default: 2' },
    ],
    testStatus: 'verified',
  },
  {
    id: 'clear-screen-blood',
    title: 'Clear Screen Blood',
    category: 'Camera',
    description: 'Clear blood/damage overlays from the screen.',
    command: 'ClearScreenBlood',
    tags: ['camera', 'photo', 'blood', 'screen'],
    testStatus: 'verified',
  },

  // WORLD
  {
    id: 'toggle-pause',
    title: 'Toggle Game Pause',
    category: 'World',
    description: 'Toggle the gameplay pause state.',
    command: 'tgp',
    tags: ['pause', 'world', 'toggle'],
    testStatus: 'verified',
  },
  {
    id: 'game-speed',
    title: 'Set Game Speed',
    category: 'World',
    description: 'Set the global gameplay speed multiplier. 1 is normal speed.',
    command: 'sgtm {value}',
    tags: ['time', 'speed', 'slow motion'],
    inputs: [
      { key: 'value', label: 'Multiplier', type: 'number', defaultValue: 1, min: 0.01, max: 10, step: 0.01, hint: 'Default: 1' },
    ],
    warning: 'Very low or high multipliers can make the game difficult to control. Use 1 to restore normal speed.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'pass-time',
    title: 'Wait Anywhere',
    category: 'World',
    description: 'Choose how many hours to wait without needing a bed or chair.',
    command: 'passtime {hours}',
    tags: ['time', 'wait', 'hours', 'wait anywhere'],
    inputs: [
      { key: 'hours', label: 'Hours', type: 'number', defaultValue: 1, min: 1, max: 24, step: 1, hint: 'Choose 1–24 hours.' },
    ],
    testStatus: 'verified',
  },
  {
    id: 'toggle-grass',
    title: 'Toggle Grass',
    category: 'World',
    description: 'Show or hide grass rendering. Run it again to restore the previous state.',
    command: 'ToggleGrass',
    tags: ['grass', 'rendering', 'world', 'togglegrass'],
    testStatus: 'verified',
  },
  {
    id: 'toggle-sky',
    title: 'Toggle Sky',
    category: 'World',
    description: 'Show or hide sky rendering. Run it again to restore the previous state.',
    command: 'ts',
    tags: ['sky', 'rendering', 'world', 'toggle sky', 'togglesky'],
    testStatus: 'verified',
  },
  {
    id: 'set-interior-gravity',
    title: 'Set Interior Gravity',
    category: 'World',
    description: 'Set the gravity scale for the current interior cell. Use 1 to restore normal gravity.',
    command: 'setgravityscale {value}',
    inputs: [
      { key: 'value', label: 'Gravity Scale', type: 'number', defaultValue: 1, min: 0, max: 10, step: 0.1, hint: 'Interior cells only. 0 removes gravity; 1 is normal.' },
    ],
    tags: ['gravity', 'zero g', 'interior', 'cell', 'setgravityscale'],
    warning: 'This only works inside interior cells. Unusual values affect movement and physics in the current interior; use 1 to restore normal gravity before leaving.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-scanner-range',
    title: 'Set Scanner Scan Range',
    category: 'World',
    description: 'Set the hand-scanner distance used for scanning objects, flora, and fauna.',
    command: 'setgs fHandScannerScanRange {value}',
    inputs: [
      { key: 'value', label: 'Scan Range', type: 'number', defaultValue: 200, min: 1, max: 100000, step: 1 },
    ],
    tags: ['scanner', 'range', 'hand scanner', 'setgs'],
    warning: 'This changes a Game Setting for the current runtime and may need to be reapplied after loading or restarting the game.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-scanner-base-range',
    title: 'Set Scanner Base Range',
    category: 'World',
    description: 'Set the hand-scanner base distance used by scanner-range calculations.',
    command: 'setgs fHandScannerBaseRange {value}',
    inputs: [
      { key: 'value', label: 'Base Range', type: 'number', defaultValue: 200, min: 1, max: 100000, step: 1 },
    ],
    tags: ['scanner', 'range', 'base range', 'hand scanner', 'setgs'],
    warning: 'This changes a Game Setting for the current runtime and may need to be reapplied after loading or restarting the game. Inspect the original value first if you want to restore it exactly.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-scanner-social-range',
    title: 'Set Scanner Social Range',
    category: 'World',
    description: 'Set the hand-scanner social / NPC interaction scan distance.',
    command: 'setgs fHandScannerSocialRange {value}',
    inputs: [
      { key: 'value', label: 'Social Range', type: 'number', defaultValue: 200, min: 1, max: 100000, step: 1 },
    ],
    tags: ['scanner', 'range', 'social', 'npc', 'setgs'],
    warning: 'This changes a Game Setting for the current runtime and may need to be reapplied after loading or restarting the game.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'show-map-markers',
    title: 'Reveal Planet Map Markers',
    category: 'World',
    description: 'Add map markers for locations on the current planet surface.',
    command: 'tmm 1',
    tags: ['map', 'markers', 'locations'],
    warning: 'Published reports indicate the added markers may persist and may not be cleanly undone with tmm 0 during the session.',
    risk: 'danger',
    testStatus: 'verified',
  },
  {
    id: 'center-on-cell',
    title: 'Teleport to Cell',
    category: 'World',
    description: 'Teleport directly to a cell using its Editor ID / cell name.',
    command: 'coc {cellName}',
    tags: ['coc', 'cell', 'teleport', 'location'],
    inputs: [
      { key: 'cellName', label: 'Cell Name / Editor ID', type: 'text', placeholder: 'CityAkilaTheRock01', pattern: '^\\S+$', hint: 'Choose a popular location or enter an exact Editor ID.', picker: POPULAR_LOCATION_PICKER },
    ],
    warning: 'An invalid or unsuitable cell can place you in test areas, unloaded spaces, or locations with broken progression context.',
    risk: 'danger',
    testStatus: 'verified',
  },
  {
    id: 'inspect-game-setting',
    title: 'Inspect Game Setting',
    category: 'World',
    description: 'Read the current value of any Game Setting before changing it.',
    command: 'getgs {setting}',
    inputs: [
      { key: 'setting', label: 'Game Setting', type: 'text', defaultValue: 'uSpaceshipMaximumOwnedSpaceships', pattern: GAME_SETTING_PATTERN, hint: 'Choose a known setting or enter an exact Game Setting name.', picker: GAME_SETTING_PICKER },
    ],
    tags: ['game setting', 'getgs', 'inspect', 'read only', 'advanced'],
    captureOutput: true,
    testStatus: 'verified',
  },
  {
    id: 'force-weather',
    title: 'Force Weather',
    category: 'World',
    description: 'Immediately force a weather record. Choose a weather from the menu or enter any valid Weather Form ID.',
    command: 'fw {weatherId}',
    tags: ['weather', 'forceweather', 'photo', 'rain', 'snow', 'storm', 'fog'],
    inputs: [{
      ...hexInput('weatherId', 'Weather', '0002B07E', 'Choose a weather or enter its Form ID.'),
      picker: WEATHER_PICKER,
    }],
    warning: 'Weather records are location-dependent. A selected weather may look wrong or be overridden in a location or climate it was not designed for.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-weather',
    title: 'Set Weather Gradually',
    category: 'World',
    description: 'Transition toward a weather record. Choose a weather from the menu or enter any valid Weather Form ID.',
    command: 'setweather {weatherId}',
    tags: ['weather', 'transition', 'photo', 'rain', 'snow', 'storm', 'fog'],
    inputs: [{
      ...hexInput('weatherId', 'Weather', '0002B07E', 'Choose a weather or enter its Form ID.'),
      picker: WEATHER_PICKER,
    }],
    warning: 'Weather records are location-dependent. A selected weather may look wrong or be overridden by the current location, climate, or scripts.',
    risk: 'caution',
    testStatus: 'verified',
  },

  // TARGETS (NPCs / OBJECTS / WORLD REFERENCES)
  {
    id: 'select-closest-actor',
    title: 'Select Closest Actor',
    category: 'Targets',
    description: 'Set the console selection to the actor closest to the player.',
    command: 'PickClosestActor',
    tags: ['actor', 'select', 'console', 'target'],
    testStatus: 'verified',
  },
  {
    id: 'move-ref-to-player',
    title: 'Move Reference to Player',
    category: 'Targets',
    description: 'Move an existing NPC or object to the player using its Reference ID.',
    command: '{refId}.moveto player',
    tags: ['npc', 'object', 'reference', 'moveto', 'fix'],
    inputs: [hexInput('refId', 'Reference ID', '000BDA6A')],
    warning: 'Use a Reference ID, not a Base ID. Moving quest actors can trigger or disrupt scripted scenes.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'kill-ref',
    title: 'Kill Actor by Reference ID',
    category: 'Targets',
    description: 'Kill a specific actor using its Reference ID.',
    command: '{refId}.kill',
    tags: ['npc', 'kill', 'reference'],
    inputs: [hexInput('refId', 'Reference ID', '000BDA6A')],
    warning: 'Killing quest or unique actors can break quests and scripted scenes. Essential actors may only be incapacitated.',
    risk: 'danger',
    testStatus: 'verified',
  },
  {
    id: 'resurrect-ref',
    title: 'Resurrect Actor by Reference ID',
    category: 'Targets',
    description: 'Resurrect a specific dead actor using its Reference ID.',
    command: '{refId}.resurrect',
    tags: ['npc', 'resurrect', 'reference', 'fix'],
    inputs: [hexInput('refId', 'Reference ID', '000BDA6A')],
    warning: 'Resurrecting unique or quest actors can produce duplicated state, missing scripts, or broken quest logic.',
    risk: 'danger',
    testStatus: 'verified',
  },
  {
    id: 'recycle-ref',
    title: 'Recycle Actor / Reference',
    category: 'Targets',
    description: 'Recycle/reset an existing reference using its Reference ID.',
    command: '{refId}.recycleactor',
    tags: ['npc', 'recycleactor', 'reset', 'fix'],
    inputs: [hexInput('refId', 'Reference ID', '000BDA6A')],
    warning: 'RecycleActor can reset inventory, state, placement, and script-related data. Never use it casually on important NPCs.',
    risk: 'danger',
    testStatus: 'verified',
  },
  {
    id: 'disable-ref',
    title: 'Disable Reference',
    category: 'Targets',
    description: 'Disable an existing NPC or object by Reference ID.',
    command: '{refId}.disable',
    tags: ['disable', 'npc', 'object', 'reference'],
    inputs: [hexInput('refId', 'Reference ID', '00000000')],
    warning: 'Record the Reference ID before disabling anything. Disabling quest actors or objects can block progression.',
    risk: 'danger',
    testStatus: 'verified',
  },
  {
    id: 'enable-ref',
    title: 'Enable Reference',
    category: 'Targets',
    description: 'Re-enable an existing NPC or object by Reference ID.',
    command: '{refId}.enable',
    tags: ['enable', 'npc', 'object', 'reference', 'fix'],
    inputs: [hexInput('refId', 'Reference ID', '00000000')],
    warning: 'Use the exact Reference ID for the previously disabled object or actor.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'unlock-ref',
    title: 'Unlock Door / Container by Reference ID',
    category: 'Targets',
    description: 'Unlock a specific door or container reference.',
    command: '{refId}.unlock',
    tags: ['unlock', 'door', 'container', 'reference'],
    inputs: [hexInput('refId', 'Reference ID', '00000000')],
    warning: 'Quest-locked doors and scripted locks may be intentional. Forcing them open can bypass triggers or break quest flow.',
    risk: 'danger',
    testStatus: 'verified',
  },
  {
    id: 'lock-ref',
    title: 'Lock Door / Container by Reference ID',
    category: 'Targets',
    description: 'Lock a specific door or container with a chosen lock level.',
    command: '{refId}.lock {level}',
    tags: ['lock', 'door', 'container', 'reference'],
    inputs: [
      hexInput('refId', 'Reference ID', '00000000'),
      { key: 'level', label: 'Lock Level', type: 'number', defaultValue: 50, min: 0, max: 100, step: 1 },
    ],
    warning: 'Locking quest-critical doors or containers can interfere with progression.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-ref-scale',
    title: 'Set Target / Reference Scale',
    category: 'Targets',
    description: 'Resize an NPC or world reference. 1 is normal size.',
    command: '{refId}.setscale {scale}',
    tags: ['scale', 'npc', 'object', 'reference'],
    inputs: [
      hexInput('refId', 'Reference ID', '00000000'),
      { key: 'scale', label: 'Scale', type: 'number', defaultValue: 1, min: 0.1, max: 10, step: 0.1, hint: 'Default: 1' },
    ],
    warning: 'Extreme scales can cause collision, animation, or interaction problems.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-ref-ownership',
    title: 'Set Reference Ownership',
    category: 'Targets',
    description: 'Make the selected reference owned by the player using its Reference ID.',
    command: '{refId}.setownership',
    tags: ['ownership', 'steal', 'object', 'reference'],
    inputs: [hexInput('refId', 'Reference ID', '00000000')],
    warning: 'Changing ownership can affect theft/crime behavior and scripted objects.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'move-ref-axis',
    title: 'Move Reference Along Axis',
    category: 'Targets',
    description: 'Move a world reference by an offset along the X, Y, or Z axis.',
    command: '{refId}.modpos {axis} {amount}',
    tags: ['object', 'position', 'modpos', 'decorating', 'reference'],
    inputs: [
      hexInput('refId', 'Reference ID', '00000000'),
      { key: 'axis', label: 'Axis', type: 'text', defaultValue: 'z', pattern: AXIS_PATTERN, hint: 'x, y, or z' },
      { key: 'amount', label: 'Offset', type: 'number', defaultValue: 0.1, step: 0.001 },
    ],
    warning: 'Moving scripted or structural references can create visual, collision, or quest problems.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'rotate-ref-axis',
    title: 'Rotate Reference Along Axis',
    category: 'Targets',
    description: 'Rotate a world reference by an offset in degrees along the X, Y, or Z axis.',
    command: '{refId}.modangle {axis} {degrees}',
    tags: ['object', 'rotation', 'modangle', 'decorating', 'reference'],
    inputs: [
      hexInput('refId', 'Reference ID', '00000000'),
      { key: 'axis', label: 'Axis', type: 'text', defaultValue: 'z', pattern: AXIS_PATTERN, hint: 'x, y, or z' },
      { key: 'degrees', label: 'Degrees', type: 'number', defaultValue: 5, step: 0.1 },
    ],
    warning: 'Rotating scripted or structural references can create visual, collision, or quest problems.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'restore-actor-health',
    title: 'Restore Actor Health',
    category: 'Targets',
    description: 'Restore an actor to full health using its Reference ID.',
    command: '{refId}.resethealth',
    tags: ['health', 'heal', 'actor', 'npc', 'resethealth', 'reference'],
    inputs: [hexInput('refId', 'Reference ID', '00000000')],
    testStatus: 'verified',
  },
  {
    id: 'stop-actor-combat',
    title: 'Stop Actor Combat',
    category: 'Targets',
    description: 'Tell one actor to stop its current combat state using its Reference ID.',
    command: '{refId}.stopcombat',
    tags: ['combat', 'npc', 'actor', 'stopcombat', 'reference'],
    inputs: [hexInput('refId', 'Reference ID', '00000000')],
    warning: 'Scripts, factions, or nearby enemies may cause the actor to enter combat again immediately.',
    risk: 'caution',
    testStatus: 'needs-adjustment',
  },
  {
    id: 'activate-reference',
    title: 'Activate Reference',
    category: 'Targets',
    description: 'Activate a door, switch, terminal, elevator, container, or other activatable reference.',
    command: '{refId}.activate',
    tags: ['activate', 'door', 'switch', 'terminal', 'reference'],
    inputs: [hexInput('refId', 'Reference ID', '00000000')],
    warning: 'Activating scripted or quest-controlled references out of sequence can trigger events early or create progression problems.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'reset-actor-ai',
    title: 'Reset Actor AI',
    category: 'Targets',
    description: 'Reset the AI state of one NPC or actor using its Reference ID.',
    command: '{refId}.resetai',
    inputs: [hexInput('refId', 'Reference ID', '00000000')],
    tags: ['npc', 'actor', 'ai', 'resetai', 'fix', 'reference'],
    warning: 'Resetting AI can interrupt scripted packages, scenes, or quest behavior. Use it as a skip tool, not casually on quest actors.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'force-actor-repath',
    title: 'Force Actor Repath',
    category: 'Targets',
    description: 'Force one actor to recalculate its navigation path.',
    command: '{refId}.forcerepath',
    inputs: [hexInput('refId', 'Reference ID', '00000000')],
    tags: ['npc', 'actor', 'path', 'navigation', 'forcerepath', 'fix'],
    warning: "This can interrupt the actor's current package or scripted movement. It is intended for actors that appear stuck.",
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'reevaluate-actor-package',
    title: 'Reevaluate Actor Behavior',
    category: 'Targets',
    description: 'Force an NPC to reevaluate its current AI package, which can restart movement or end a stuck interaction.',
    command: '{refId}.evp',
    inputs: [hexInput('refId', 'Reference ID', '00000000')],
    tags: ['npc', 'actor', 'ai', 'package', 'evaluatepackage', 'evp', 'stuck', 'fix'],
    warning: 'Reevaluating a quest actor can interrupt dialogue, scenes, or scripted movement. Use it for an actor that appears stuck and make a manual save first.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-open-state',
    title: 'Open or Close Reference',
    category: 'Targets',
    description: 'Open or close a door or other openable reference using an explicit state.',
    command: '{refId}.setopenstate {state}',
    inputs: [
      hexInput('refId', 'Reference ID', '00000000'),
      { key: 'state', label: 'Open State', type: 'number', defaultValue: 1, min: 0, max: 1, step: 1, hint: '0 Closed, 1 Open', picker: OPEN_STATE_PICKER },
    ],
    tags: ['door', 'open', 'close', 'setopenstate', 'reference'],
    warning: 'Forcing quest-controlled doors or activators open or closed can bypass triggers or interfere with scripted scenes.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'inspect-ref-actor-value',
    title: 'Inspect Reference Actor Value',
    category: 'Targets',
    description: 'Read any actor value from a reference and capture the result in CCC.',
    command: '{refId}.getav {actorValue}',
    inputs: [
      hexInput('refId', 'Reference ID', '00000000'),
      { key: 'actorValue', label: 'Actor Value', type: 'text', defaultValue: 'Health', pattern: ACTOR_VALUE_PATTERN, hint: 'Choose a common value or enter a name manually.', picker: REFERENCE_ACTOR_VALUE_PICKER },
    ],
    tags: ['inspect', 'actor value', 'getav', 'reference', 'read only'],
    captureOutput: true,
    testStatus: 'verified',
  },
  {
    id: 'mark-ref-for-delete',
    title: 'Mark Reference for Permanent Deletion',
    category: 'Targets',
    description: 'Mark a world reference for permanent deletion when its cell reloads.',
    command: '{refId}.markfordelete',
    inputs: [hexInput('refId', 'Reference ID', '00000000')],
    tags: ['delete', 'permanent', 'markfordelete', 'reference', 'cleanup'],
    warning: 'EXTREME DANGER: MarkForDelete is permanent after the cell reloads. There is no normal way to restore the deleted reference. Prefer this only for objects you spawned yourself and verify the exact Reference ID first. Never use it casually on vanilla, quest, ship, or persistent references.',
    risk: 'danger',
    testStatus: 'untested',
  },
  {
    id: 'set-ref-position',
    title: 'Set Exact Reference Position',
    category: 'Targets',
    description: 'Set the absolute X, Y, or Z coordinate of a world reference.',
    command: '{refId}.setpos {axis} {value}',
    tags: ['object', 'position', 'setpos', 'coordinate', 'reference'],
    inputs: [
      hexInput('refId', 'Reference ID', '00000000'),
      { key: 'axis', label: 'Axis', type: 'text', defaultValue: 'z', pattern: AXIS_PATTERN, hint: 'x, y, or z' },
      { key: 'value', label: 'Coordinate', type: 'number', defaultValue: 0, step: 0.001 },
    ],
    warning: 'This sets an absolute world coordinate, not an offset. Moving scripted or structural references can break collision, visuals, or quests.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-ref-angle',
    title: 'Set Exact Reference Rotation',
    category: 'Targets',
    description: 'Set the absolute rotation angle of a world reference on the X, Y, or Z axis.',
    command: '{refId}.setangle {axis} {degrees}',
    tags: ['object', 'rotation', 'setangle', 'degrees', 'reference'],
    inputs: [
      hexInput('refId', 'Reference ID', '00000000'),
      { key: 'axis', label: 'Axis', type: 'text', defaultValue: 'z', pattern: AXIS_PATTERN, hint: 'x, y, or z' },
      { key: 'degrees', label: 'Degrees', type: 'number', defaultValue: 0, step: 0.1 },
    ],
    warning: 'This sets an absolute angle, not an offset. Rotating scripted or structural references can create visual, collision, or quest problems.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'inspect-ref-position',
    title: 'Inspect Reference Position',
    category: 'Targets',
    description: 'Read the absolute X, Y, or Z coordinate of a reference and display the console result in CCC.',
    command: '{refId}.getpos {axis}',
    tags: ['inspect', 'position', 'getpos', 'coordinate', 'reference', 'read only'],
    inputs: [
      hexInput('refId', 'Reference ID', '00000000'),
      { key: 'axis', label: 'Axis', type: 'text', defaultValue: 'z', pattern: AXIS_PATTERN, hint: 'x, y, or z' },
    ],
    captureOutput: true,
    testStatus: 'verified',
  },
  {
    id: 'inspect-ref-angle',
    title: 'Inspect Reference Rotation',
    category: 'Targets',
    description: 'Read the X, Y, or Z rotation angle of a reference and display the console result in CCC.',
    command: '{refId}.getangle {axis}',
    tags: ['inspect', 'rotation', 'getangle', 'reference', 'read only'],
    inputs: [
      hexInput('refId', 'Reference ID', '00000000'),
      { key: 'axis', label: 'Axis', type: 'text', defaultValue: 'z', pattern: AXIS_PATTERN, hint: 'x, y, or z' },
    ],
    captureOutput: true,
    testStatus: 'verified',
  },
  {
    id: 'inspect-ref-scale',
    title: 'Inspect Reference Scale',
    category: 'Untested',
    description: 'Read a reference scale. Both tested native adapters are unsafe on Starfield 1.16.244.',
    command: '{refId}.getscale',
    tags: ['inspect', 'scale', 'getscale', 'reference', 'read only'],
    inputs: [hexInput('refId', 'Reference ID', '00000000', 'Use a placed Reference ID from the current session, not a Base ID or an ID copied before reloading.')],
    captureOutput: true,
    testStatus: 'failed',
    unavailableReason: 'Disabled after TESObjectREFR::GetScale attempted to resolve missing Address Library ID 0 and crashed Starfield 1.16.244. The earlier condition-evaluator adapter also crashed.',
    intakeGroup: 'Blocked — Known Crash',
  },
  {
    id: 'add-item-mod',
    title: 'Attach Weapon / Armor Mod',
    category: 'Targets',
    description: 'Attach a modifier to a dropped weapon or armor reference using its Reference ID and a Mod ID.',
    command: '{refId}.amod {modId}',
    tags: ['weapon', 'armor', 'mod', 'amod', 'modifier'],
    inputs: [
      hexInput('refId', 'Item Reference ID', 'FF00BB78'),
      {
        ...hexInput('modId', 'Modifier / Mod ID', '002BDD72', 'Choose an included OMOD record or enter its Form ID.'),
        browserPicker: { browser: 'id', buttonLabel: 'Browse Mods', allowedTypes: ['OMOD'] },
      },
    ],
    warning: 'Many OMOD IDs are weapon- or armor-specific. The game may accept an incompatible modifier but produce janky or broken equipment. Confirm the exact mod ID for that item first.',
    risk: 'caution',
    testStatus: 'untested',
  },
  {
    id: 'remove-item-mod',
    title: 'Remove Weapon / Armor Mod',
    category: 'Targets',
    description: 'Remove a modifier from a dropped weapon or armor reference.',
    command: '{refId}.rmod {modId}',
    tags: ['weapon', 'armor', 'mod', 'rmod', 'modifier'],
    inputs: [
      hexInput('refId', 'Item Reference ID', 'FF00BB78'),
      {
        ...hexInput('modId', 'Modifier / Mod ID', '002BDD72', 'Choose an included OMOD record or enter its Form ID.'),
        browserPicker: { browser: 'id', buttonLabel: 'Browse Mods', allowedTypes: ['OMOD'] },
      },
    ],
    warning: 'Removing the wrong modifier can change item quality or remove an intended attachment.',
    risk: 'caution',
    testStatus: 'untested',
  },
  {
    id: 'inspect-companion-affinity',
    title: 'Inspect Companion Affinity',
    category: 'Targets',
    description: 'Read com_affinity. 1300 is the commonly used progression target; the raw value can sometimes continue above 1300.',
    command: '{refId}.getav com_affinity',
    tags: ['companion', 'affinity', 'relationship', 'inspect', 'read only'],
    inputs: [{
      ...hexInput('refId', 'Companion', '00005986', 'Choose a companion or enter its Reference ID.'),
      picker: CORE_COMPANION_PICKER,
    }],
    captureOutput: true,
    testStatus: 'verified',
  },
  {
    id: 'inspect-companion-affinity-level',
    title: 'Inspect Companion Relationship Level',
    category: 'Targets',
    description: 'Read com_affinitylevel: 0 Neutral, 1 Friendship, 2 Affection/Romance, 3 Commitment. Maximum relationship level: 3.',
    command: '{refId}.getav com_affinitylevel',
    tags: ['companion', 'affinity', 'relationship level', 'inspect', 'read only'],
    inputs: [{
      ...hexInput('refId', 'Companion', '00005986', 'Choose a companion or enter its Reference ID.'),
      picker: CORE_COMPANION_PICKER,
    }],
    captureOutput: true,
    testStatus: 'verified',
  },
  {
    id: 'inspect-companion-anger',
    title: 'Inspect Companion Anger Level',
    category: 'Targets',
    description: 'Read com_angerlevel: 0 Calm, 1 Annoyed, 2 Very Angry. Maximum anger level: 2.',
    command: '{refId}.getav com_angerlevel',
    tags: ['companion', 'anger', 'relationship', 'inspect', 'read only'],
    inputs: [{
      ...hexInput('refId', 'Companion', '00005986', 'Choose a companion or enter its Reference ID.'),
      picker: CORE_COMPANION_PICKER,
    }],
    captureOutput: true,
    testStatus: 'verified',
  },
  {
    id: 'set-companion-affinity',
    title: 'Set Companion Affinity',
    category: 'Targets',
    description: 'Set affinity for one of the four core affinity-capable companions, or enter a companion Reference ID manually.',
    command: '{refId}.setav com_affinity {value}',
    tags: ['companion', 'affinity', 'relationship', 'npc'],
    inputs: [
      {
        ...hexInput('refId', 'Companion', '00005986', 'Choose a companion or enter its Reference ID.'),
        picker: CORE_COMPANION_PICKER,
      },
      { key: 'value', label: 'Affinity', type: 'number', defaultValue: 99, step: 1 },
    ],
    warning: 'Changing affinity directly can skip natural relationship progression and dialogue triggers. Values just below thresholds are generally safer than jumping far ahead.',
    risk: 'danger',
    testStatus: 'verified',
  },
  {
    id: 'set-companion-affinity-level',
    title: 'Set Companion Relationship Level',
    category: 'Targets',
    description: 'Set relationship level for one of the four core affinity-capable companions, or enter a companion Reference ID manually.',
    command: '{refId}.setav com_affinitylevel {value}',
    tags: ['companion', 'affinity', 'relationship', 'npc'],
    inputs: [
      {
        ...hexInput('refId', 'Companion', '00005986', 'Choose a companion or enter its Reference ID.'),
        picker: CORE_COMPANION_PICKER,
      },
      { key: 'value', label: 'Relationship Level', type: 'number', defaultValue: 1, min: 0, max: 3, step: 1, hint: '0 Neutral, 1 Friendship, 2 Affection, 3 Commitment' },
    ],
    warning: 'Direct relationship-level changes can skip dialogue and quest triggers. Use only on a backup save.',
    risk: 'danger',
    testStatus: 'verified',
  },

  {
    id: 'set-companion-anger',
    title: 'Set Companion Anger Level',
    category: 'Targets',
    description: 'Set the anger state for one of the four core affinity-capable companions, or enter a companion Reference ID manually.',
    command: '{refId}.setav com_angerlevel {value}',
    tags: ['companion', 'anger', 'relationship', 'npc'],
    inputs: [
      {
        ...hexInput('refId', 'Companion', '00005986', 'Choose a companion or enter its Reference ID.'),
        picker: CORE_COMPANION_PICKER,
      },
      { key: 'value', label: 'Anger Level', type: 'number', defaultValue: 0, min: 0, max: 2, step: 1, hint: '0 Normal, 1 Angry/reluctant, 2 Refusal' },
    ],
    warning: 'Direct anger-state changes can interfere with companion reactions, dialogue, and relationship progression. Use a backup save.',
    risk: 'danger',
    testStatus: 'verified',
  },

  // QUESTS
  {
    id: 'show-current-quest-targets',
    title: 'Show Current Quest Targets',
    category: 'Untested',
    description: 'List current quest targets through Starfield’s console. Testing showed that the unfiltered output is too large to use comfortably.',
    command: 'sqt',
    tags: ['quest', 'targets', 'sqt', 'inspect', 'read only'],
    closeBeforeExecute: true,
    testStatus: 'needs-adjustment',
    unavailableReason: 'The command executes, but floods Starfield’s console with an impractical amount of unfiltered output. CCC needs a filtered native replacement.',
    intakeGroup: 'Executed — Issues',
  },
  {
    id: 'get-quest-stage',
    title: 'Get Current Quest Stage',
    category: 'Quests',
    description: 'Read the current/highest completed stage and quest state directly from Starfield before attempting a repair.',
    command: 'getstage {questId}',
    inputs: [questIdInput()],
    tags: ['quest', 'stage', 'getstage', 'inspect', 'read only'],
    testStatus: 'verified',
  },
  {
    id: 'show-quest-stages',
    title: 'Show Quest Stage History',
    category: 'Quests',
    description: 'Read every packaged stage directly from Starfield and list whether it is done or not set. Results open in a scrollable window and can be reopened from Activity Log.',
    command: 'sqs {questId}',
    inputs: [questIdInput()],
    tags: ['quest', 'stages', 'sqs', 'history', 'inspect', 'read only'],
    testStatus: 'verified',
  },
  {
    id: 'start-quest',
    title: 'Start Quest by ID',
    category: 'Quests',
    description: 'Start a quest using its Quest ID.',
    command: 'startquest {questId}',
    tags: ['quest', 'start', 'repair'],
    inputs: [questIdInput()],
    warning: 'Starting a quest outside its normal prerequisites can break dialogue, scenes, or linked quest progression.',
    risk: 'danger',
    testStatus: 'needs-adjustment',
    verifyInGame: true,
  },
  {
    id: 'stop-quest',
    title: 'Stop Quest by ID',
    category: 'Quests',
    description: 'Stop a quest using its Quest ID.',
    command: 'stopquest {questId}',
    tags: ['quest', 'stop', 'repair'],
    inputs: [questIdInput()],
    warning: 'Stopping an active quest can leave scripts, scenes, NPC state, and linked quests in an inconsistent state.',
    risk: 'danger',
    testStatus: 'verified',
    verifyInGame: true,
  },
  {
    id: 'set-quest-stage',
    title: 'Set Quest Stage',
    category: 'Quests',
    description: 'Set a quest directly to a chosen stage.',
    command: 'setstage {questId} {stage}',
    tags: ['quest', 'stage', 'repair', 'setstage'],
    inputs: [
      questIdInput(),
      { key: 'stage', label: 'Stage', type: 'number', defaultValue: 100, min: 0, step: 1, hint: 'Choose a recorded stage for the selected quest or enter one manually.', questStageFor: 'questId' },
    ],
    warning: 'SetStage can bypass required triggers and permanently break quest chains. Use only when you know the exact intended stage.',
    risk: 'danger',
    testStatus: 'verified',
    verifyInGame: true,
  },
  {
    id: 'complete-quest',
    title: 'Complete Quest by ID',
    category: 'Quests',
    description: 'Mark a quest complete using its Quest ID.',
    command: 'completequest {questId}',
    tags: ['quest', 'complete', 'repair'],
    inputs: [questIdInput()],
    warning: 'This can mark a quest complete without running required scenes, rewards, scripts, or follow-up triggers.',
    risk: 'danger',
    testStatus: 'verified',
    verifyInGame: true,
  },
  {
    id: 'reset-quest',
    title: 'Reset Quest by ID',
    category: 'Quests',
    description: 'Clear a quest’s recorded stages and remove it from the quest log. This does not automatically restart the quest.',
    command: 'resetquest {questId}',
    tags: ['quest', 'reset', 'repair'],
    inputs: [questIdInput()],
    warning: 'ResetQuest can conflict with NPC, scene, and world state that the quest already changed. Use only on a backup save.',
    risk: 'danger',
    testStatus: 'verified',
    verifyInGame: true,
  },
  {
    id: 'move-to-quest-target',
    title: 'Teleport to Quest Target',
    category: 'Quests',
    description: 'Teleport the player directly to the current target of a specified quest.',
    command: 'movetoqt {questId}',
    tags: ['quest', 'teleport', 'target', 'movetoqt'],
    inputs: [questIdInput()],
    warning: 'This can place you directly into combat, hazardous terrain, interiors, or scripted areas and may trigger quest events immediately.',
    risk: 'caution',
    testStatus: 'verified',
  },

  // SHIP
  {
    id: 'get-current-ship-id',
    title: 'Get Current Ship Reference ID',
    category: 'Ship',
    description: 'Read the Reference ID of the ship the player is currently aboard. Use it with the ship commands below.',
    command: 'player.getspaceship',
    tags: ['ship', 'reference id', 'getspaceship', 'inspect', 'read only'],
    captureOutput: true,
    testStatus: 'verified',
  },
  {
    id: 'inspect-ship-actor-value',
    title: 'Inspect Ship Actor Value',
    category: 'Ship',
    description: 'Read any actor value from a ship Reference ID before changing it.',
    command: '{shipRef}.getav {actorValue}',
    inputs: [
      hexInput('shipRef', 'Ship Reference ID', 'FF000000', 'Use Get Current Ship Reference ID first.'),
      { key: 'actorValue', label: 'Actor Value', type: 'text', defaultValue: 'CarryWeight', pattern: ACTOR_VALUE_PATTERN, hint: 'Choose a common ship value or enter a name manually.', picker: SHIP_ACTOR_VALUE_PICKER },
    ],
    tags: ['ship', 'getav', 'actor value', 'inspect', 'read only'],
    captureOutput: true,
    testStatus: 'verified',
  },
  {
    id: 'set-ship-cargo-capacity',
    title: 'Set Ship Cargo Base Value',
    category: 'Ship',
    description: 'Set the ship CarryWeight base value. Cargo modules and other modifiers are added to this base.',
    command: '{shipRef}.setav CarryWeight {value}',
    inputs: [
      hexInput('shipRef', 'Ship Reference ID', 'FF000000', 'Use Get Current Ship Reference ID first.'),
      { key: 'value', label: 'Cargo Base Value', type: 'number', defaultValue: 5000, min: 0, max: 1000000000, step: 1, hint: 'Do not paste the inspected effective total when cargo-module modifiers are active.' },
    ],
    tags: ['ship', 'cargo', 'carryweight', 'setav'],
    warning: 'TESTED BEHAVIOR: GetAV reports effective cargo capacity, but SetAV changes the base. Entering the inspected total adds that base beneath cargo-module modifiers and raises the final capacity.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-ship-cargo-total',
    title: 'Set Ship Cargo Effective Total',
    category: 'Ship',
    description: 'Set the final CarryWeight total while preserving the currently detected cargo-module contribution.',
    command: 'ccc.seteffectivetotal {shipRef} CarryWeight {value}',
    inputs: [
      hexInput('shipRef', 'Ship Reference ID', 'FF000000', 'Use Get Current Ship Reference ID first.'),
      { key: 'value', label: 'Desired Effective Total', type: 'number', defaultValue: 5000, min: 0, max: 1000000000, step: 1 },
    ],
    tags: ['ship', 'cargo', 'carryweight', 'effective total'],
    warning: 'CCC calculates a new base from the ship\'s current base and effective cargo values. Review the calculation before applying it.',
    risk: 'caution',
    testStatus: 'verified',
    effectiveTotal: true,
  },
  {
    id: 'set-ship-shielded-cargo',
    title: 'Set Shielded Cargo Capacity',
    category: 'Ship',
    description: 'Set the ship CarryWeightShielded actor value used for shielded cargo capacity.',
    command: '{shipRef}.setav CarryWeightShielded {value}',
    inputs: [
      hexInput('shipRef', 'Ship Reference ID', 'FF000000', 'Use Get Current Ship Reference ID first.'),
      { key: 'value', label: 'Shielded Cargo', type: 'number', defaultValue: 1000, min: 0, max: 1000000000, step: 1 },
    ],
    tags: ['ship', 'cargo', 'shielded', 'carryweightshielded', 'setav'],
    warning: 'TESTED BEHAVIOR: GetAV reports the effective shielded cargo capacity, but SetAV changes the base. Entering the inspected total can stack beneath shielded-cargo module modifiers and raise the final capacity.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-ship-shielded-cargo-total',
    title: 'Set Shielded Cargo Effective Total',
    category: 'Ship',
    description: 'Set the final CarryWeightShielded total while preserving the currently detected module contribution.',
    command: 'ccc.seteffectivetotal {shipRef} CarryWeightShielded {value}',
    inputs: [
      hexInput('shipRef', 'Ship Reference ID', 'FF000000', 'Use Get Current Ship Reference ID first.'),
      { key: 'value', label: 'Desired Effective Total', type: 'number', defaultValue: 1000, min: 0, max: 1000000000, step: 1 },
    ],
    tags: ['ship', 'shielded cargo', 'carryweightshielded', 'effective total'],
    warning: 'CCC calculates a new base from the ship\'s current base and effective shielded-cargo values. Review the calculation before applying it.',
    risk: 'caution',
    testStatus: 'verified',
    effectiveTotal: true,
  },
  {
    id: 'set-ship-crew-capacity',
    title: 'Set Ship Crew Capacity',
    category: 'Ship',
    description: 'Set the ship SpaceshipCrewRating actor value.',
    command: '{shipRef}.setav SpaceshipCrewRating {value}',
    inputs: [
      hexInput('shipRef', 'Ship Reference ID', 'FF000000', 'Use Get Current Ship Reference ID first.'),
      { key: 'value', label: 'Crew Capacity', type: 'number', defaultValue: 8, min: 0, max: 100, step: 1 },
    ],
    tags: ['ship', 'crew', 'spaceshipcrewrating', 'setav'],
    warning: 'Ship crew capacity and player crew command slots are separate values. You may need to adjust both for additional crew to be usable.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-player-ship-command-slots',
    title: 'Set Player Ship Command Slots',
    category: 'Ship',
    description: 'Set the player SpaceshipCrewCommandSlots actor value used when assigning ship crew.',
    command: 'player.setav SpaceshipCrewCommandSlots {value}',
    inputs: [
      { key: 'value', label: 'Command Slots', type: 'number', defaultValue: 8, min: 0, max: 100, step: 1 },
    ],
    tags: ['ship', 'crew', 'command slots', 'spaceshipcrewcommandslots', 'setav'],
    warning: 'This directly changes a saved player actor value. Record the original value first if you may want to restore it.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-ship-reactor-power',
    title: 'Set Ship Reactor Power Actor Value',
    category: 'Ship',
    description: 'Set the ship SpaceshipReactorPower actor value.',
    command: '{shipRef}.setav SpaceshipReactorPower {value}',
    inputs: [
      hexInput('shipRef', 'Ship Reference ID', 'FF000000', 'Use Get Current Ship Reference ID first.'),
      { key: 'value', label: 'Reactor Power Value', type: 'number', defaultValue: 40, min: 0, max: 1000, step: 1 },
    ],
    tags: ['ship', 'reactor', 'power', 'spaceshipreactorpower', 'setav'],
    warning: 'TESTED BEHAVIOR: GetAV reports effective reactor power, while SetAV changes the base. Entering the inspected total can stack beneath reactor-module modifiers and raise the displayed final power.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-ship-reactor-power-total',
    title: 'Set Ship Reactor Effective Total',
    category: 'Ship',
    description: 'Set the final SpaceshipReactorPower total while preserving the currently detected reactor-module contribution.',
    command: 'ccc.seteffectivetotal {shipRef} SpaceshipReactorPower {value}',
    inputs: [
      hexInput('shipRef', 'Ship Reference ID', 'FF000000', 'Use Get Current Ship Reference ID first.'),
      { key: 'value', label: 'Desired Effective Total', type: 'number', defaultValue: 40, min: 0, max: 1000, step: 1 },
    ],
    tags: ['ship', 'reactor', 'power', 'effective total'],
    warning: 'CCC calculates a new base from the ship\'s current base and effective reactor values. Review the calculation before applying it.',
    risk: 'caution',
    testStatus: 'verified',
    effectiveTotal: true,
  },
  {
    id: 'set-ship-grav-fuel',
    title: 'Set Ship Grav Jump Fuel',
    category: 'Ship',
    description: 'Set the ship SpaceshipGravJumpFuel actor value.',
    command: '{shipRef}.setav SpaceshipGravJumpFuel {value}',
    inputs: [
      hexInput('shipRef', 'Ship Reference ID', 'FF000000', 'Use Get Current Ship Reference ID first.'),
      { key: 'value', label: 'Grav Fuel', type: 'number', defaultValue: 500, min: 0, max: 100000, step: 1 },
    ],
    tags: ['ship', 'grav', 'fuel', 'jump', 'spaceshipgravjumpfuel', 'setav'],
    warning: 'This directly changes a ship actor value. Record the current value first so you can restore it.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-ship-boost-fuel',
    title: 'Set Ship Boost Fuel',
    category: 'Ship',
    description: 'Set the ship SpaceshipBoostFuel actor value.',
    command: '{shipRef}.setav SpaceshipBoostFuel {value}',
    inputs: [
      hexInput('shipRef', 'Ship Reference ID', 'FF000000', 'Use Get Current Ship Reference ID first.'),
      { key: 'value', label: 'Boost Fuel', type: 'number', defaultValue: 200, min: 0, max: 100000, step: 1 },
    ],
    tags: ['ship', 'boost', 'fuel', 'spaceshipboostfuel', 'setav'],
    warning: 'Very large values can trivialize ship combat and may interact oddly with ship modules or perks. Record the original value first.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-ship-boost-recharge',
    title: 'Set Ship Boost Recharge Rate',
    category: 'Ship',
    description: 'Set the ship SpaceshipBoostRechargeRate actor value.',
    command: '{shipRef}.setav SpaceshipBoostRechargeRate {value}',
    inputs: [
      hexInput('shipRef', 'Ship Reference ID', 'FF000000', 'Use Get Current Ship Reference ID first.'),
      { key: 'value', label: 'Recharge Rate', type: 'number', defaultValue: 2, min: 0, max: 1000, step: 0.1 },
    ],
    tags: ['ship', 'boost', 'recharge', 'spaceshipboostrechargerate', 'setav'],
    warning: 'Very high recharge values can effectively remove normal boost limits. Record the original value first.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-max-owned-ships',
    title: 'Set Maximum Owned Ships',
    category: 'Ship',
    description: 'Change the Game Setting that limits how many ships the player can own.',
    command: 'setgs uSpaceshipMaximumOwnedSpaceships {value}',
    inputs: [
      { key: 'value', label: 'Maximum Ships', type: 'number', defaultValue: 20, min: 1, max: 1000, step: 1, hint: 'Vanilla: 10' },
    ],
    tags: ['ship', 'owned ships', 'limit', 'setgs', 'game setting'],
    warning: 'Game Setting changes generally reset when Starfield is restarted. Use 10 to restore the vanilla limit during the current session.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-ship-looting-distance',
    title: 'Set Ship Looting Distance',
    category: 'Ship',
    description: 'Change the distance at which space loot can be collected from the ship.',
    command: 'setgs fSpaceshipLootingDistanceDefault {value}',
    inputs: [
      { key: 'value', label: 'Looting Distance', type: 'number', defaultValue: 1500, min: 0, max: 1000000, step: 1, hint: 'Vanilla: 500' },
    ],
    tags: ['ship', 'loot', 'distance', 'setgs', 'game setting'],
    warning: 'This Game Setting normally resets when Starfield restarts. Very large distances may affect balance or interact poorly with space-looting behavior.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-ship-docking-distance',
    title: 'Set Maximum Docking Distance',
    category: 'Ship',
    description: 'Change the maximum distance from which the player ship can dock.',
    command: 'setgs fSpaceshipMaxDockingDistance {value}',
    inputs: [
      { key: 'value', label: 'Docking Distance', type: 'number', defaultValue: 1000, min: 0, max: 1000000, step: 1, hint: 'Vanilla: 500' },
    ],
    tags: ['ship', 'dock', 'distance', 'setgs', 'game setting'],
    warning: 'This Game Setting normally resets when Starfield restarts. Very large values may allow docking interactions from visually unrealistic distances.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-ship-transfer-distance',
    title: 'Set Ship Cargo Transfer Distance',
    category: 'Ship',
    description: 'Change how far from the ship the player can transfer items to and from ship cargo.',
    command: 'setgs fMaxShipTransferDistance {value}',
    inputs: [
      { key: 'value', label: 'Transfer Distance', type: 'number', defaultValue: 2500, min: 0, max: 1000000, step: 1, hint: 'Commonly reported default: 1000' },
    ],
    tags: ['ship', 'cargo', 'transfer', 'distance', 'setgs', 'game setting'],
    warning: 'This Game Setting normally resets when Starfield restarts. The reported vanilla/default distance varies by source, so inspect the current setting first if you want an exact restore value.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-ship-builder-max-height',
    title: 'Set Ship Builder Max Height',
    category: 'Ship',
    description: 'Change the fSpaceshipBuilderMaxSizeZ Game Setting used by the ship builder.',
    command: 'setgs fSpaceshipBuilderMaxSizeZ {value}',
    inputs: [
      { key: 'value', label: 'Maximum Height', type: 'number', defaultValue: 500, min: 1, max: 10000, step: 1, hint: 'Inspect the current Game Setting first if you want an exact restore value.' },
    ],
    tags: ['ship', 'builder', 'size', 'height', 'setgs', 'game setting'],
    warning: 'Extreme ship-builder dimensions can allow designs the game was not intended to support. This Game Setting may reset after restarting Starfield.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-ship-landable-max-size-x',
    title: 'Set Landable Ship Max Size X',
    category: 'Ship',
    description: 'Change the fSpaceshipLandableMaxSizeX Game Setting used for ship landing-size limits.',
    command: 'setgs fSpaceshipLandableMaxSizeX {value}',
    inputs: [
      { key: 'value', label: 'Maximum X Size', type: 'number', defaultValue: 5000, min: 1, max: 100000, step: 1, hint: 'Inspect the current Game Setting first if you want an exact restore value.' },
    ],
    tags: ['ship', 'landing', 'size', 'x', 'setgs', 'game setting'],
    warning: 'Large ship dimensions can permit designs or landing behavior the game was not intended to support. Record the original Game Setting before changing it.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-ship-landable-max-size-y',
    title: 'Set Landable Ship Max Size Y',
    category: 'Ship',
    description: 'Change the fSpaceshipLandableMaxSizeY Game Setting used for ship landing-size limits.',
    command: 'setgs fSpaceshipLandableMaxSizeY {value}',
    inputs: [
      { key: 'value', label: 'Maximum Y Size', type: 'number', defaultValue: 5000, min: 1, max: 100000, step: 1, hint: 'Inspect the current Game Setting first if you want an exact restore value.' },
    ],
    tags: ['ship', 'landing', 'size', 'y', 'setgs', 'game setting'],
    warning: 'Large ship dimensions can permit designs or landing behavior the game was not intended to support. Record the original Game Setting before changing it.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-ship-landable-max-size-z',
    title: 'Set Landable Ship Max Size Z',
    category: 'Ship',
    description: 'Change the fSpaceshipLandableMaxSizeZ Game Setting used for ship landing-size limits.',
    command: 'setgs fSpaceshipLandableMaxSizeZ {value}',
    inputs: [
      { key: 'value', label: 'Maximum Z Size', type: 'number', defaultValue: 5000, min: 1, max: 100000, step: 1, hint: 'Inspect the current Game Setting first if you want an exact restore value.' },
    ],
    tags: ['ship', 'landing', 'size', 'z', 'setgs', 'game setting'],
    warning: 'Large ship dimensions can permit designs or landing behavior the game was not intended to support. Record the original Game Setting before changing it.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-ship-landable-small-size',
    title: 'Set Landable Small Ship Size',
    category: 'Ship',
    description: 'Change the fSpaceshipLandableSmallSize Game Setting used by ship landing-size rules.',
    command: 'setgs fSpaceshipLandableSmallSize {value}',
    inputs: [
      { key: 'value', label: 'Small Ship Size', type: 'number', defaultValue: 5000, min: 1, max: 100000, step: 1, hint: 'Inspect the current Game Setting first if you want an exact restore value.' },
    ],
    tags: ['ship', 'landing', 'small ship', 'size', 'setgs', 'game setting'],
    warning: 'This changes a low-level ship landing-size Game Setting. Record the original value first and test large-ship changes on a backup save.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-ship-builder-module-limit',
    title: 'Set Ship Builder Module Limit',
    category: 'Ship',
    description: 'Change the normal ship-builder module-count limit.',
    command: 'setgs uSpaceshipBuilderMaxModules {value}',
    inputs: [
      { key: 'value', label: 'Module Limit', type: 'number', defaultValue: 230, min: 1, max: 5000, step: 1, hint: 'Vanilla: 130' },
    ],
    tags: ['ship builder', 'modules', 'limit', 'setgs', 'game setting'],
    warning: 'The ship builder also has a hard module limit. Set both limits to the same value when raising the cap. These settings normally reset on game restart; use 130 to restore vanilla.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-ship-builder-hard-limit',
    title: 'Set Ship Builder Module Hard Limit',
    category: 'Ship',
    description: 'Change the ship-builder hard module-count limit.',
    command: 'setgs uSpaceshipBuilderModuleHardLimit {value}',
    inputs: [
      { key: 'value', label: 'Hard Limit', type: 'number', defaultValue: 230, min: 1, max: 5000, step: 1, hint: 'Vanilla: 130' },
    ],
    tags: ['ship builder', 'modules', 'hard limit', 'setgs', 'game setting'],
    warning: 'Raise this together with Set Ship Builder Module Limit. Extremely large ships can hurt performance or stability. These settings normally reset on game restart; use 130 to restore vanilla.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'refuel-spaceship',
    title: 'Refuel Player Spaceship',
    category: 'Ship',
    description: 'Refuel the player spaceship when no other spaceship is targeted.',
    command: 'RefuelSpaceship',
    tags: ['ship', 'fuel', 'spaceship'],
    testStatus: 'verified',
  },
  {
    id: 'spawn-ship',
    title: 'Spawn Ship by Base ID',
    category: 'Untested',
    description: 'Spawn a ship Base ID at the player location.',
    command: 'player.placeatme {baseId}',
    tags: ['ship', 'spawn', 'placeatme', 'base id'],
    inputs: [{
      ...hexInput('baseId', 'Ship Base ID', '000F31DB', 'Choose an included ship/base-form record or enter its Base ID.'),
      browserPicker: { browser: 'id', buttonLabel: 'Browse Ships', allowedTypes: ['GBFM'] },
    }],
    warning: 'PlaceAtMe spawned the ship directly on the player with its boarding ramp buried underground.',
    risk: 'danger',
    testStatus: 'failed',
    unavailableReason: 'Disabled after in-game testing: the ship spawned on the player and partly underground, leaving its boarding ramp inaccessible.',
    intakeGroup: 'Executed — Issues',
  },
  ...UNTESTED_COMMANDS,
];

export const CATEGORY_ORDER: CommandCategory[] = [
  'Gameplay',
  'Player',
  'Inventory',
  'Skills',
  'Camera',
  'World',
  'Targets',
  'Quests',
  'Ship',
  'Untested',
];
