export type CommandCategory =
  | 'Gameplay'
  | 'Player'
  | 'Inventory'
  | 'Skills'
  | 'Camera'
  | 'World'
  | 'Targets'
  | 'Quests'
  | 'Ship';

export type CommandRisk = 'caution' | 'danger';
export type CommandTestStatus = 'verified' | 'untested';

export type CommandInput = {
  key: string;
  label: string;
  type: 'number' | 'text';
  defaultValue?: string | number;
  placeholder?: string;
  min?: number;
  max?: number;
  step?: number;
  pattern?: string;
  hint?: string;
};

export type CommandDefinition = {
  id: string;
  title: string;
  category: CommandCategory;
  description: string;
  command: string;
  inputs?: CommandInput[];
  tags?: string[];
  warning?: string;
  risk?: CommandRisk;
  testStatus?: CommandTestStatus;
};

const HEX_ID_PATTERN = '^[0-9A-Fa-f]{1,8}$';
const AXIS_PATTERN = '^[xXyYzZ]$';

const hexInput = (key: string, label: string, placeholder = '0000000F', hint = '1-8 hexadecimal characters'): CommandInput => ({
  key,
  label,
  type: 'text',
  placeholder,
  pattern: HEX_ID_PATTERN,
  hint,
});

// Command syntax is curated from current Starfield console-command references.
// Only commands marked "verified" have been personally confirmed through CCC so far.
export const COMMANDS: CommandDefinition[] = [
  // GAMEPLAY
  {
    id: 'god-mode',
    title: 'God Mode',
    category: 'Gameplay',
    description: 'Toggle invulnerability, infinite ammo, and other god-mode effects.',
    command: 'tgm',
    tags: ['cheat', 'invincible', 'ammo', 'toggle'],
    testStatus: 'verified',
  },
  {
    id: 'immortal-mode',
    title: 'Immortal Mode',
    category: 'Gameplay',
    description: 'Toggle immortal mode. You can take damage, but health will not drop to zero.',
    command: 'tim',
    tags: ['immortal', 'health', 'toggle'],
    testStatus: 'verified',
  },
  {
    id: 'toggle-collision',
    title: 'Toggle Collision',
    category: 'Gameplay',
    description: 'Toggle collision so the player can move through geometry and into the air.',
    command: 'tcl',
    tags: ['noclip', 'movement', 'toggle'],
    testStatus: 'verified',
  },
  {
    id: 'toggle-detection',
    title: 'Toggle Detection',
    category: 'Gameplay',
    description: 'Toggle whether NPCs can detect the player.',
    command: 'tdetect',
    tags: ['stealth', 'detection', 'toggle'],
    testStatus: 'verified',
  },
  {
    id: 'toggle-combat-ai',
    title: 'Toggle Combat AI',
    category: 'Gameplay',
    description: 'Toggle combat behavior for NPCs.',
    command: 'tcai',
    tags: ['ai', 'combat', 'npc', 'toggle'],
    testStatus: 'verified',
  },
  {
    id: 'toggle-ai',
    title: 'Toggle All AI',
    category: 'Gameplay',
    description: 'Toggle general NPC AI processing globally.',
    command: 'tai',
    tags: ['ai', 'npc', 'toggle'],
    warning: 'This affects NPC behavior globally. Run the command again to restore AI processing.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'kill-hostiles',
    title: 'Kill Nearby Hostiles',
    category: 'Gameplay',
    description: 'Kill hostile actors in the nearby area.',
    command: 'kah',
    tags: ['kill', 'hostile', 'combat'],
    warning: 'This can kill nearby hostile actors immediately, including enemies involved in scripted encounters.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'kill-all-nearby',
    title: 'Kill Everyone Nearby',
    category: 'Gameplay',
    description: 'Kill actors in the nearby area.',
    command: 'killall',
    tags: ['kill', 'npc', 'all'],
    warning: 'This can kill friendly, neutral, or quest-related actors in the area. Use only on a disposable save.',
    risk: 'danger',
    testStatus: 'untested',
  },
  {
    id: 'speech-success-on',
    title: 'Always Succeed Speech Challenges',
    category: 'Gameplay',
    description: 'Force speech challenges to succeed.',
    command: 'setforcespeechchallengealwayssucceed 1',
    tags: ['speech', 'persuasion', 'dialogue'],
    warning: 'This changes speech-challenge behavior until disabled.',
    risk: 'caution',
    testStatus: 'untested',
  },
  {
    id: 'speech-success-off',
    title: 'Restore Normal Speech Challenges',
    category: 'Gameplay',
    description: 'Disable forced speech-challenge success.',
    command: 'setforcespeechchallengealwayssucceed 0',
    tags: ['speech', 'persuasion', 'dialogue', 'restore'],
    testStatus: 'untested',
  },
  {
    id: 'clear-bounty',
    title: 'Clear Faction Bounty',
    category: 'Gameplay',
    description: 'Pay off the current bounty for a specified faction without going to jail or confiscating stolen goods.',
    command: 'player.paycrimegold 0 0 {factionId}',
    inputs: [hexInput('factionId', 'Faction ID', '000638E5')],
    tags: ['crime', 'bounty', 'faction', 'credits'],
    warning: 'Use the correct faction ID. This directly changes crime/bounty state for that faction.',
    risk: 'caution',
    testStatus: 'untested',
  },

  // PLAYER
  {
    id: 'add-xp',
    title: 'Add Experience',
    category: 'Player',
    description: 'Add experience points to the player. Normal level-up processing should award perk points.',
    command: 'player.modav experience {amount}',
    inputs: [
      { key: 'amount', label: 'XP Amount', type: 'number', defaultValue: 1000, min: 1, step: 1 },
    ],
    tags: ['xp', 'experience', 'level', 'perk points'],
    warning: 'Large XP amounts can cause many levels to process at once. Make a save first.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-level',
    title: 'Increase Player Level',
    category: 'Player',
    description: 'Raise the player directly to the chosen level. Starfield does not allow this command to lower your level.',
    command: 'player.setlevel {level}',
    inputs: [
      { key: 'level', label: 'New Level', type: 'number', defaultValue: 10, min: 1, step: 1, hint: 'Can only increase level; reload an earlier save to undo' },
    ],
    tags: ['level', 'progression', 'increase'],
    warning: 'This is effectively one-way on the current save: Starfield refuses requests below your current level. It also bypasses normal XP progression, so save first and reload if you need to undo it.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'modify-carry-weight',
    title: 'Adjust Carry Weight (+/-)',
    category: 'Player',
    description: 'Add to or subtract from your current maximum carry weight. Positive numbers add capacity; negative numbers remove it.',
    command: 'player.modav carryweight {amount}',
    inputs: [
      { key: 'amount', label: 'Change Amount', type: 'number', defaultValue: 100, step: 1 },
    ],
    tags: ['carry', 'weight', 'actor value', 'modav', 'add', 'subtract'],
    warning: 'This changes carry weight relative to its current value. Positive values add capacity and negative values subtract it. Extreme values may produce undesirable saved actor values.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'player-scale',
    title: 'Change Player Size',
    category: 'Player',
    description: 'Resize the player character only. This is different from Set Target / Reference Scale. 1 is the normal scale.',
    command: 'player.setscale {scale}',
    inputs: [
      { key: 'scale', label: 'Scale', type: 'number', defaultValue: 1, min: 0.1, max: 3, step: 0.05, hint: 'Default: 1' },
    ],
    tags: ['scale', 'size', 'height', 'player'],
    warning: 'Non-default player scale can affect camera position, animation alignment, collision, and interactions. Use 1 to restore normal scale.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'movement-speed',
    title: 'Set Movement Speed',
    category: 'Player',
    description: 'Set the player movement-speed multiplier. 100 is the normal baseline.',
    command: 'player.setav speedmult {value}',
    inputs: [
      { key: 'value', label: 'Speed Multiplier', type: 'number', defaultValue: 100, min: 1, max: 1000, step: 1, hint: 'Default: 100' },
    ],
    tags: ['speed', 'movement'],
    warning: 'Extreme values can make movement difficult to control. Use 100 to restore the normal baseline.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'max-health',
    title: 'Set Max Health',
    category: 'Player',
    description: 'Set the player health actor value.',
    command: 'player.setav health {value}',
    inputs: [
      { key: 'value', label: 'Health', type: 'number', defaultValue: 500, min: 1, step: 1 },
    ],
    tags: ['health', 'actor value'],
    warning: 'This directly changes a saved player actor value.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'character-creator-full',
    title: 'Open Full Character Creator (Advanced)',
    category: 'Player',
    description: 'Open the original full character creator, including background and trait options.',
    command: 'showlooksmenu player 1',
    tags: ['appearance', 'character', 'creator', 'traits', 'background'],
    warning: 'This opens the original character-creation flow. In current Starfield there is no reliable way to fully cancel back to gameplay; you may have to complete the profile/name flow to exit. It can also change appearance, background, traits, name, and pronouns. Save first. Use Open Appearance Editor for safer appearance-only changes.',
    risk: 'danger',
    testStatus: 'verified',
  },
  {
    id: 'character-creator-partial',
    title: 'Open Appearance Editor',
    category: 'Player',
    description: 'Open the partial character editor while leaving background and traits intact.',
    command: 'showlooksmenu player 2',
    tags: ['appearance', 'character', 'creator'],
    testStatus: 'verified',
  },
  {
    id: 'teleport-player-to-ref',
    title: 'Teleport Player to Reference',
    category: 'Player',
    description: 'Teleport the player to an existing NPC or object using its Reference ID.',
    command: 'player.moveto {refId}',
    inputs: [hexInput('refId', 'Reference ID', '000BDA6A')],
    tags: ['teleport', 'moveto', 'reference', 'npc'],
    warning: 'Teleporting to an arbitrary reference can place you inside geometry, in unloaded areas, or in dangerous locations.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-player-position-axis',
    title: 'Set Player Coordinate Axis',
    category: 'Player',
    description: 'Set the player to an absolute coordinate on a single X, Y, or Z axis. This is not a relative movement amount.',
    command: 'player.setpos {axis} {value}',
    inputs: [
      { key: 'axis', label: 'Axis', type: 'text', defaultValue: 'x', pattern: AXIS_PATTERN, hint: 'x, y, or z' },
      { key: 'value', label: 'Coordinate', type: 'number', placeholder: '5', step: 0.1, hint: 'Absolute coordinate; even small values can move you a long way' },
    ],
    tags: ['position', 'coordinate', 'movement', 'axis', 'spacewalk', 'setpos'],
    warning: 'This sets an absolute coordinate, not an offset. Even values around 15 can move the player a surprising distance vertically. Save first and enter the value deliberately.',
    risk: 'caution',
    testStatus: 'verified',
  },

  // INVENTORY
  {
    id: 'add-credits',
    title: 'Add Credits',
    category: 'Inventory',
    description: 'Add a chosen number of credits to the player inventory.',
    command: 'player.additem 0000000F {amount}',
    tags: ['money', 'credits', 'inventory'],
    inputs: [
      { key: 'amount', label: 'Amount', type: 'number', defaultValue: 10000, min: 1, step: 1 },
    ],
    testStatus: 'verified',
  },
  {
    id: 'add-digipicks',
    title: 'Add Digipicks',
    category: 'Inventory',
    description: 'Add a chosen number of digipicks to the player inventory.',
    command: 'player.additem 0000000A {amount}',
    tags: ['digipick', 'lockpick', 'inventory'],
    inputs: [
      { key: 'amount', label: 'Amount', type: 'number', defaultValue: 25, min: 1, step: 1 },
    ],
    testStatus: 'verified',
  },
  {
    id: 'add-med-packs',
    title: 'Add Med Packs',
    category: 'Inventory',
    description: 'Add standard Med Packs to the player inventory.',
    command: 'player.additem 0000ABF9 {amount}',
    tags: ['med pack', 'health', 'aid', 'inventory'],
    inputs: [
      { key: 'amount', label: 'Amount', type: 'number', defaultValue: 10, min: 1, step: 1 },
    ],
    testStatus: 'verified',
  },
  {
    id: 'add-ship-parts',
    title: 'Add Ship Parts',
    category: 'Inventory',
    description: 'Add Ship Parts used to repair spaceship hull damage.',
    command: 'player.additem 0003FB19 {amount}',
    tags: ['ship parts', 'ship repair', 'aid', 'inventory'],
    inputs: [
      { key: 'amount', label: 'Amount', type: 'number', defaultValue: 10, min: 1, step: 1 },
    ],
    testStatus: 'verified',
  },
  {
    id: 'add-item',
    title: 'Add Item by Form ID',
    category: 'Inventory',
    description: 'Add an arbitrary item to the player inventory using its Form ID.',
    command: 'player.additem {formId} {amount}',
    tags: ['item', 'formid', 'inventory', 'advanced'],
    inputs: [
      hexInput('formId', 'Form ID', '0000000F'),
      { key: 'amount', label: 'Amount', type: 'number', defaultValue: 1, min: 1, step: 1 },
    ],
    warning: 'Use a valid Form ID. Invalid IDs or unusual quest/scripted items may have unintended results.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'remove-item',
    title: 'Remove Item by Form ID',
    category: 'Inventory',
    description: 'Remove a chosen quantity of an item from the player inventory.',
    command: 'player.removeitem {formId} {amount}',
    tags: ['item', 'remove', 'formid', 'inventory'],
    inputs: [
      hexInput('formId', 'Form ID', '0000000F', 'Find inventory Form IDs with player.showinventory in the normal console'),
      { key: 'amount', label: 'Amount', type: 'number', defaultValue: 1, min: 1, step: 1 },
    ],
    warning: 'Removing quest items or scripted items can break quests or inventory scripts.',
    risk: 'danger',
    testStatus: 'verified',
  },
  {
    id: 'equip-item',
    title: 'Equip Item by Form ID',
    category: 'Inventory',
    description: 'Equip an item on the player. If the item is missing, the command may add it.',
    command: 'player.equipitem {formId}',
    tags: ['equip', 'item', 'weapon', 'armor'],
    inputs: [hexInput('formId', 'Form ID', '00228829', 'Find inventory Form IDs with player.showinventory in the normal console')],
    warning: 'Use an equippable item Form ID. Some unusual or scripted equipment can behave unexpectedly.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'unequip-item',
    title: 'Unequip Item by Form ID',
    category: 'Inventory',
    description: 'Unequip a specific item from the player.',
    command: 'player.unequipitem {formId}',
    tags: ['unequip', 'item', 'weapon', 'armor'],
    inputs: [hexInput('formId', 'Form ID', '00228829', 'Find inventory Form IDs with player.showinventory in the normal console')],
    testStatus: 'verified',
  },
  {
    id: 'drop-item',
    title: 'Drop Item by Form ID',
    category: 'Inventory',
    description: 'Drop a chosen quantity of an item from the player inventory into the world.',
    command: 'player.drop {formId} {amount}',
    tags: ['drop', 'item', 'inventory'],
    inputs: [
      hexInput('formId', 'Form ID', '0000000F', 'Find inventory Form IDs with player.showinventory in the normal console'),
      { key: 'amount', label: 'Amount', type: 'number', defaultValue: 1, min: 1, step: 1 },
    ],
    warning: 'Do not use this on quest items or items you cannot safely recover.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'spawn-by-base-id',
    title: 'Spawn Object / NPC by Base ID',
    category: 'Inventory',
    description: 'Create one or more new instances of an object, creature, NPC, or other Base ID at the player.',
    command: 'player.placeatme {baseId} {amount}',
    tags: ['spawn', 'placeatme', 'base id', 'npc', 'object'],
    inputs: [
      hexInput('baseId', 'Base ID', '0019121F'),
      { key: 'amount', label: 'Amount', type: 'number', defaultValue: 1, min: 1, max: 100, step: 1 },
    ],
    warning: 'This creates new instances. Spawning unique NPCs can create duplicates and spawning many objects can destabilize or crash the game.',
    risk: 'danger',
    testStatus: 'verified',
  },

  // SKILLS / POWERS / EFFECTS
  {
    id: 'add-perk',
    title: 'Add Perk / Skill by Form ID',
    category: 'Skills',
    description: 'Add a perk, skill, trait, or background by Form ID.',
    command: 'player.addperk {formId}',
    tags: ['perk', 'skill', 'trait', 'background', 'formid'],
    inputs: [hexInput('formId', 'Form ID', '002C59D9')],
    warning: 'Adding progression records without normal prerequisites may produce unusual progression states.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'remove-perk',
    title: 'Remove Perk / Skill by Form ID',
    category: 'Skills',
    description: 'Remove a perk, skill, trait, or background by Form ID.',
    command: 'player.removeperk {formId}',
    tags: ['perk', 'skill', 'trait', 'background', 'formid'],
    inputs: [hexInput('formId', 'Form ID', '002C59D9')],
    warning: 'Removing progression records can create inconsistent character progression. Make a save first.',
    risk: 'danger',
    testStatus: 'verified',
  },
  {
    id: 'all-powers',
    title: 'Grant All Powers',
    category: 'Skills',
    description: 'Grant all Starborn powers.',
    command: 'psb',
    tags: ['powers', 'starborn', 'spellbook'],
    warning: 'This grants a large set of progression content at once and can permanently alter power progression.',
    risk: 'danger',
    testStatus: 'untested',
  },
  {
    id: 'set-star-power',
    title: 'Set Star Power',
    category: 'Skills',
    description: 'Set the player Starborn power resource actor value.',
    command: 'player.setav starpower {value}',
    tags: ['starborn', 'power', 'actor value'],
    inputs: [
      { key: 'value', label: 'Star Power', type: 'number', defaultValue: 100, min: 0, step: 1 },
    ],
    warning: 'This directly changes a player actor value.',
    risk: 'caution',
    testStatus: 'untested',
  },
  {
    id: 'add-spell',
    title: 'Add Spell / Effect by Form ID',
    category: 'Skills',
    description: 'Add a spell/effect record to the player by Form ID.',
    command: 'player.addspell {formId}',
    tags: ['spell', 'effect', 'power', 'status'],
    inputs: [hexInput('formId', 'Spell / Effect ID', '0008CB48')],
    warning: 'Adding arbitrary effects can create persistent or unintended status effects. Only use IDs you understand.',
    risk: 'danger',
    testStatus: 'untested',
  },
  {
    id: 'remove-spell',
    title: 'Remove Spell / Status Effect by Form ID',
    category: 'Skills',
    description: 'Remove a spell or stuck status-effect record from the player by Form ID.',
    command: 'player.removespell {formId}',
    tags: ['spell', 'status effect', 'weather bug', 'fix'],
    inputs: [hexInput('formId', 'Spell / Effect ID', '00163FE7')],
    warning: 'Removing the wrong effect can remove legitimate powers or scripted effects. Confirm the effect ID first.',
    risk: 'caution',
    testStatus: 'untested',
  },

  // CAMERA
  {
    id: 'free-camera',
    title: 'Toggle Free Camera',
    category: 'Camera',
    description: 'Toggle free-camera mode while the world continues running.',
    command: 'tfc',
    tags: ['camera', 'photo', 'toggle'],
    testStatus: 'verified',
  },
  {
    id: 'free-camera-freeze',
    title: 'Enter Free Camera + Freeze',
    category: 'Camera',
    description: 'Enter free camera while freezing world animation. Use Toggle Free Camera to exit and resume gameplay.',
    command: 'tfc 1',
    tags: ['camera', 'photo', 'freeze', 'enter'],
    warning: 'Do not run tfc 1 a second time to exit. Use Toggle Free Camera (tfc) to return to normal camera/gameplay.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'toggle-hud',
    title: 'Toggle HUD / Interface',
    category: 'Camera',
    description: 'Toggle the game interface for clean screenshots.',
    command: 'tm',
    tags: ['hud', 'ui', 'photo', 'toggle'],
    warning: 'This hides the game UI, including the normal console display. Run the command again to restore it.',
    risk: 'caution',
    testStatus: 'untested',
  },
  {
    id: 'free-camera-speed',
    title: 'Set Free Camera Speed',
    category: 'Camera',
    description: 'Set the movement-speed multiplier for the free camera. The normal/default value is 2.',
    command: 'sucsm {speed}',
    tags: ['camera', 'photo', 'speed', 'sucsm'],
    inputs: [
      { key: 'speed', label: 'Camera Speed', type: 'number', defaultValue: 2, min: 0.1, max: 100, step: 0.1, hint: 'Default: 2' },
    ],
    testStatus: 'verified',
  },
  {
    id: 'clear-screen-blood',
    title: 'Clear Screen Blood',
    category: 'Camera',
    description: 'Clear blood/damage overlays from the screen.',
    command: 'ClearScreenBlood',
    tags: ['camera', 'photo', 'blood', 'screen'],
    testStatus: 'untested',
  },

  // WORLD
  {
    id: 'toggle-pause',
    title: 'Toggle Game Pause',
    category: 'World',
    description: 'Toggle the gameplay pause state.',
    command: 'tgp',
    tags: ['pause', 'world', 'toggle'],
    testStatus: 'untested',
  },
  {
    id: 'game-speed',
    title: 'Set Game Speed',
    category: 'World',
    description: 'Set the global gameplay speed multiplier. 1 is normal speed.',
    command: 'sgtm {value}',
    tags: ['time', 'speed', 'slow motion'],
    inputs: [
      { key: 'value', label: 'Multiplier', type: 'number', defaultValue: 1, min: 0.01, max: 10, step: 0.01, hint: 'Default: 1' },
    ],
    warning: 'Very low or high multipliers can make the game difficult to control. Use 1 to restore normal speed.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'pass-time',
    title: 'Pass Time',
    category: 'World',
    description: 'Advance the game by a chosen number of hours.',
    command: 'passtime {hours}',
    tags: ['time', 'wait', 'hours'],
    inputs: [
      { key: 'hours', label: 'Hours', type: 'number', defaultValue: 1, min: 1, max: 1000, step: 1 },
    ],
    testStatus: 'verified',
  },
  {
    id: 'show-map-markers',
    title: 'Reveal Planet Map Markers',
    category: 'World',
    description: 'Add map markers for locations on the current planet surface.',
    command: 'tmm 1',
    tags: ['map', 'markers', 'locations'],
    warning: 'Published reports indicate the added markers may persist and may not be cleanly undone with tmm 0 during the session.',
    risk: 'danger',
    testStatus: 'untested',
  },
  {
    id: 'center-on-cell',
    title: 'Teleport to Cell',
    category: 'World',
    description: 'Teleport directly to a cell using its Editor ID / cell name.',
    command: 'coc {cellName}',
    tags: ['coc', 'cell', 'teleport', 'location'],
    inputs: [
      { key: 'cellName', label: 'Cell Name / Editor ID', type: 'text', placeholder: 'CityAkilaTheRock01', pattern: '^\\S+$', hint: 'Exact cell Editor ID, usually no spaces' },
    ],
    warning: 'An invalid or unsuitable cell can place you in test areas, unloaded spaces, or locations with broken progression context.',
    risk: 'danger',
    testStatus: 'untested',
  },
  {
    id: 'force-weather',
    title: 'Force Weather',
    category: 'World',
    description: 'Immediately force a weather record by Form ID.',
    command: 'fw {weatherId}',
    tags: ['weather', 'forceweather', 'photo'],
    inputs: [hexInput('weatherId', 'Weather ID', '00000000')],
    warning: 'Use a valid weather Form ID. Forced weather can look wrong in locations it was not designed for.',
    risk: 'caution',
    testStatus: 'untested',
  },
  {
    id: 'set-weather',
    title: 'Set Weather Gradually',
    category: 'World',
    description: 'Transition toward a weather record by Form ID.',
    command: 'setweather {weatherId}',
    tags: ['weather', 'transition', 'photo'],
    inputs: [hexInput('weatherId', 'Weather ID', '00000000')],
    warning: 'Use a valid weather Form ID. Weather changes may be overridden by the current location or scripts.',
    risk: 'caution',
    testStatus: 'untested',
  },

  // TARGETS (NPCs / OBJECTS / WORLD REFERENCES)
  {
    id: 'move-ref-to-player',
    title: 'Move Reference to Player',
    category: 'Targets',
    description: 'Move an existing NPC or object to the player using its Reference ID.',
    command: '{refId}.moveto player',
    tags: ['npc', 'object', 'reference', 'moveto', 'fix'],
    inputs: [hexInput('refId', 'Reference ID', '000BDA6A')],
    warning: 'Use a Reference ID, not a Base ID. Moving quest actors can trigger or disrupt scripted scenes.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'kill-ref',
    title: 'Kill Actor by Reference ID',
    category: 'Targets',
    description: 'Kill a specific actor using its Reference ID.',
    command: '{refId}.kill',
    tags: ['npc', 'kill', 'reference'],
    inputs: [hexInput('refId', 'Reference ID', '000BDA6A')],
    warning: 'Killing quest or unique actors can break quests and scripted scenes. Essential actors may only be incapacitated.',
    risk: 'danger',
    testStatus: 'verified',
  },
  {
    id: 'resurrect-ref',
    title: 'Resurrect Actor by Reference ID',
    category: 'Targets',
    description: 'Resurrect a specific dead actor using its Reference ID.',
    command: '{refId}.resurrect',
    tags: ['npc', 'resurrect', 'reference', 'fix'],
    inputs: [hexInput('refId', 'Reference ID', '000BDA6A')],
    warning: 'Resurrecting unique or quest actors can produce duplicated state, missing scripts, or broken quest logic.',
    risk: 'danger',
    testStatus: 'verified',
  },
  {
    id: 'recycle-ref',
    title: 'Recycle Actor / Reference',
    category: 'Targets',
    description: 'Recycle/reset an existing reference using its Reference ID.',
    command: '{refId}.recycleactor',
    tags: ['npc', 'recycleactor', 'reset', 'fix'],
    inputs: [hexInput('refId', 'Reference ID', '000BDA6A')],
    warning: 'RecycleActor can reset inventory, state, placement, and script-related data. Never use it casually on important NPCs.',
    risk: 'danger',
    testStatus: 'verified',
  },
  {
    id: 'disable-ref',
    title: 'Disable Reference',
    category: 'Targets',
    description: 'Disable an existing NPC or object by Reference ID.',
    command: '{refId}.disable',
    tags: ['disable', 'npc', 'object', 'reference'],
    inputs: [hexInput('refId', 'Reference ID', '00000000')],
    warning: 'Record the Reference ID before disabling anything. Disabling quest actors or objects can block progression.',
    risk: 'danger',
    testStatus: 'verified',
  },
  {
    id: 'enable-ref',
    title: 'Enable Reference',
    category: 'Targets',
    description: 'Re-enable an existing NPC or object by Reference ID.',
    command: '{refId}.enable',
    tags: ['enable', 'npc', 'object', 'reference', 'fix'],
    inputs: [hexInput('refId', 'Reference ID', '00000000')],
    warning: 'Use the exact Reference ID for the previously disabled object or actor.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'unlock-ref',
    title: 'Unlock Door / Container by Reference ID',
    category: 'Targets',
    description: 'Unlock a specific door or container reference.',
    command: '{refId}.unlock',
    tags: ['unlock', 'door', 'container', 'reference'],
    inputs: [hexInput('refId', 'Reference ID', '00000000')],
    warning: 'Quest-locked doors and scripted locks may be intentional. Forcing them open can bypass triggers or break quest flow.',
    risk: 'danger',
    testStatus: 'verified',
  },
  {
    id: 'lock-ref',
    title: 'Lock Door / Container by Reference ID',
    category: 'Targets',
    description: 'Lock a specific door or container with a chosen lock level.',
    command: '{refId}.lock {level}',
    tags: ['lock', 'door', 'container', 'reference'],
    inputs: [
      hexInput('refId', 'Reference ID', '00000000'),
      { key: 'level', label: 'Lock Level', type: 'number', defaultValue: 50, min: 0, max: 100, step: 1 },
    ],
    warning: 'Locking quest-critical doors or containers can interfere with progression.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-ref-scale',
    title: 'Set Target / Reference Scale',
    category: 'Targets',
    description: 'Resize an NPC or world reference. 1 is normal size.',
    command: '{refId}.setscale {scale}',
    tags: ['scale', 'npc', 'object', 'reference'],
    inputs: [
      hexInput('refId', 'Reference ID', '00000000'),
      { key: 'scale', label: 'Scale', type: 'number', defaultValue: 1, min: 0.1, max: 10, step: 0.1, hint: 'Default: 1' },
    ],
    warning: 'Extreme scales can cause collision, animation, or interaction problems.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'set-ref-ownership',
    title: 'Set Reference Ownership',
    category: 'Targets',
    description: 'Make the selected reference owned by the player using its Reference ID.',
    command: '{refId}.setownership',
    tags: ['ownership', 'steal', 'object', 'reference'],
    inputs: [hexInput('refId', 'Reference ID', '00000000')],
    warning: 'Changing ownership can affect theft/crime behavior and scripted objects.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'move-ref-axis',
    title: 'Move Reference Along Axis',
    category: 'Targets',
    description: 'Move a world reference by an offset along the X, Y, or Z axis.',
    command: '{refId}.modpos {axis} {amount}',
    tags: ['object', 'position', 'modpos', 'decorating', 'reference'],
    inputs: [
      hexInput('refId', 'Reference ID', '00000000'),
      { key: 'axis', label: 'Axis', type: 'text', defaultValue: 'z', pattern: AXIS_PATTERN, hint: 'x, y, or z' },
      { key: 'amount', label: 'Offset', type: 'number', defaultValue: 0.1, step: 0.001 },
    ],
    warning: 'Moving scripted or structural references can create visual, collision, or quest problems.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'rotate-ref-axis',
    title: 'Rotate Reference Along Axis',
    category: 'Targets',
    description: 'Rotate a world reference by an offset in degrees along the X, Y, or Z axis.',
    command: '{refId}.modangle {axis} {degrees}',
    tags: ['object', 'rotation', 'modangle', 'decorating', 'reference'],
    inputs: [
      hexInput('refId', 'Reference ID', '00000000'),
      { key: 'axis', label: 'Axis', type: 'text', defaultValue: 'z', pattern: AXIS_PATTERN, hint: 'x, y, or z' },
      { key: 'degrees', label: 'Degrees', type: 'number', defaultValue: 5, step: 0.1 },
    ],
    warning: 'Rotating scripted or structural references can create visual, collision, or quest problems.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'add-item-mod',
    title: 'Attach Weapon / Armor Mod',
    category: 'Targets',
    description: 'Attach a modifier to a dropped weapon or armor reference using its Reference ID and a Mod ID.',
    command: '{refId}.amod {modId}',
    tags: ['weapon', 'armor', 'mod', 'amod', 'modifier'],
    inputs: [
      hexInput('refId', 'Item Reference ID', 'FF00BB78'),
      hexInput('modId', 'Modifier / Mod ID', '002BDD72'),
    ],
    warning: 'The modifier must be compatible with the item. Invalid combinations can create broken or unusual equipment.',
    risk: 'caution',
    testStatus: 'untested',
  },
  {
    id: 'remove-item-mod',
    title: 'Remove Weapon / Armor Mod',
    category: 'Targets',
    description: 'Remove a modifier from a dropped weapon or armor reference.',
    command: '{refId}.rmod {modId}',
    tags: ['weapon', 'armor', 'mod', 'rmod', 'modifier'],
    inputs: [
      hexInput('refId', 'Item Reference ID', 'FF00BB78'),
      hexInput('modId', 'Modifier / Mod ID', '002BDD72'),
    ],
    warning: 'Removing the wrong modifier can change item quality or remove an intended attachment.',
    risk: 'caution',
    testStatus: 'untested',
  },
  {
    id: 'set-companion-affinity',
    title: 'Set Companion Affinity',
    category: 'Targets',
    description: 'Set a companion affinity actor value using the companion Reference ID.',
    command: '{refId}.setav com_affinity {value}',
    tags: ['companion', 'affinity', 'relationship', 'npc'],
    inputs: [
      hexInput('refId', 'Companion Reference ID', '00005986'),
      { key: 'value', label: 'Affinity', type: 'number', defaultValue: 99, step: 1 },
    ],
    warning: 'Changing affinity directly can skip natural relationship progression and dialogue triggers. Values just below thresholds are generally safer than jumping far ahead.',
    risk: 'danger',
    testStatus: 'untested',
  },
  {
    id: 'set-companion-affinity-level',
    title: 'Set Companion Relationship Level',
    category: 'Targets',
    description: 'Set a companion relationship-level actor value using the companion Reference ID.',
    command: '{refId}.setav com_affinitylevel {value}',
    tags: ['companion', 'affinity', 'relationship', 'npc'],
    inputs: [
      hexInput('refId', 'Companion Reference ID', '00005986'),
      { key: 'value', label: 'Relationship Level', type: 'number', defaultValue: 1, min: 0, max: 3, step: 1, hint: '0 Neutral, 1 Friendship, 2 Affection, 3 Commitment' },
    ],
    warning: 'Direct relationship-level changes can skip dialogue and quest triggers. Use only on a backup save.',
    risk: 'danger',
    testStatus: 'untested',
  },

  // QUESTS
  {
    id: 'start-quest',
    title: 'Start Quest by ID',
    category: 'Quests',
    description: 'Start a quest using its Quest ID.',
    command: 'startquest {questId}',
    tags: ['quest', 'start', 'repair'],
    inputs: [hexInput('questId', 'Quest ID', '00003448')],
    warning: 'Starting a quest outside its normal prerequisites can break dialogue, scenes, or linked quest progression.',
    risk: 'danger',
    testStatus: 'untested',
  },
  {
    id: 'stop-quest',
    title: 'Stop Quest by ID',
    category: 'Quests',
    description: 'Stop a quest using its Quest ID.',
    command: 'stopquest {questId}',
    tags: ['quest', 'stop', 'repair'],
    inputs: [hexInput('questId', 'Quest ID', '00003448')],
    warning: 'Stopping an active quest can leave scripts, scenes, NPC state, and linked quests in an inconsistent state.',
    risk: 'danger',
    testStatus: 'untested',
  },
  {
    id: 'set-quest-stage',
    title: 'Set Quest Stage',
    category: 'Quests',
    description: 'Set a quest directly to a chosen stage.',
    command: 'setstage {questId} {stage}',
    tags: ['quest', 'stage', 'repair', 'setstage'],
    inputs: [
      hexInput('questId', 'Quest ID', '00003448'),
      { key: 'stage', label: 'Stage', type: 'number', defaultValue: 100, min: 0, step: 1 },
    ],
    warning: 'SetStage can bypass required triggers and permanently break quest chains. Use only when you know the exact intended stage.',
    risk: 'danger',
    testStatus: 'untested',
  },
  {
    id: 'complete-quest',
    title: 'Complete Quest by ID',
    category: 'Quests',
    description: 'Mark a quest complete using its Quest ID.',
    command: 'completequest {questId}',
    tags: ['quest', 'complete', 'repair'],
    inputs: [hexInput('questId', 'Quest ID', '00003448')],
    warning: 'This can mark a quest complete without running required scenes, rewards, scripts, or follow-up triggers.',
    risk: 'danger',
    testStatus: 'untested',
  },
  {
    id: 'reset-quest',
    title: 'Reset Quest by ID',
    category: 'Quests',
    description: 'Reset all stages of a quest back to their initial state.',
    command: 'resetquest {questId}',
    tags: ['quest', 'reset', 'repair'],
    inputs: [hexInput('questId', 'Quest ID', '00003448')],
    warning: 'ResetQuest can conflict with NPC, scene, and world state that the quest already changed. Use only on a backup save.',
    risk: 'danger',
    testStatus: 'untested',
  },
  {
    id: 'move-to-quest-target',
    title: 'Teleport to Quest Target',
    category: 'Quests',
    description: 'Teleport the player directly to the current target of a specified quest.',
    command: 'movetoqt {questId}',
    tags: ['quest', 'teleport', 'target', 'movetoqt'],
    inputs: [hexInput('questId', 'Quest ID', '00003448')],
    warning: 'This can place you directly into combat, hazardous terrain, interiors, or scripted areas and may trigger quest events immediately.',
    risk: 'caution',
    testStatus: 'untested',
  },

  // SHIP
  {
    id: 'refuel-spaceship',
    title: 'Refuel Player Spaceship',
    category: 'Ship',
    description: 'Refuel the player spaceship when no other spaceship is targeted.',
    command: 'RefuelSpaceship',
    tags: ['ship', 'fuel', 'spaceship'],
    testStatus: 'untested',
  },
  {
    id: 'spawn-ship',
    title: 'Spawn Ship by Base ID',
    category: 'Ship',
    description: 'Spawn a ship Base ID at the player location.',
    command: 'player.placeatme {baseId}',
    tags: ['ship', 'spawn', 'placeatme', 'base id'],
    inputs: [hexInput('baseId', 'Ship Base ID', '000F31DB')],
    warning: 'Spawning ships in unsuitable locations can cause collisions, inaccessible geometry, or save instability. Use in a large open area and on a backup save.',
    risk: 'danger',
    testStatus: 'untested',
  },
];

export const CATEGORY_ORDER: CommandCategory[] = [
  'Gameplay',
  'Player',
  'Inventory',
  'Skills',
  'Camera',
  'World',
  'Targets',
  'Quests',
  'Ship',
];
