import { BOUNTY_FACTION_PICKER, CORE_COMPANION_PICKER, WEATHER_PICKER, type ReferenceIdPicker } from './reference-ids';
import type { GeneratedIdCatalogEntry } from './id-browser-data';

export type IdCatalogAction = 'additem' | 'addperk' | 'addspell' | 'spawn';

export type IdCatalogEntry = {
  label: string;
  value: string;
  type: string;
  category: string;
  detail?: string;
  keywords?: string[];
  action?: IdCatalogAction;
  source?: 'built-in' | 'Base Game' | 'Shattered Space';
};

export type IdBrowserCategory = {
  label: string;
  value: string;
  detail: string;
  recordType: string;
  builtInCategories: string[];
};

// These groups filter the reviewed catalog packaged with CCC. Expansion-only
// records include their requirement in the visible detail text.
export const ID_BROWSER_CATEGORIES: IdBrowserCategory[] = [
  { label: 'All Categories', value: 'all', detail: 'Every ID included with CCC.', recordType: '', builtInCategories: ['*'] },
  { label: 'Common Items', value: 'common', detail: 'Credits, digipicks, and ship parts.', recordType: '', builtInCategories: ['Common'] },
  { label: 'Weapons', value: 'weapons', detail: 'Weapons and guns.', recordType: 'WEAP', builtInCategories: ['Weapons'] },
  { label: 'Armor / Apparel', value: 'armor', detail: 'Spacesuits, helmets, packs, and clothing.', recordType: 'ARMO', builtInCategories: ['Armor', 'Apparel', 'Helmets', 'Packs', 'Spacesuits'] },
  { label: 'Ammo', value: 'ammo', detail: 'Ammunition records.', recordType: 'AMMO', builtInCategories: ['Ammo'] },
  { label: 'Aid / Consumables', value: 'aid', detail: 'Medicine and consumable records.', recordType: 'ALCH', builtInCategories: ['Aid'] },
  { label: 'Resources / Miscellaneous', value: 'resources', detail: 'Resources, components, and miscellaneous items.', recordType: 'MISC', builtInCategories: ['Resources', 'Resources & Miscellaneous'] },
  { label: 'Books / Notes', value: 'books', detail: 'Books, magazines, slates, and notes.', recordType: 'BOOK', builtInCategories: ['Books & Notes'] },
  { label: 'Perks / Skills / Traits', value: 'perks', detail: 'Skills, perks, backgrounds, and traits.', recordType: 'PERK', builtInCategories: ['Perks'] },
  { label: 'Powers / Effects', value: 'powers', detail: 'Starborn powers and removable environmental effects.', recordType: 'SPEL', builtInCategories: ['Powers', 'Effects'] },
  { label: 'NPCs / Companions', value: 'npcs', detail: 'NPC base records and included companion references.', recordType: 'NPC_', builtInCategories: ['Companions', 'NPCs'] },
  { label: 'Weapon / Armor Mods', value: 'mods', detail: 'Weapon and armor modifier records.', recordType: 'OMOD', builtInCategories: ['Mods'] },
  { label: 'Factions', value: 'factions', detail: 'Faction records.', recordType: 'FACT', builtInCategories: ['Factions'] },
  { label: 'Quests', value: 'quests', detail: 'Quest records.', recordType: 'QUST', builtInCategories: [] },
  { label: 'Locations / Cells', value: 'locations', detail: 'Named location and cell records with searchable Editor IDs.', recordType: 'CELL', builtInCategories: ['Locations', 'Cells'] },
  { label: 'Ships / Base Forms', value: 'ships', detail: 'Ships and generic base-form records.', recordType: 'GBFM', builtInCategories: [] },
  { label: 'Furniture', value: 'furniture', detail: 'Furniture and animation-marker records.', recordType: 'FURN', builtInCategories: [] },
  { label: 'Weather', value: 'weather', detail: 'Weather records.', recordType: 'WTHR', builtInCategories: ['Weather'] },
];

const BASE_CATALOG: IdCatalogEntry[] = [
  // COMMON
  { label: 'Credits', value: '0000000F', type: 'MISC', category: 'Common', detail: 'Currency', keywords: ['money'], action: 'additem' },
  { label: 'Digipick', value: '0000000A', type: 'MISC', category: 'Common', detail: 'Lockpick', keywords: ['lockpick'], action: 'additem' },
  { label: 'Ship Parts', value: '0003FB19', type: 'ALCH', category: 'Common', detail: 'Ship repair item', keywords: ['repair'], action: 'additem' },

  // AID — base game
  { label: 'Med Pack', value: '0000ABF9', type: 'ALCH', category: 'Aid', detail: 'Restores health', keywords: ['medpack', 'medicine', 'healing'], action: 'additem' },
  { label: 'Addichrone', value: '0029A851', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'AddiJack', value: '001F3E85', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Alien Genetic Material', value: '000C1F57', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Amp', value: '0029A856', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Analgesic Poultice', value: '0003D8B2', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Anchored Immobilizers', value: '0003D3AD', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Antibiotic Cocktail', value: '0003D3A9', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Antibiotic Injector', value: '0003D3AF', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Antibiotic Paste', value: '0003D3AE', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Antibiotic Paste (Alternate)', value: '00299590', type: 'ALCH', category: 'Aid', detail: 'Alternate base-game record', action: 'additem' },
  { label: 'Antibiotics', value: '002F4436', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Aurora', value: '002C5884', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Bandages', value: '002F4459', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Battlestim', value: '002A5024', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'BattleUp', value: '001F3E87', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Black Hole Heart', value: '00122EA8', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Boosted Injector', value: '0003D3AC', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Boudicca', value: '0029959F', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'CQB-X', value: '0029A85E', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Dwarf Star Heart', value: '00299599', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Emergency Kit', value: '002A9DE8', type: 'ALCH', category: 'Aid', keywords: ['health', 'healing'], action: 'additem' },
  { label: 'Frostwolf', value: '002C5885', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Giant Heart', value: '0029959A', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Heal Gel', value: '0003D3AB', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Heal Paste', value: '002F445C', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Heart+', value: '0029CAD9', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Hippolyta', value: '002C5883', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Hypergiant Heart', value: '00122E9C', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Immobilizer', value: '002F445B', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Infantry Alpha', value: '0029A85C', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Infused Bandages', value: '0003D3B0', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Junk Flush', value: '00143CB1', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'O2 Shot', value: '001F3E84', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Panopticon', value: '002A5025', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Paramour', value: '002C5881', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Penicillin X', value: '0029A84F', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Pick-Me-Up', value: '00255DCB', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Recon Stim', value: '0029A855', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Red Trench', value: '002C587F', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'RedAMP', value: '001F3E86', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Repairing Immobilizer', value: '00224D61', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'S.T.E.V.E.', value: '00139E4B', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Snake Oil', value: '0029A850', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Squall', value: '002A9DE7', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Subgiant Heart', value: '00122EB1', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Synapse Alpha', value: '002C5880', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Trauma Pack', value: '0029A847', type: 'ALCH', category: 'Aid', keywords: ['health', 'healing'], action: 'additem' },
  { label: 'Unprocessed Aurora', value: '000C8721', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Whiteout', value: '00143CB2', type: 'ALCH', category: 'Aid', action: 'additem' },
  { label: 'Zipper Bandages', value: '0003D3AA', type: 'ALCH', category: 'Aid', action: 'additem' },

  // WEAPONS — a useful starter set.
  { label: 'AA-99', value: '002BF65B', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Arc Welder', value: '0026D965', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Auto-Rivet', value: '0026D964', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Barrow Knife', value: '0026F181', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Big Bang', value: '0026D963', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Beowulf', value: '0004716C', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Breach', value: '000547A3', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Bridger', value: '0026D96A', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Coachman', value: '0026D96B', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Combat Knife', value: '00035A48', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Cutter', value: '00016758', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Discarded Sidestar', value: '002F413A', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Drum Beat', value: '0018DE2C', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Ecliptic Pistol', value: '0026D96E', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Eon', value: '000476C4', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Equinox', value: '0001BC4F', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Grendel', value: '00028A02', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Hard Target', value: '000546CC', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Kodama', value: '00253A16', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Kraken', value: '0021FEB4', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Lawgiver', value: '0002D7F4', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Maelstrom', value: '002984DF', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'MagPulse', value: '00023606', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'MagShear', value: '0002EB3C', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'MagShot', value: '0002EB42', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'MagSniper', value: '0002EB45', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'MagStorm', value: '0026035E', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Microgun', value: '000546CD', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Novablast Disruptor', value: '0026D968', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Novalight', value: '0026D967', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Old Earth Assault Rifle', value: '0026ED2A', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Old Earth Hunting Rifle', value: '0021BBCD', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Old Earth Shotgun', value: '00278F74', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Orion', value: '002773C8', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Osmium Dagger', value: '0026D966', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Pacifier', value: '002953F8', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Rattler', value: '00040826', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Razorback', value: '00000FD6', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Regulator', value: '0002CB5F', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Rescue Axe', value: '0004F760', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Shotty', value: '0026D960', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Sidestar', value: '0026D95D', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Solstice', value: '0026D961', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Tombstone', value: '0002EB36', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Urban Eagle', value: '0026D96D', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: "Va'ruun Inflictor", value: '0026D8A0', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: "Va'ruun Painblade", value: '0026D8A2', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: "Va'ruun Starshard", value: '0026D8A4', type: 'WEAP', category: 'Weapons', action: 'additem' },
  { label: 'Wakizashi', value: '0026D8A1', type: 'WEAP', category: 'Weapons', action: 'additem' },

  // ARMOR / SPACESUITS — common base-game examples.
  { label: 'Bounty Hunter Spacesuit', value: '00228570', type: 'ARMO', category: 'Armor', action: 'additem' },
  { label: 'Constellation Spacesuit', value: '001E2B18', type: 'ARMO', category: 'Armor', action: 'additem' },
  { label: 'Deep Mining Spacesuit', value: '0005278E', type: 'ARMO', category: 'Armor', action: 'additem' },
  { label: 'Deep Recon Spacesuit', value: '002265AE', type: 'ARMO', category: 'Armor', action: 'additem' },
  { label: 'Deepcore Spacesuit', value: '0006AC00', type: 'ARMO', category: 'Armor', action: 'additem' },
  { label: 'Deepseeker Spacesuit', value: '0016D2C4', type: 'ARMO', category: 'Armor', action: 'additem' },
  { label: 'Deimos Spacesuit', value: '00026BF1', type: 'ARMO', category: 'Armor', action: 'additem' },
  { label: 'Ecliptic Spacesuit', value: '0022856F', type: 'ARMO', category: 'Armor', action: 'additem' },
  { label: 'Explorer Spacesuit', value: '002265AF', type: 'ARMO', category: 'Armor', action: 'additem' },
  { label: 'Mantis Spacesuit', value: '00226299', type: 'ARMO', category: 'Armor', action: 'additem' },
  { label: 'Mark I Spacesuit', value: '0001754D', type: 'ARMO', category: 'Armor', action: 'additem' },
  { label: 'Mercury Spacesuit', value: '001D0F96', type: 'ARMO', category: 'Armor', action: 'additem' },
  { label: 'Navigator Spacesuit', value: '00067C94', type: 'ARMO', category: 'Armor', action: 'additem' },
  { label: 'Old Earth Spacesuit', value: '0003084E', type: 'ARMO', category: 'Armor', action: 'additem' },
  { label: 'Pirate Assault Spacesuit', value: '00066821', type: 'ARMO', category: 'Armor', action: 'additem' },
  { label: 'Pirate Charger Spacesuit', value: '00066826', type: 'ARMO', category: 'Armor', action: 'additem' },
  { label: 'Pirate Corsair Spacesuit', value: '00066828', type: 'ARMO', category: 'Armor', action: 'additem' },
  { label: 'Pirate Sniper Spacesuit', value: '0006682A', type: 'ARMO', category: 'Armor', action: 'additem' },
  { label: 'Ranger Spacesuit', value: '00227CA0', type: 'ARMO', category: 'Armor', action: 'additem' },
  { label: 'Shocktroop Spacesuit', value: '002265AD', type: 'ARMO', category: 'Armor', action: 'additem' },

  // SKILLS — base game
  { label: 'Boxing', value: '002C59DF', type: 'PERK', category: 'Perks', detail: 'Physical skill', action: 'addperk' },
  { label: 'Fitness', value: '002CE2DD', type: 'PERK', category: 'Perks', detail: 'Physical skill', action: 'addperk' },
  { label: 'Stealth', value: '002CFCB2', type: 'PERK', category: 'Perks', detail: 'Physical skill', action: 'addperk' },
  { label: 'Weight Lifting', value: '002C59D9', type: 'PERK', category: 'Perks', detail: 'Physical skill', action: 'addperk' },
  { label: 'Wellness', value: '002CE2E1', type: 'PERK', category: 'Perks', detail: 'Physical skill', action: 'addperk' },
  { label: 'Energy Weapon Dissipation', value: '002C59E2', type: 'PERK', category: 'Perks', detail: 'Physical skill', action: 'addperk' },
  { label: 'Environmental Conditioning', value: '0028AE17', type: 'PERK', category: 'Perks', detail: 'Physical skill', action: 'addperk' },
  { label: 'Gymnastics', value: '0028AE29', type: 'PERK', category: 'Perks', detail: 'Physical skill', action: 'addperk' },
  { label: 'Nutrition', value: '002CFCAD', type: 'PERK', category: 'Perks', detail: 'Physical skill', action: 'addperk' },
  { label: 'Pain Tolerance', value: '002CFCAE', type: 'PERK', category: 'Perks', detail: 'Physical skill', action: 'addperk' },
  { label: 'Cellular Regeneration', value: '0028AE14', type: 'PERK', category: 'Perks', detail: 'Physical skill', action: 'addperk' },
  { label: 'Decontamination', value: '002CE2A0', type: 'PERK', category: 'Perks', detail: 'Physical skill', action: 'addperk' },
  { label: 'Martial Arts', value: '002C5554', type: 'PERK', category: 'Perks', detail: 'Physical skill', action: 'addperk' },
  { label: 'Concealment', value: '002C555E', type: 'PERK', category: 'Perks', detail: 'Physical skill', action: 'addperk' },
  { label: 'Neurostrikes', value: '002C53B4', type: 'PERK', category: 'Perks', detail: 'Physical skill', action: 'addperk' },
  { label: 'Rejuvenation', value: '0028AE13', type: 'PERK', category: 'Perks', detail: 'Physical skill', action: 'addperk' },

  { label: 'Commerce', value: '002C5A8E', type: 'PERK', category: 'Perks', detail: 'Social skill', action: 'addperk' },
  { label: 'Gastronomy', value: '002C5A94', type: 'PERK', category: 'Perks', detail: 'Social skill', action: 'addperk' },
  { label: 'Persuasion', value: '0022EC82', type: 'PERK', category: 'Perks', detail: 'Social skill', action: 'addperk' },
  { label: 'Scavenging', value: '0028B853', type: 'PERK', category: 'Perks', detail: 'Social skill', action: 'addperk' },
  { label: 'Theft', value: '002C555B', type: 'PERK', category: 'Perks', detail: 'Social skill', action: 'addperk' },
  { label: 'Deception', value: '002CFCAF', type: 'PERK', category: 'Perks', detail: 'Social skill', action: 'addperk' },
  { label: 'Diplomacy', value: '002C59E1', type: 'PERK', category: 'Perks', detail: 'Social skill', action: 'addperk' },
  { label: 'Intimidation', value: '002C59DE', type: 'PERK', category: 'Perks', detail: 'Social skill', action: 'addperk' },
  { label: 'Isolation', value: '002C53AE', type: 'PERK', category: 'Perks', detail: 'Social skill', action: 'addperk' },
  { label: 'Negotiation', value: '002C555F', type: 'PERK', category: 'Perks', detail: 'Social skill', action: 'addperk' },
  { label: 'Instigation', value: '002C555D', type: 'PERK', category: 'Perks', detail: 'Social skill', action: 'addperk' },
  { label: 'Leadership', value: '002C890D', type: 'PERK', category: 'Perks', detail: 'Social skill', action: 'addperk' },
  { label: 'Outpost Management', value: '0023826F', type: 'PERK', category: 'Perks', detail: 'Social skill', action: 'addperk' },
  { label: 'Manipulation', value: '002C5555', type: 'PERK', category: 'Perks', detail: 'Social skill', action: 'addperk' },
  { label: 'Ship Command', value: '002C53B3', type: 'PERK', category: 'Perks', detail: 'Social skill', action: 'addperk' },
  { label: 'Xenosociology', value: '002C53B0', type: 'PERK', category: 'Perks', detail: 'Social skill', action: 'addperk' },

  { label: 'Ballistics', value: '002CFCAB', type: 'PERK', category: 'Perks', detail: 'Combat skill', action: 'addperk' },
  { label: 'Dueling', value: '002CFCB0', type: 'PERK', category: 'Perks', detail: 'Combat skill', action: 'addperk' },
  { label: 'Lasers', value: '002C59DD', type: 'PERK', category: 'Perks', detail: 'Combat skill', action: 'addperk' },
  { label: 'Pistol Certification', value: '002080FF', type: 'PERK', category: 'Perks', detail: 'Combat skill', action: 'addperk' },
  { label: 'Shotgun Certification', value: '0027DF97', type: 'PERK', category: 'Perks', detail: 'Combat skill', action: 'addperk' },
  { label: 'Demolitions', value: '002C5556', type: 'PERK', category: 'Perks', detail: 'Combat skill', action: 'addperk' },
  { label: 'Heavy Weapons Certification', value: '00147E38', type: 'PERK', category: 'Perks', detail: 'Combat skill', action: 'addperk' },
  { label: 'Incapacitation', value: '0027DF96', type: 'PERK', category: 'Perks', detail: 'Combat skill', action: 'addperk' },
  { label: 'Particle Beams', value: '0027BAFD', type: 'PERK', category: 'Perks', detail: 'Combat skill', action: 'addperk' },
  { label: 'Rifle Certification', value: '002CE2E0', type: 'PERK', category: 'Perks', detail: 'Combat skill', action: 'addperk' },
  { label: 'Marksmanship', value: '002C890B', type: 'PERK', category: 'Perks', detail: 'Combat skill', action: 'addperk' },
  { label: 'Rapid Reloading', value: '002C555A', type: 'PERK', category: 'Perks', detail: 'Combat skill', action: 'addperk' },
  { label: 'Sniper Certification', value: '002C53B1', type: 'PERK', category: 'Perks', detail: 'Combat skill', action: 'addperk' },
  { label: 'Targeting', value: '002C59DA', type: 'PERK', category: 'Perks', detail: 'Combat skill', action: 'addperk' },
  { label: 'Armor Penetration', value: '0027DF94', type: 'PERK', category: 'Perks', detail: 'Combat skill', action: 'addperk' },
  { label: 'Crippling', value: '0027CBBA', type: 'PERK', category: 'Perks', detail: 'Combat skill', action: 'addperk' },
  { label: 'Sharpshooting', value: '002C53AF', type: 'PERK', category: 'Perks', detail: 'Combat skill', action: 'addperk' },

  { label: 'Astrodynamics', value: '002C5560', type: 'PERK', category: 'Perks', detail: 'Science skill', action: 'addperk' },
  { label: 'Geology', value: '002CE29F', type: 'PERK', category: 'Perks', detail: 'Science skill', action: 'addperk' },
  { label: 'Medicine', value: '002CE2DF', type: 'PERK', category: 'Perks', detail: 'Science skill', action: 'addperk' },
  { label: 'Research Methods', value: '002C555C', type: 'PERK', category: 'Perks', detail: 'Science skill', action: 'addperk' },
  { label: 'Surveying', value: '0027CBC1', type: 'PERK', category: 'Perks', detail: 'Science skill', action: 'addperk' },
  { label: 'Botany', value: '002C5557', type: 'PERK', category: 'Perks', detail: 'Science skill', action: 'addperk' },
  { label: 'Scanning', value: '002CFCB1', type: 'PERK', category: 'Perks', detail: 'Science skill', action: 'addperk' },
  { label: 'Spacesuit Design', value: '0027CBC3', type: 'PERK', category: 'Perks', detail: 'Science skill', action: 'addperk' },
  { label: 'Weapon Engineering', value: '002C890C', type: 'PERK', category: 'Perks', detail: 'Science skill', action: 'addperk' },
  { label: 'Zoology', value: '002C5552', type: 'PERK', category: 'Perks', detail: 'Science skill', action: 'addperk' },
  { label: 'Astrophysics', value: '0027CBBB', type: 'PERK', category: 'Perks', detail: 'Science skill', action: 'addperk' },
  { label: 'Chemistry', value: '002CE2C0', type: 'PERK', category: 'Perks', detail: 'Science skill', action: 'addperk' },
  { label: 'Outpost Engineering', value: '002C59E0', type: 'PERK', category: 'Perks', detail: 'Science skill', action: 'addperk' },
  { label: 'Aneutronic Fusion', value: '002C2C5A', type: 'PERK', category: 'Perks', detail: 'Science skill', action: 'addperk' },
  { label: 'Planetary Habitation', value: '0027CBC2', type: 'PERK', category: 'Perks', detail: 'Science skill', action: 'addperk' },
  { label: 'Special Projects', value: '0004CE2D', type: 'PERK', category: 'Perks', detail: 'Science skill', action: 'addperk' },

  { label: 'Ballistic Weapon Systems', value: '002CE2C2', type: 'PERK', category: 'Perks', detail: 'Tech skill', action: 'addperk' },
  { label: 'Boost Pack Training', value: '00146C2C', type: 'PERK', category: 'Perks', detail: 'Tech skill', action: 'addperk' },
  { label: 'Piloting', value: '002CFCAC', type: 'PERK', category: 'Perks', detail: 'Tech skill', action: 'addperk' },
  { label: 'Security', value: '002CE2E2', type: 'PERK', category: 'Perks', detail: 'Tech skill', action: 'addperk' },
  { label: 'Targeting Control Systems', value: '002C5559', type: 'PERK', category: 'Perks', detail: 'Tech skill', action: 'addperk' },
  { label: 'Energy Weapon Systems', value: '002C59DB', type: 'PERK', category: 'Perks', detail: 'Tech skill', action: 'addperk' },
  { label: 'Engine Systems', value: '002CE2DE', type: 'PERK', category: 'Perks', detail: 'Tech skill', action: 'addperk' },
  { label: 'Payloads', value: '00143B6B', type: 'PERK', category: 'Perks', detail: 'Tech skill', action: 'addperk' },
  { label: 'Shield Systems', value: '002C2C59', type: 'PERK', category: 'Perks', detail: 'Tech skill', action: 'addperk' },
  { label: 'Missile Weapon Systems', value: '002C5558', type: 'PERK', category: 'Perks', detail: 'Tech skill', action: 'addperk' },
  { label: 'Particle Beam Weapon Systems', value: '002C2C5B', type: 'PERK', category: 'Perks', detail: 'Tech skill', action: 'addperk' },
  { label: 'Robotics', value: '002C5553', type: 'PERK', category: 'Perks', detail: 'Tech skill', action: 'addperk' },
  { label: 'Starship Design', value: '002C59DC', type: 'PERK', category: 'Perks', detail: 'Tech skill', action: 'addperk' },
  { label: 'Starship Engineering', value: '002AC953', type: 'PERK', category: 'Perks', detail: 'Tech skill', action: 'addperk' },
  { label: 'Automated Weapon Systems', value: '0027B9ED', type: 'PERK', category: 'Perks', detail: 'Tech skill', action: 'addperk' },
  { label: 'Boost Assault Training', value: '0008C3EE', type: 'PERK', category: 'Perks', detail: 'Tech skill', action: 'addperk' },
  { label: 'EM Weapon Systems', value: '002C53B2', type: 'PERK', category: 'Perks', detail: 'Tech skill', action: 'addperk' },

  // TRAITS — base game
  { label: 'Alien DNA', value: '00227FDA', type: 'PERK', category: 'Perks', detail: 'Trait', keywords: ['trait'], action: 'addperk' },
  { label: 'Dream Home', value: '00227FDF', type: 'PERK', category: 'Perks', detail: 'Trait', keywords: ['trait'], action: 'addperk' },
  { label: 'Empath', value: '00227FD6', type: 'PERK', category: 'Perks', detail: 'Trait', keywords: ['trait'], action: 'addperk' },
  { label: 'Extrovert', value: '00227FD7', type: 'PERK', category: 'Perks', detail: 'Trait', keywords: ['trait'], action: 'addperk' },
  { label: 'Freestar Collective Settler', value: '00227FD5', type: 'PERK', category: 'Perks', detail: 'Trait', keywords: ['trait'], action: 'addperk' },
  { label: 'Hero Worshipped', value: '00227FD9', type: 'PERK', category: 'Perks', detail: 'Trait', keywords: ['trait'], action: 'addperk' },
  { label: 'Introvert', value: '00227FD8', type: 'PERK', category: 'Perks', detail: 'Trait', keywords: ['trait'], action: 'addperk' },
  { label: 'Kid Stuff', value: '00227FDE', type: 'PERK', category: 'Perks', detail: 'Trait', keywords: ['trait'], action: 'addperk' },
  { label: 'Neon Street Rat', value: '00227FD3', type: 'PERK', category: 'Perks', detail: 'Trait', keywords: ['trait'], action: 'addperk' },
  { label: 'Raised Enlightened', value: '00227FD2', type: 'PERK', category: 'Perks', detail: 'Trait', keywords: ['trait'], action: 'addperk' },
  { label: 'Raised Universal', value: '00227FD1', type: 'PERK', category: 'Perks', detail: 'Trait', keywords: ['trait'], action: 'addperk' },
  { label: "Serpent's Embrace", value: '00227FD0', type: 'PERK', category: 'Perks', detail: 'Trait', keywords: ['trait'], action: 'addperk' },
  { label: 'Spaced', value: '00227FE2', type: 'PERK', category: 'Perks', detail: 'Trait', keywords: ['trait'], action: 'addperk' },
  { label: 'Taskmaster', value: '00227FE0', type: 'PERK', category: 'Perks', detail: 'Trait', keywords: ['trait'], action: 'addperk' },
  { label: 'Terra Firma', value: '00227FE1', type: 'PERK', category: 'Perks', detail: 'Trait', keywords: ['trait'], action: 'addperk' },
  { label: 'United Colonies Native', value: '00227FD4', type: 'PERK', category: 'Perks', detail: 'Trait', keywords: ['trait'], action: 'addperk' },
  { label: 'Wanted', value: '00227FDD', type: 'PERK', category: 'Perks', detail: 'Trait', keywords: ['trait'], action: 'addperk' },

  // STARBORN POWERS — base game
  { label: 'Anti-Gravity Field', value: '002BACBA', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },
  { label: 'Create Vacuum', value: '002C5390', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },
  { label: "Creators' Peace", value: '002C538D', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },
  { label: 'Earthbound', value: '002BACB5', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },
  { label: 'Elemental Pull', value: '002C5391', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },
  { label: 'Alien Reanimation', value: '002C538F', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },
  { label: 'Eternal Harvest', value: '002BACB4', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },
  { label: 'Grav Dash', value: '002C538C', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },
  { label: 'Gravity Wave', value: '002BACB7', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },
  { label: 'Gravity Well', value: '002C5A62', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },
  { label: 'Inner Demon', value: '002C5399', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },
  { label: 'Life Forced', value: '002C538B', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },
  { label: 'Moon Form', value: '002C5A4E', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },
  { label: 'Parallel Self', value: '002C5A67', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },
  { label: 'Particle Beam', value: '002C5A66', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },
  { label: 'Personal Atmosphere', value: '002C5389', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },
  { label: 'Phased Time', value: '002C5A63', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },
  { label: 'Precognition', value: '002C538A', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },
  { label: 'Reactive Shield', value: '002BACB6', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },
  { label: 'Sense Star Stuff', value: '002C5A54', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },
  { label: 'Solar Flare', value: '002C5A59', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },
  { label: 'Sunless Space', value: '002C5388', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },
  { label: 'Supernova', value: '002C5387', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },
  { label: 'Void Form', value: '002C5A53', type: 'SPEL', category: 'Powers', detail: 'Starborn power', action: 'addspell' },

  // ENVIRONMENTAL EFFECTS — base game; removal choices only
  { label: 'Extreme Ambient Heat', value: '0008CB48', type: 'SPEL', category: 'Effects', detail: 'Environmental effect; remove only when stuck', keywords: ['hazard', 'heat'] },
  { label: 'Poor Air Quality', value: '00163FE7', type: 'SPEL', category: 'Effects', detail: 'Environmental effect; remove only when stuck', keywords: ['hazard', 'air'] },
  { label: 'Incoming Hazardous Weather A', value: '001639EE', type: 'SPEL', category: 'Effects', detail: 'Weather-warning variant; remove only when stuck', keywords: ['hazard', 'weather', 'warning'] },
  { label: 'Incoming Hazardous Weather B', value: '00163FE0', type: 'SPEL', category: 'Effects', detail: 'Weather-warning variant; remove only when stuck', keywords: ['hazard', 'weather', 'warning'] },
  { label: 'Incoming Hazardous Weather C', value: '00281ECF', type: 'SPEL', category: 'Effects', detail: 'Weather-warning variant; remove only when stuck', keywords: ['hazard', 'weather', 'warning'] },
  { label: 'Incoming Hazardous Weather D', value: '00281ED2', type: 'SPEL', category: 'Effects', detail: 'Weather-warning variant; remove only when stuck', keywords: ['hazard', 'weather', 'warning'] },

  // AMMO
  { label: '.27 Caliber', value: '002B559C', type: 'AMMO', category: 'Ammo', action: 'additem' },
  { label: '.43 MI Array', value: '002B559A', type: 'AMMO', category: 'Ammo', action: 'additem' },
  { label: '.43 Ultramag', value: '002B5599', type: 'AMMO', category: 'Ammo', action: 'additem' },
  { label: '.45 Caliber ACP', value: '002B5598', type: 'AMMO', category: 'Ammo', action: 'additem' },
  { label: '.50 Caliber Caseless', value: '002B5597', type: 'AMMO', category: 'Ammo', action: 'additem' },
  { label: '.50 MI Array', value: '002B5596', type: 'AMMO', category: 'Ammo', action: 'additem' },
  { label: '1.5kV LZR Cartridge', value: '002BAE3F', type: 'AMMO', category: 'Ammo', action: 'additem' },
  { label: '11mm Caseless', value: '002B5595', type: 'AMMO', category: 'Ammo', action: 'additem' },
  { label: '12.5mm ST Rivet', value: '002B5594', type: 'AMMO', category: 'Ammo', action: 'additem' },
  { label: '12G Shotgun Shell', value: '000547A1', type: 'AMMO', category: 'Ammo', action: 'additem' },
  { label: '15x25 CLL Shotgun Shell', value: '002B4AFC', type: 'AMMO', category: 'Ammo', action: 'additem' },
  { label: '3kV LZR Cartridge', value: '0000E8EC', type: 'AMMO', category: 'Ammo', action: 'additem' },
  { label: '40mm XPL', value: '002B5592', type: 'AMMO', category: 'Ammo', action: 'additem' },
  { label: '6.5mm CT', value: '002B5590', type: 'AMMO', category: 'Ammo', action: 'additem' },
  { label: '6.5mm MI Array', value: '002B558F', type: 'AMMO', category: 'Ammo', action: 'additem' },
  { label: '7.5mm Whitehot', value: '002B558E', type: 'AMMO', category: 'Ammo', action: 'additem' },
  { label: '7.62x39mm', value: '002B558D', type: 'AMMO', category: 'Ammo', action: 'additem' },
  { label: '7.77mm Caseless', value: '0004AD3E', type: 'AMMO', category: 'Ammo', action: 'additem' },
  { label: '9x39mm', value: '002B559B', type: 'AMMO', category: 'Ammo', action: 'additem' },
  { label: 'Caseless Shotgun Shell', value: '002B4AFB', type: 'AMMO', category: 'Ammo', action: 'additem' },
  { label: 'Heavy Particle Fuse', value: '002B558B', type: 'AMMO', category: 'Ammo', action: 'additem' },
  { label: 'Light Particle Fuse', value: '002B558A', type: 'AMMO', category: 'Ammo', action: 'additem' },

  // RESOURCES / COMPONENTS
  { label: 'Adaptive Frame', value: '00246B6A', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Adhesive', value: '000055B1', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Aldumite', value: '00005DEC', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Alkanes', value: '00005570', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Aluminum', value: '0000557D', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Amino Acids', value: '000055CD', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Analgesic', value: '000055A9', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Antimicrobial', value: '000055AB', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Antimony', value: '0000557B', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Argon', value: '00005588', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Aromatic', value: '000055B8', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Austenitic Manifold', value: '00246B7C', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Benzene', value: '00005585', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Beryllium', value: '000057D9', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Biosuppressant', value: '000055B2', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Caelumite', value: '000788D6', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Caesium', value: '000057DF', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Carboxylic Acids', value: '00005586', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Chasmbass Oil', value: '0013BD9C', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Chlorine', value: '0000557C', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Chlorosilanes', value: '0000557E', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Cobalt', value: '00005575', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Comm Relay', value: '00246B64', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Control Rod', value: '00246B7B', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Copper', value: '00005576', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Cosmetic', value: '000055A8', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Deformable Nozzle', value: '00246B7A', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Drilling Rig', value: '0020A02F', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Dysprosium', value: '00005569', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Electron Pump', value: '00246B63', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Europium', value: '000057E1', type: 'MISC', category: 'Resources', action: 'additem' },
  { label: 'Fiber', value: '000055AF', type: 'MISC', category: 'Resources', action: 'additem' },

  // MODIFIER IDS
  { label: 'Ablative', value: '0013369C', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Acrobat', value: '000710FD', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Advanced (Armor)', value: '0011E2B9', type: 'OMOD', category: 'Mods', detail: 'Armor quality modifier' },
  { label: 'Analyzer', value: '000690AF', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Anti-Ballistic', value: '0013369E', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Antiseptic', value: '000710FA', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Armor-Plated', value: '002EDE59', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Assisted Carry', value: '002EDE4F', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Auto Medic', value: '000C9A43', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Beast Hunter', value: '001336BD', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Calibrated (Armor)', value: '0011E2BC', type: 'OMOD', category: 'Mods', detail: 'Armor quality modifier' },
  { label: 'Chameleon', value: '001336C1', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Combat Veteran', value: '001336BE', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Disassembler', value: '001625EB', type: 'OMOD', category: 'Mods', detail: 'Weapon modifier' },
  { label: 'Extended Magazine', value: '000FFA3B', type: 'OMOD', category: 'Mods', detail: 'Weapon modifier' },
  { label: 'Fastened', value: '002EDE4E', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Galvanized', value: '000710F7', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Hacker', value: '002C43DA', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Headhunter', value: '002C43DC', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Incendiary', value: '0007D728', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Leadlined', value: '000710F5', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Liquid Cooled', value: '000710F6', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Mechanized', value: '000BE542', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Mirrored', value: '00059AE8', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'O2 Boosted', value: '000690B0', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'O2 Filter', value: '000690AE', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Rapid', value: '000FEA04', type: 'OMOD', category: 'Mods', detail: 'Weapon modifier' },
  { label: 'Refined (Armor)', value: '0011E2BA', type: 'OMOD', category: 'Mods', detail: 'Armor quality modifier' },
  { label: 'Repulsing', value: '0006029D', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Resource Hauler', value: '00060293', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Sensor Chip', value: '002C43DB', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Sentinel', value: '000BE540', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Staggering', value: '000E8D64', type: 'OMOD', category: 'Mods', detail: 'Weapon / armor modifier' },
  { label: 'Sturdy', value: '00133699', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Superior (Armor)', value: '0003AF7D', type: 'OMOD', category: 'Mods', detail: 'Armor quality modifier' },
  { label: 'Weapon Holsters', value: '00060295', type: 'OMOD', category: 'Mods', detail: 'Armor modifier' },
  { label: 'Calibrated (Weapon)', value: '0028F442', type: 'OMOD', category: 'Mods', detail: 'Weapon quality modifier' },
  { label: 'Refined (Weapon)', value: '0028F443', type: 'OMOD', category: 'Mods', detail: 'Weapon quality modifier' },
  { label: 'Advanced (Weapon)', value: '0028F444', type: 'OMOD', category: 'Mods', detail: 'Weapon quality modifier' },
];

const pickerFromCatalog = (
  title: string,
  buttonLabel: string,
  searchPlaceholder: string,
  categories: string[],
): ReferenceIdPicker => ({
  title,
  buttonLabel,
  searchPlaceholder,
  options: BASE_CATALOG
    .filter((entry) => categories.includes(entry.category))
    .map(({ label, value, detail, keywords }) => ({ label, value, detail, keywords })),
});

export const PERK_SKILL_PICKER = pickerFromCatalog(
  'Choose Perk, Skill, or Trait',
  'Choose Perk',
  'Search perk, skill, trait, or Form ID...',
  ['Perks'],
);

export const POWER_SPELL_PICKER = pickerFromCatalog(
  'Choose Starborn Power',
  'Choose Power',
  'Search power name or Form ID...',
  ['Powers'],
);

export const SPELL_EFFECT_PICKER = pickerFromCatalog(
  'Choose Power or Effect',
  'Choose Effect',
  'Search power, environmental effect, or Form ID...',
  ['Powers', 'Effects'],
);

const pickerEntries: IdCatalogEntry[] = [
  ...BOUNTY_FACTION_PICKER.options.map((option) => ({
    label: option.label,
    value: option.value,
    type: 'FACT',
    category: 'Factions',
    detail: option.detail,
    keywords: option.keywords,
  })),
  ...CORE_COMPANION_PICKER.options.map((option) => ({
    label: option.label,
    value: option.value,
    type: 'REF',
    category: 'Companions',
    detail: option.detail,
    keywords: option.keywords,
  })),
  ...WEATHER_PICKER.options.map((option) => ({
    label: option.label,
    value: option.value,
    type: 'WTHR',
    category: 'Weather',
    detail: option.detail,
    keywords: option.keywords,
  })),
];

const curatedCatalog = [...BASE_CATALOG, ...pickerEntries]
  .map((entry) => ({ ...entry, source: 'built-in' as const }));
const curatedIds = new Set(curatedCatalog.map((entry) => entry.value));

export const CURATED_ID_CATALOG: IdCatalogEntry[] = [...curatedCatalog]
  .sort((a, b) => a.label.localeCompare(b.label));

export function mergeGeneratedIdCatalog(generated: GeneratedIdCatalogEntry[]): IdCatalogEntry[] {
  return [
    ...curatedCatalog,
    ...generated
    .filter((entry) => !curatedIds.has(entry.value))
    .map((entry) => ({
      ...entry,
      detail: entry.detail ?? undefined,
      action: entry.action ?? undefined,
    })),
  ].sort((a, b) => a.label.localeCompare(b.label));
}
