// Generated from a broad real-world Starfield mod installation.
// Plugin filenames are stable lookup keys; unknown plugins keep their filename-derived fallback.
export const MOD_DISPLAY_NAMES: Readonly<Record<string, string>> = {
  "001odx_antares.esm": "Antares Renegade",
  "00vv-ss.esm": "Unfamiliar Faces Shattered Space",
  "00vv-ta.esm": "Unfamiliar Faces Terran Armada",
  "00vv-unfamiliarfaces.esm": "Unfamiliar Faces",
  "50gs.esm": "50 GS",
  "accurateads.esm": "Accurate Aiming",
  "adsammymilliwhale.esm": "Sammy And The Lab of Nightmares",
  "advancedtechnology.esm": "Advanced Technology",
  "aguaworldgrindterra.esm": "Aquafield - a GRiNDTerra Mod",
  "ahplla_autolootships.esm": "Auto Loot Ship Debris",
  "allprisonersgotoprison.esm": "All Prisoners Go To Prison",
  "allvehicleshavestorage.esm": "All Vehicles Have Storage",
  "alternate vasco.esm": "Alternate Vasco",
  "andrejawalkfixed.esm": "Fixed Walking Animation for Andreja",
  "antimaterielrifle.esm": "Old World 50 Cal Barrett M82 M95 (Standalone and Replacer)",
  "apollo11.esm": "Apollo 11 Spacesuit",
  "apotheosis.esm": "Apotheosis - Powers Overhaul",
  "arc_clutter.esm": "Clutter",
  "armor and clothing for kids.esm": "Armor and Clothing for Kids",
  "arrowhead.esm": "Arrowhead",
  "arx-15.esm": "ARX-15",
  "asc_arsenal.esm": "ASC Arsenal",
  "asc_deimos_svf_patch.esm": "ASC Deimos + SVFW Patch",
  "asc_deimos.esm": "ASC Deimos",
  "asc_taiyo.esm": "ASC Taiyo",
  "ase3.esm": "Farseer",
  "ase4.esm": "Continuum",
  "aseeverbright.esm": "Everbright",
  "aseveil.esm": "The Veil",
  "aseveil2.esm": "Beyond the Veil",
  "astrallounge_neonswildestnight.esm": "Astral Lounge - NEON'S WILDEST NIGHT",
  "astralloungeplus_females.esm": "Astral Lounge - Dancers Genders",
  "asyrxminesaslockpicks.esm": "Mines as Lockpicks",
  "atlasclothing.esm": "ATLAS Clothing - Advanced Techwear",
  "atmospherevsradiation.esm": "Atmosphere Affects Radiation",
  "atmosphericaudio.esm": "Atmospheric Audio",
  "aurie_backgrounddialogueunlocked.esm": "Background Dialogue Unlocked",
  "aurie_companionsletstalklater.esm": "Let's Talk Later",
  "aurie_livedinoutposts.esm": "Lived-In Outposts",
  "aurie_optionaltemples.esm": "Optional Temple Quests",
  "aurie_templemapmarkerfix.esm": "Temple Map Marker Fix",
  "aurie_templequestfixes.esm": "Aurie's Temple Quest Fixes (Power From Beyond)",
  "aurie_terranarmadadelayed.esm": "Terran Armada Delayed",
  "auroracargocontainers.esm": "Aurora Cargo Containers",
  "avontechshipyards.esm": "Avontech Shipyards",
  "avontechtraveller.esm": "Avontech Traveller",
  "awaitsthewell.esm": "The Well Enhanced",
  "backgrounddialogueunlocked_ss_addon.esm": "Background Dialogue Unlocked - Shattered Space Addon",
  "backgrounddialogueunlocked_terranarmada.esm": "Background Dialogue Unlocked - Terran Armada Addon",
  "base-containers.esm": "B.A.S.E. - Better container snapping",
  "basefootfootstepforclothes.esm": "Barefoot Footstep Sounds for the Nightwear and Swimsuit",
  "basefootfootstepforswimsuit.esm": "Barefoot Footstep Sounds for Swimsuit Only",
  "battenswrecks.esm": "Batten's Shipwrecks (POIs)",
  "bedlam.esm": "Bedlam - Dungeon Randomizer",
  "beefybackgrounds.esm": "Beefy Backgrounds and Traits",
  "better blocking.esm": "Better Blocking",
  "better explosives.esm": "Better Explosives - An Explosive Overhaul",
  "better locational damage.esm": "Better Locational Damage",
  "better_living_ii.esm": "Better Living - Shattered Space DLC Edition",
  "better_living.esm": "Better Living - Outpost Decor",
  "betterboardingencounters.esm": "Better Boarding Encounters (BBE)",
  "bettercamdocked.esm": "CamDockCam",
  "betterdeathphysics.esm": "Better Death Physics",
  "bettergifts.esm": "Better Companion Gifts",
  "betterneonsechq.esm": "Better Neon Security HQ",
  "betternpcs.esm": "Better NPCs",
  "bettershippartflips.esm": "Better Ship Part Flips",
  "bettersleepbettercoitus.esm": "Better Sleep - Well Rested and Lovers Embrace",
  "biggersystems.esm": "Bigger Systems - Expanded Star Maps",
  "bj_lodgegear.esm": "Livingstone Weave",
  "blep_farm_shatteredspace_patch.esm": "Farm Fresh Fabricated Produce - Shattered Space Patch",
  "blep_farm.esm": "Farm Fresh Fabricated Produce",
  "bluemoon.esm": "Bluemoon",
  "blueprintships-sfta03.esm": "Trackers Alliance Complete",
  "blueprintships-sfta06.esm": "Trackers Alliance Complete",
  "blueprintships-varuuntechnicalinstituteshiphabs.esm": "Va'ruun Technical Institute Ship Habs",
  "bmxcoolerreplacer.esm": "Drink From Sinks",
  "bmxcoolerreplacerdlcpatch.esm": "BMXCoolerReplacerDLCPatch",
  "bmxlodgepatch.esm": "GTS- BMXLodgePatch",
  "bmxoutpost.esm": "Betamax's Outpost Framework",
  "bookshelfdisplaysenhanced.esm": "Bookshelf Displays Enhanced",
  "booksofstarfield.esm": "Books of Starfield",
  "booksrevamped.esm": "Books Revamped",
  "bookthedustycydonianface.esm": "The Dusty Cydonian Face",
  "bountyboard.esm": "More Mission Boards",
  "bspf-shipcolorize-patch.esm": "Better Ship Part Flips",
  "bspf-shipcombatrevisedhabs-patch.esm": "Better Ship Part Flips",
  "bspf-shipcombatrevisedreactors-patch.esm": "Better Ship Part Flips",
  "bspf-shipcombatrevisedthrusters-patch.esm": "Better Ship Part Flips",
  "bspf-shipcombatrevisedweapons-patch.esm": "Better Ship Part Flips",
  "bspf-skkshippartsnolevelallvendors-patch.esm": "Better Ship Part Flips",
  "bspf-starfieldextendedshieldsrebalanced-patch.esm": "Better Ship Part Flips",
  "bspf-tnexpandedcargoholds-patch.esm": "Better Ship Part Flips",
  "bspf-tnseparatedcategories-patch.esm": "Better Ship Part Flips",
  "bspf-tnshipmodsallinone-patch.esm": "Better Ship Part Flips",
  "bspf-tnusefulshipstructure-patch.esm": "Better Ship Part Flips",
  "bspf-usu-patch.esm": "Better Ship Part Flips",
  "bspf-usunolevelrequirements-patch.esm": "Better Ship Part Flips",
  "bspf-usuquestrewards-patch.esm": "Better Ship Part Flips",
  "bspfcargoexpanderx10.esm": "Better Ship Part Flips",
  "bspfcargoexpanderx3.esm": "Better Ship Part Flips",
  "bspfnodecoratives.esm": "Better Ship Part Flips",
  "caracal_crater.esm": "Crater 87",
  "caracal_locationpack_blue.esm": "Lost Light",
  "cargoshipsexpanded.esm": "Cargo Ships Expanded",
  "catalyst - dynamic missions.esm": "Catalyst - Dynamic Missions Patch",
  "ccexpandedloadingscreenentries.esm": "Expanded Loading Screen Entries",
  "cfaw - magazines.esm": "Collectibles From Another World - Magazines (CFAW)",
  "change your outfit.esm": "Change Your Outfit",
  "cheapaschipsships.esm": "Cheap As Chips Ships",
  "check_mateo.esm": "Matteo Went Shopping",
  "check_subtledetails.esm": "Subtle Starport Visuals",
  "checker_lodgebuild.esm": "Lodge Unlimited",
  "checker_thesilentcovenant_p1.esm": "-- The Silent Covenant",
  "chooseanimationtype_crafting.esm": "Outpost Furniture Addon",
  "chooseanimationtype.esm": "Use NPC Animations - Eating drinking and more",
  "cigarsandcigarettes.esm": "Cigars Pipes and Cigarettes and Lolipops too",
  "clothingpack_standalone_z.esm": "ZoNE79 Clothing Pack",
  "cocsos - sale of substances.esm": "Conner's Ordinary Conversations - Sale of Substances",
  "cocsos - seek out stores.esm": "Conner's Ordinary Conversations - Seek Out Stores",
  "codoscrater.esm": "Codos Crater",
  "cometoyourbandaid.esm": "Come to your BandAid - Bandages heal you",
  "commandnpcs.esm": "Command NPCs - Order your followers and allies",
  "companionpreviews.esm": "Proper Companion Previews",
  "configurabletimescale.esm": "Configurable Timescale",
  "constellation archive 2.2.x.esm": "Amber Shade - Starborn Elite Crew Companion",
  "constellationarchives.esm": "Constellation Archives - Unique Books - Lore Friendly Collection",
  "constellationdecorations.esm": "Constellation Signage and posters",
  "cooldownuniquepatch.esm": "Cooldown patch",
  "cpsyche_forgottenfrontiers1and2_factionencounterspatch.esm": "Forgotten Frontiers 1 and 2 + F&E Patch",
  "cpsyche_packingheat.esm": "Packing Heat",
  "cpsycheskillposters.esm": "Unlockable Max Rank Skill Posters",
  "creweatsfood.esm": "Crew Eats Food",
  "cross heavy industries m3 sbc patch.esm": "Cross Heavy Industries - Ship Builder Categories Patch",
  "cross heavy industries m3.esm": "Cross Heavy Industries - Model 3 Ship Modules",
  "cruisetweaks.esm": "Fly Closer To Planets in Cruise Mode",
  "cryomancer_z.esm": "Cryomancers",
  "cydoniaalt.esm": "Cydonia Rear Entrance",
  "cydoniacheck.esm": "Echoes of Cydonia",
  "cydoniachunks.esm": "Chunks in Cydonia",
  "dangerousebbside.esm": "The Dark Side of Neon - An Ebbside Overhaul",
  "darker nights.esm": "Darker Nights",
  "darkneon.esm": "Dark NEON",
  "darkstar.esm": "DarkStar - Total Gameplay Overhaul",
  "darkstarpatch_aseveil.esm": "Darkstar + The Veil",
  "darkstarpatch_athellsgate.esm": "Darkstar + At Hell's Gate",
  "darkstarpatch_cryomancer.esm": "Darkstar + Cryomancers",
  "darkstarpatch_lambentstreetratss.esm": "Darkstar + Lambent",
  "darkstarpatch_shatteredspace.esm": "Darkstar + Shattered Space",
  "darkstarpatch_terranarmada.esm": "Darkstar + Terran Armada",
  "darkstarpatch_theheadhunter.esm": "Darkstar + The Headhunter",
  "darkstarpatch_trackersalliance_fallen_hero.esm": "Darkstar + TA Fallen Hero",
  "darkstarpatch_trackersalliance_rikuokada.esm": "Darkstar + TA Riku Okada",
  "darkstarpatch_trackersalliance_starjackerredux.esm": "Darkstar + TA StarJacker",
  "darkstarpatch_trackersalliance_the_lovers.esm": "Darkstar + TA The Lovers",
  "darkstarpatch_trackersalliance_thevulture.esm": "Darkstar + TA The Vulture",
  "darkstarpatch_trackersalliance_thewidow.esm": "Darkstar + TA The Widow",
  "darkstarpatch_vigilance.esm": "Darkstar + Vigilance",
  "daylengthmessage.esm": "See day length when landing",
  "dazraplayerhomefurnished.esm": "Dazra - Vacant House Furnished",
  "dd - enhanced blood textures - medium.esm": "Enhanced Blood Textures",
  "dead body collision.esm": "Dead Body Collision",
  "deathquotes.esm": "Death Quotes",
  "decorativeengines_enhanced.esm": "Decorative Engines Enhanced",
  "densityplus.esm": "Density Plus",
  "derretechlegacy.esm": "Derretech Legacy Redux",
  "disablestarborndeatheffect.esm": "Disable Starborn Death VFX (Player)",
  "displaystuffgc01.esm": "DisplayStuff",
  "dk - pcm starborn.esm": "Immersive Starborn Temples",
  "dk_believable_crime_report_radius.esm": "Believable Crime Report Radius",
  "dmlegendaryrecycler.esm": "Legendary Module Recycler",
  "donnacrew.esm": "Donna and Tony Crew Members",
  "droppable credits.esm": "Droppable Credits",
  "du_outlaws_01.esm": "Dark Universe - Outlaws 01",
  "du_overtime.esm": "Dark Universe - Overtime",
  "du_retrograde.esm": "Dark Universe - Retrograde",
  "du_takeover.esm": "Dark Universe - Takeover",
  "du_xfire.esm": "Dark Universe - Crossfire",
  "duo_focus.esm": "DUO - Focus",
  "dwn_anchorpointexpanded.esm": "Anchorpoint Expanded",
  "dwn_communityspaceshipexpansion.esm": "Community Spaceship Expansion",
  "dwn_communityspaceshipexpansionshipvendorframework.esm": "Community Spaceship Expansion - Buyable Ships",
  "dwn_csexascarsenalpatch.esm": "Community Spaceship Expansion + ASC Arsenal Patch",
  "dwn_decorativepack.esm": "Nem's Deco Pack",
  "dwn_dreamhomefurnished.esm": "Dream Home - Overhaul",
  "dwn_factionplayerrooms.esm": "Faction Player Rooms",
  "dwn_immersivecargoholds.esm": "Immersive Cargo Halls",
  "dwn_indoorarmillary.esm": "Indoor Armillary",
  "dwn_integratedshipoptimizationterminal.esm": "Integrated Ship Optimization Terminal",
  "dwn_interactivescriptsexample.esm": "Interactive Scripts",
  "dwn_luxhabs.esm": "Luxorious Habs",
  "dwn_newbabylonhome.esm": "New Babylon Cabin",
  "dwn_newhomsteadnovastore.esm": "Nova Galactic Store",
  "dwn_redmileblackjack.esm": "Red Mile Blackjack Table",
  "eaa_novehicleidledialog.esm": "No Vehicle Idle Dialog",
  "eaacrewwanted.esm": "Crew Wanted SSNN Message Board",
  "eags ship shop 03 stroud decatur-class frigate v1-1.esm": "Stroud-Eklund Decatur-Class Frigate - Eag's Ship Shop Standalone Ship",
  "eags ship shop 04 ng nasa prism-xxl v1-2.esm": "Nova Galactic NASA Prism-XXL - Eag's Ship Shop Standalone Ship",
  "eags ship shop 05 constellation ark class.esm": "Constellation Ark-Class Expedition Cruiser - Eag's Ship Shop Standalone Ship",
  "eags ship shop 06 ng heavy outpost platform.esm": "Nova Galactic Heavy Outpost Platform-Retrievable (HOP-R) - Eag's Ship Shop Standalone Ship",
  "eags ship shop 07 razorleaf-class.esm": "UC SysDef Razorleaf-Class Frigate - Eag's Ship Shop Standalone Ship",
  "eags ship shop 08 the scintillant.esm": "Deimos Staryards 'The Scintillant' - Eag's Ship Shop Standalone Ship",
  "eags ship shop 09 ng venerator.esm": "Nova Galactic Venerator - Eag's Ship Shop Standalone Ship",
  "eags ship shop 10 hope astral engine.esm": "HopeTech Astral Engine - Eag's Ship Shop Standalone Ship",
  "eags ship shop 11 hope model ej.esm": "HopeTech Astral Engine Model EJ - Eag's Ship Shop Standalone Ship",
  "eags ship shop 12 hope archer-class.esm": "HopeTech Archer-Class Destroyer - Eag's Ship Shop Standalone Ship",
  "eags ship shop 13 nav corps 01 atlas surveyor.esm": "UC Navigator Corps Atlas-Class Surveyor - Eag's Ship Shop Standalone Ship",
  "eags ship shop 13 nav corps 02 corbita freighter.esm": "UC Navigator Corps Corbita-Class Freighter - Eag's Ship Shop Standalone Ship",
  "eags ship shop 13 nav corps 03 acropolis cruiser.esm": "UC Navigator Corps Acropolis-Class Operations Cruiser - Eag's Ship Shop Standalone Ship",
  "eags_shipshop_01_libertycruiser_01.esm": "Liberty Cruiser Ship - Eag's Ship Shop Standalone Ship",
  "eags_shipshop_02_prismlte_01.esm": "Nova Galactic NASA Prism-LTE - Eag's Ship Shop Standalone Ship",
  "ehl_apollosuitquest.esm": "for Apollo 11 Spacesuit",
  "eit_clothiers_z.esm": "Eit Clothiers Plus",
  "el jefe combat ai extreme patch.esm": "El Jefe Combat AI",
  "el jefe combat ai ss.esm": "El Jefe Combat AI",
  "el jefe combat ai ta.esm": "El Jefe Combat AI",
  "el jefe combat ai.esm": "El Jefe Combat AI",
  "el jefe combat weapons.esm": "El Jefe Space Combat AI",
  "el jefe space combat ai.esm": "El Jefe Space Combat AI",
  "el_jefe_combat_ai_stealthpatch.esm": "El Jefe Combat AI",
  "el-outposthabs.esm": "EL-OutpostHabs",
  "elysianmods-uc-gear-for-sale.esm": "UC Gear for Sale",
  "encounters_boarding_myship.esm": "Enemies Boarding My Ship",
  "enhancecompanions.esm": "Enhance Companions",
  "enhancedsona.esm": "Enhanced Sona",
  "enhancedsurrender.esm": "Enhanced Surrender",
  "erishair.esm": "Eris Hairstyles - New hair with physics",
  "errata.esm": "Cyberpunk Errata Standalone",
  "evies ship shop 16 uc war chest 01 requital.esm": "UC Requital Class Corvette - UC War Chest Series - Evie's Ship Shop Standalone Ship",
  "evies ship shop 17 uc war chest 02 arbitrator.esm": "UC Arbitrator Class Heavy Escort Cruiser - UC War Chest Series - Evie's Ship Shop Standalone Ship",
  "evies ship shop 18 uc war chest 03 bastion.esm": "UC Bastion-Class Battlecruiser - UC War Chest Series - Evie's Ship Shop Standalone Ship",
  "evies ship shop 19 uc war chest full package.esm": "Ship Bundle - UC War Chest Series - Evie's Ship Shop",
  "evies_shipshop_01a_libertycruiser_terran.esm": "Liberty Cruiser Redux - TERRAN ARMADA Edition - Evie's Ship Shop Standalone Ship",
  "expensive enhance price.esm": "Enhance Removes Bounties",
  "eyewitnessstartupfix.esm": "Eyewitness Startup Fix",
  "ezmods_fafnir_solarsystem.esm": "Fafnir SolarSystem",
  "faction expansion project.esm": "Factions and Encounters Expanded",
  "factionsgiveskillpoints.esm": "Faction Quests Give Skill Points",
  "faded_memories_music.esm": "Faded Memories - A Combat and Exploration Music Replacer",
  "falklandsystems_immersivelandingrampspatch.esm": "Falkland Systems + ILR Patch",
  "falklandsystems_usefulbrigspatch.esm": "Falkland Systems + UB Patch",
  "falklandsystems.esm": "Falkland Systems Ship Services",
  "fh_sailstars.esm": "Sail the Stars",
  "fieldos_atmocore.esm": "Native Light - Colour-Accurate LUT Overhaul",
  "fieldos_deadmansslate.esm": "Dead Man's Slate - DMS",
  "fieldos_eyecolours.esm": "Living Eyes",
  "fieldos_naturalhair.esm": "Natural Hair Colours",
  "fixgraydockingcolors.esm": "DragonFixes - Docking Animation Color Correction",
  "flashy_stl.esm": "Flashy(JoeR) - Sometimes They Leave",
  "flytothestars.esm": "Fly to the Stars",
  "forgottenfrontierspoi.esm": "Forgotten Frontiers - POI Expansion",
  "forgottenfrontierspoi2.esm": "Forgotten Frontiers 2 - POI Expansion",
  "formless-galaxyofdiamonds.esm": "Formless - Galaxy of Diamonds",
  "formlessgameplaysettings.esm": "Formless Gameplay Settings Expanded",
  "formlessshipyards.esm": "Formless Shipyards",
  "formlessskilltreeredesigned.esm": "Formless Skill Tree Redesigned",
  "frieren.esm": "New Skill Magazines - Frieren. Beyond Journeys End",
  "ftsettingspatch.esm": "Fast Travel Settings",
  "functionaldecor.esm": "Betamax's Functional Decor",
  "functionalreflexsights_shatteredspace.esm": "Functional Reflex Sights - Shattered Space",
  "functionalreflexsights_terranarmada.esm": "Functional Reflex Sights - Terran Armada",
  "functionalreflexsights.esm": "Functional Reflex Sights",
  "furnishedstarbornship.esm": "Furnished Starborn Ship",
  "g231_crowdgunfearredonenocompanioncrewff.esm": "CGFNCCFFCITYA",
  "gagarinnewdawn.esm": "Gagarin - New Dawn",
  "gaiaisgreat.esm": "Gaia is Great",
  "galaxy in flux.esm": "Galaxy in Flux",
  "gallion.esm": "Gallion - Immersive Finance",
  "gallionhackableatms.esm": "Gallion Addon - Hackable GalBank Mobiles",
  "gb_sbcx_dstgo.esm": "DarkStar + SBC Patch",
  "gb_sbcx_falkland.esm": "Falkland Systems + SBC Patch",
  "gb_sbcx_wt.esm": "Watchtower + SBC Patch",
  "gb_shipbuilderconfigurator_free.esm": "Builder Configurator",
  "gl_generatelitter.esm": "Generate Litter",
  "goloaerobicsskill.esm": "Aerobics - A New Physical Skill",
  "golobeginnersluckskill.esm": "Beginner's Luck - A New Social Skill",
  "golobloodrushskill.esm": "Bloodrush - A Doom Inspired New Physical Skill",
  "golocoffeefiendskill.esm": "Coffee Fiend - A New Social Skill",
  "golomadscientistskill.esm": "Mad Scientist - A New Science Skill",
  "golosentinelskill.esm": "Sentinel - A New Physical Skill",
  "grafscockpits.esm": "Graf's Cockpits and Bridges",
  "grafscorelliancastoffs.esm": "Graf's Corellian Castoffs - YT1300-Series Ships for Sale",
  "grafshabs-nova1x1.esm": "Graf's Habs - Nova Galactic 1x1s",
  "grindterrapet.esm": "Pets - a GRiNDTerra Outpost Expansion",
  "grindterrappgfauna.esm": "Dummys - Load Archive",
  "grindterravbo.esm": "Vanilla Biomes Enhanced- A GRiNDTerra Mod",
  "gts - all plant data - at hell's gate.esm": "All Plant Data creation patches",
  "gts - all plant data - crater 87.esm": "All Plant Data creation patches",
  "gts - all plant data - cryomancers.esm": "All Plant Data creation patches",
  "gts - all plant data - everbright.esm": "All Plant Data creation patches",
  "gts - all plant data - mcclarence.esm": "All Plant Data creation patches",
  "gts - all plant data - terminus.esm": "All Plant Data creation patches",
  "gts - all plant data - tracker's alliance.esm": "All Plant Data creation patches",
  "gts - all plant data - vigilance.esm": "All Plant Data creation patches",
  "gts - all plant data - watchtower.esm": "All Plant Data creation patches",
  "gts - all plant data.esm": "- All Plant Data - Main",
  "gts economy patch.esm": "Economy Patch by Sonic",
  "gts patch - immersive star colour.esm": "Patch by AwakenOdyssey",
  "gts patch - planet data.esm": "Dummys - Load Archive",
  "gts temple patch.esm": "GTS Temple Patch",
  "gts_spe_vh_patch_patch.esm": "GTS_SPE_VH_PATCH_PATCH",
  "gtsinkpatch.esm": "GTSinkPatch",
  "gtsmessagewarnings.esm": "Message",
  "gtsultimatepatch.esm": "Ultimate Patch",
  "h0lzpoiexpansion.esm": "- Abandoned UC Radar Station",
  "hairoverhaul.esm": "Hair Overhaul - Hair Retexture",
  "hairoverhaulnewcolors.esm": "Hair Overhaul - New Colors",
  "hal_better_actor_fire.esm": "Better Actor Get Burned Fire Effect",
  "hal_better_lilypad.esm": "Better LilyPads",
  "hal_better_metal_impact_effects.esm": "HPE Better Metal Impact Effects",
  "hatch-22 sfbgs050 patch.esm": "Hatch 22 SFBGS050 Patch",
  "hatch-22.esm": "Hatch-22 - Simple Ship Doors",
  "hbi_breakable_beer_crate.esm": "HBI Breakable Beer Crate",
  "hbi_breakable_foamcontainer.esm": "HBI Breakable Foam Container",
  "hbi_breakable_mug.esm": "HBI Breakable Mug",
  "hbi_breakable_other_cups.esm": "HBI Breakable Other Cups",
  "hbi_breakable_vase.esm": "HBI Breakable Vase",
  "hbi_breakable_wine_glass_bottle.esm": "HBI Breakable Wine Glass Bottle",
  "heartofcydonia.esm": "Heart of Cydonia",
  "hella took a shower.esm": "Heller Had A Shower CLEAN Version",
  "hjalmereaquariums.esm": "Hjalmere's Aquariums",
  "ho_crewslots.esm": "More Crew Slots",
  "hsiba.esm": "Dummys - Load Archive",
  "hstfixandreja.esm": "Divided Loyalties - Fix for quest starts then stops",
  "idg_elegant_clothing.esm": "ELEGANT - Clothing and Accessories",
  "idg_elegant_haircollection.esm": "ELEGANT - Hair Collection",
  "immersive contraband - varuun heretic writings and contraband patch.esm": "Patch by AwakenOdyssey",
  "immersive enemy names - shattered space.esm": "Immersive Enemy Names Shattered Space",
  "immersive enemy names.esm": "Immersive Enemy Names",
  "immersive play showers mod - peak performance compatch updated.esm": "Immersive Play Usable Showers - Peak Performance Compatch",
  "immersive play showers mod.esm": "Immersive Play - Usable Showers",
  "immersivecontraband.esm": "ISC - Immersive Starfield Contraband",
  "immersivesabers.esm": "Immersive Sabers",
  "immersivestarcolours.esm": "Immersive Star Colours",
  "improvedfollowerbehavior.esm": "Improved Follower Behavior",
  "improvedshippathing.esm": "Improved Ship Pathing",
  "imsbr_freelanespatch.esm": "Xeno's Immersive Sabers and Darksaber Free Lanes Patches",
  "infiltrator2_z.esm": "Infiltrator 2 - Spacesuit Outfit and Weapon",
  "infirmary.esm": "Functional Ship Infirmaries",
  "inquisitor_defensedepot_perk.esm": "Defense Depot - NEW Expert Social Perk",
  "inquisitor_immersive_love_perk.esm": "Immersive Love Perk",
  "inquisitor_new_deimos_glowing_wings.esm": "Glowing Ship Modules - Project by Inquisitor",
  "inquisitor_parkour_perk.esm": "Parkour - NEW Physical Perk",
  "inquisitor_startrekshipmodules.esm": "Star Trek Ship Modules",
  "inquisitor_watchofthestars_mod.esm": "Watch of the Stars",
  "int_glassless_cockpits.esm": "Institute of Naval Technology Glassless Cockpits",
  "int_pirate_set.esm": "Crimson Fleet Rearmed",
  "intrinityaeroworks.esm": "Intrinity Aeroworks",
  "iwmerc2.esm": "IW - Mercenary pt. 2",
  "jemisonclearwater.esm": "Jemison is not a Swamp",
  "job gone wrong expanded.esm": "Job Gone Wrong Expanded",
  "justcreaturesgterra.esm": "Random Creature and Robot Sizes- A GRiNDTerra Mod",
  "keepgenericcrewmembersaround.esm": "Keep Generic Crew Members Around",
  "keepyourtrash.esm": "Keep Your Trash",
  "kgcdoom.esm": "At Hell's Gate",
  "kha_aliensdonotreflectmeleedammage.esm": "Aliens don't reflect damage",
  "kilroy.esm": "Kilroy - Multi-Modal Companion",
  "kine_clothing_first_x2357_tntextilespatch.esm": "kine's The First Skin Pack",
  "kine_clothing_flightsuit_tntextilepatch.esm": "kine's Flightsuit Skin Pack",
  "kine_clothing_flightsuit.esm": "kine's Flightsuit Skin Pack",
  "kine_clothing_paradiso_tntextilespatch.esm": "kine's Paradiso Skin Pack + textile patch",
  "kine_clothing_paradiso.esm": "kine's Paradiso Skin Pack",
  "kine_clothing_vaultsuit.esm": "kine's Old Earth Jumpsuit (Vault Suit)",
  "kine_spacesuit_apollo.esm": "kine's Apollo Skin Pack",
  "kine_spacesuit_armada.esm": "kine's Armada Skin Pack",
  "kine_spacesuit_assassin.esm": "kine's Assassin Skin Pack",
  "kine_spacesuit_assault.esm": "kine's Shocktroop Skin Pack",
  "kine_spacesuit_bountyhunter01.esm": "kine's Bounty Hunter Skin Pack",
  "kine_spacesuit_bountyhunter02.esm": "kine's Trackers Alliance Skin Pack",
  "kine_spacesuit_diver.esm": "kine's Deepseeker Skin Pack",
  "kine_spacesuit_ecliptic.esm": "kine's Ecliptic Skin Pack",
  "kine_spacesuit_explorer.esm": "kine's Explorer Skin Pack",
  "kine_spacesuit_groundcrew.esm": "kine's Ground Crew Skin Pack",
  "kine_spacesuit_hyperpadded.esm": "kine's Hyperpadded Skin Pack",
  "kine_spacesuit_mantis.esm": "kine's Mantis Skin Pack",
  "kine_spacesuit_marine.esm": "kine's Marine Skin Pack",
  "kine_spacesuit_mercenary.esm": "kine's Mercenary Skin Pack",
  "kine_spacesuit_mercury.esm": "kine's Mercury Skin Pack",
  "kine_spacesuit_miner.esm": "kine's Deep Mining Skin Pack",
  "kine_spacesuit_navigator.esm": "kine's Navigator Skin Pack",
  "kine_spacesuit_pilot.esm": "kine's Pilot Skin Pack",
  "kine_spacesuit_pirate.esm": "kine's Pirate Skin Pack",
  "kine_spacesuit_powerassistarmor.esm": "kine's Power Assist Skin Pack",
  "kine_spacesuit_ranger.esm": "kine's Ranger Skin Pack",
  "kine_spacesuit_recon.esm": "kine's Deep Recon Skin Pack",
  "kine_spacesuit_ryujinstealth.esm": "kine's Ryujin Stealth Skin Pack",
  "kine_spacesuit_scav.esm": "kine's Scavenger Skin Pack - v1.000",
  "kine_spacesuit_spacetrucker.esm": "kine's Star Roamer Skin Pack",
  "kine_spacesuit_starborn.esm": "kine's Starborn Skin Pack",
  "kine_spacesuit_terranrobot.esm": "kine's Terran Robot Frames (Delta Skin Pack)",
  "kine_spacesuit_uctactical.esm": "kine's Armada Skin Pack Repository",
  "kine_spacesuit_varuun.esm": "kine's Va'ruun Skin Pack",
  "kinggathcreations_legendary.esm": "McClarence Outfitters",
  "kinggathcreations_spaceship.esm": "Watchtower",
  "knockdownanimfix.esm": "Knockdown Animation Fix",
  "kriswewereoncehere.esm": "We Were Once Here",
  "kwnewbooks.esm": "More Books II",
  "kz_aos.esm": "KZ Aggregation of Scraps",
  "kz_bountyh_replacer.esm": "KZ Aggregation of Scraps",
  "kz_ecliptic_replacer.esm": "KZ Aggregation of Scraps",
  "kz_mantis.esm": "KZ Mantis 2.0",
  "kz_merc_replacer.esm": "KZ Aggregation of Scraps",
  "kz_mtr.esm": "KZ Meridian Transit Regalia",
  "kz_tca.esm": "KZ Tachyonic Core Arsenal",
  "kz_tcr.esm": "KZ Techno-Corporate Repository",
  "kz_tracker_replacer.esm": "KZ Aggregation of Scraps",
  "kz_ucd.esm": "KZ United Colonies Depository",
  "kz_vfa.esm": "KZ Venatorial Frontiers Armory",
  "lambent_ub_missopatch.esm": "Lambent + Useful Brigs",
  "landscape.esm": "Dummys - Load Archive",
  "lasersightdots_enabled.esm": "Laser Sight Dot Enabled",
  "lbn_lockonrange.esm": "(Missile) Lock On Range Extended",
  "leyr_shatteredspaceheadparts.esm": "Shattered Space Headparts",
  "light in the dark akila city.esm": "Light in the Dark - Akila City",
  "livingstarfield.esm": "Living Starfield",
  "lodecs_weap_customarmory_patch_bulletfollowsdot_lm.esm": "Lodecs Custom Armory (LCA)",
  "lodecs_weap_customarmory.esm": "Lodecs Custom Armory (LCA)",
  "lodge environmental damage restoration.esm": "Lodge Environmental Damage Restoration",
  "longrattler.esm": "Squid's Rattler Replacer",
  "loud last nova.esm": "Louder Last Nova",
  "lunalk9.esm": "LK-9 Luna - Spacefarer's Best Friend",
  "luxor's makeup and appearance hd.esm": "Luxor's Makeup and Appearance HD",
  "lvx_cydonia_mining_argos_extractors.esm": "Real Jobs - Cydonia Mining Company",
  "lvx_dynamicprison.esm": "Dynamic Prison - Jail System",
  "lvx_real_jobs_terrabrew.esm": "Real Jobs - TerraBrew",
  "lvxfleetcargo.esm": "Combined Fleet Cargo",
  "lvxvladbuysdata.esm": "Vladimir Buys Data NG Plus",
  "lx6r007_booksarebooks.esm": "Books Are Books",
  "m67.esm": "M67 Hand Grenade",
  "m9bayonet.esm": "M9 Bayonet",
  "magnusthemagnateoutpostproductionshenanigans.esm": "MagnusTheMagnateOutpostProductionShenanigans",
  "mantisdialoguepatchkz_v3_1.esm": "Mantis Dialogue Patch KZ",
  "mantisdialoguepatchvanilla_v3.esm": "Spacers and Pirates recognize the Mantis on foot",
  "markedforlandmark.esm": "Marked for Landmark",
  "massacre at kreet.esm": "Massacre at Kreet",
  "materialpatch.esm": "Material Patch",
  "matilijasaerospace.esm": "Matilija's Aerospace",
  "mattell's project fenrir ta patch.esm": "Mattell's Project Fenrir",
  "mattell's project fenrir.esm": "Mattell's Project Fenrir",
  "mattells cockpits crew series ub patch.esm": "Mattell's Cockpits and Bridges Crew Series",
  "mattells cockpits crew series.esm": "Mattell's Cockpits and Bridges Crew Series",
  "mattells cockpits solitude series.esm": "Mattell's Cockpits Solitude Series",
  "mercheavy.esm": "IW - Mercenary",
  "mercurypenthouseautoclosedoors.esm": "Mercury Penthouse Auto-Close Entrance and Terrace Doors",
  "millsgarage.esm": "Outpost Garage and Invisible Landing Pad",
  "miss_o_intwalls_03a.esm": "Better Buildable Walls and Doors",
  "missolambenteb01.esm": "Lambent Street Rat Ship Services",
  "moderncolors.esm": "Modern Colors",
  "moon jumper.esm": "Moon Jumper vehicle - Red Mile Spawn",
  "moonjumperplus.esm": "Moon Jumper Plus",
  "more in depth junk system.esm": "More In Depth Junk System",
  "moredramaticgravjumps.esm": "More Dramatic Grav Jumps",
  "moreenemies.esm": "Doubled Enemy Numbers 1.5x",
  "moreinterestingcrewrecruits.esm": "More interesting Crew Recruits",
  "morelore_kreetlab.esm": "More Lore - Kreet Research Lab",
  "morelore_mantislegacy.esm": "More Lore - Legacy of the Mantis",
  "morelore_novagalacticstaryard.esm": "More Lore - Nova Galactic Staryard",
  "moreoutpostcrew.esm": "More Outpost Crew",
  "moreshipservicestechnicians.esm": "More Ship Services Technicians",
  "morevisualizeddocking.esm": "More Visualized Docking",
  "mortal killable children.esm": "Mortal Killable Children",
  "mostlymenenemies.esm": "Mostly Men Enemies",
  "mtm-ssnoredfogmwps.esm": "Shattered Space No Red Fog",
  "munitionsexpansionframework.esm": "Munitions Expansion Framework",
  "muriamended.esm": "Muria Mended",
  "naafalklandpatch.esm": "Falkland Systems + NAA Patch",
  "nasadecrepitpa.esm": "NASA DECREPIT PA",
  "nccchunksnoire.esm": "Chunks Noir",
  "ne_zch_patch.esm": "NeonExpansion + Zone's City Homes Patch",
  "neon_entertainers_z.esm": "Neon Entertainer's Outfit",
  "neon_vertigo.esm": "Neon Vertigo - A Neon Overhaul",
  "neoncheck.esm": "Echoes of Neon (EON)",
  "neoncoreseriousbusiness_neonvertigopatch.esm": "Neon Core + Neon Vertigo",
  "neoncoreseriousbusiness.esm": "Neon Core - Serious Business",
  "neonexpansion.esm": "NeonExpansion",
  "neonlmr_neg90deg.esm": "Neon - Landing Marker Realignment",
  "neonnoir_ramenshop.esm": "Neon Noir - Ramen Shop",
  "neonplayerhideout.esm": "Hacker Smuggler Hideout",
  "neonsmuggler.esm": "Neon Smuggler - Legendary Weapons Dealer",
  "neurostrikes_melee.esm": "Neurostrikes Improved",
  "newakilacheck.esm": "Akila City Rises",
  "newhomesteadeternal.esm": "New Homestead Eternal",
  "newneoncheck.esm": "NEON VEINS",
  "newnewatlantis.esm": "New Atlantis Awaits",
  "nfvc0003vigilance.esm": "Vigilance",
  "nighthawk.esm": "Iconic Ships",
  "nomad_spacesuit_z.esm": "Nomad Spacesuit - Weapon - Player Home",
  "nomadcaveakilarisespatch.esm": "Akila City Rises",
  "nomoreidioticlandings.esm": "No More Idiotic Landings",
  "non-lethal framework.esm": "Non-Lethal Framework",
  "northern lights.esm": "Northern Lights - Aurora Borealis",
  "noselfhealeffect.esm": "No Self Heal Effect (fog begone)",
  "notyetwatchtower.esm": "Not Yet Watchtower",
  "nova_immersiveeconomy.esm": "Immersive Economy",
  "noxpkillsteal.esm": "No XP Kill Steal Fix",
  "npcstakeenvdamage.esm": "NPCs Take Environmental Damage",
  "nwef.esm": "New Workbenches Essential Framework NWEF",
  "oddzealot_constellationdecoration.esm": "Constellation Decoration-12222-1-5-1-1733855828",
  "odx_antares_sunkx1.esm": "Antares Fulcrum",
  "odx_supra_antares.esm": "Antares Supra",
  "oldatlantis.esm": "Old Atlantis",
  "ombrehaircolours.esm": "More Hair Colors",
  "oneilstation.esm": "Colony One - Fully Featured UC Space Colony",
  "open_ship_doors.esm": "Open Ship Doors",
  "operatorassaultskins.esm": "Operator Skins Set - ShockTroop",
  "operatorskinsecliptic.esm": "Operator Skins Set - Ecliptic",
  "os_outpostshower.esm": "Outpost Showers",
  "otr_optoiletreplacer.esm": "Outpost Toilets",
  "ouc_starparcelcourier.esm": "Star Parcel Courier Missions",
  "outland_frontierready.esm": "Outland - Frontier Ready",
  "outpost beacon override.esm": "Outpost Beacon Override - Increased Build Radius",
  "outpostresourcebot.esm": "O.R.B - Outpost Resource Bot",
  "outrora_poi_akila.esm": "Shaw Gang Encampments - Akila POI Expansion",
  "owltech_lets_work_habs_ds_patch.esm": "Owtech LWH UB Patch",
  "owltech_lets_work_habs_ub_patch.esm": "Owtech LWH UB Patch",
  "owltech_lets_work_habs.esm": "Owl Tech Lets Work Habs",
  "paradiso resort - hotel expansion 1.1.esm": "Paradiso Resort - Hotel Expansion",
  "paradisoevolved.esm": "Paradiso Evolved",
  "paslowmo.esm": "Smooth Ship Power SlowMo",
  "patch_spe_vh.esm": "Viewport x SPE Patch",
  "patch-spe-deimog.esm": "AddOn - SPE x Deimog",
  "patch-spe-ilr.esm": "- SPE x Immersive Landing Ramps",
  "patch-spe-lbca.esm": "- SPE x Landing Bay Cargo Access",
  "patch-spe-sbc.esm": "- SPE x Ship Builder Categories",
  "patch-spe-se.esm": "- SPE x Spacefaring Economy",
  "peakperformance_re.esm": "Peak Performance - Immersive Needs",
  "pegasus_botanicsutilities.esm": "Outpost Botanics and Utilities",
  "permanentpois-db.esm": "Permanent POIs - Darkness Beckons",
  "permanentpois-ex.esm": "Permanent POIs - Evil Beyond",
  "permanentpois-rs.esm": "Permanent POIs - Rogue Science",
  "permanentpois-uh.esm": "Permanent POIs - Untouched Horizons",
  "permanentpois.esm": "Permanent POIs",
  "pilotassistantbot.esm": "P.A.B - Pilot Assist Bot",
  "piratecutlass.esm": "Freebooter Weaponeering",
  "planetspart1.esm": "Planets Part 1",
  "planetspart2.esm": "Planets Part 2",
  "planetspart3.esm": "Planets Part 3",
  "planetspart4.esm": "Planets Part 4",
  "planetspart5.esm": "Planets Part 5",
  "planetspart6.esm": "Planets Part 6",
  "poicooldown.esm": "Cooldown - Fewer repeated POIs",
  "preconfiguredgamesettings.esm": "Preconfigured Game Settings",
  "prisonpatch.esm": "Prison Patch",
  "projectrework-akila.esm": "Project Rework - Akila",
  "projectrework-pluto.esm": "Project Rework - Pluto",
  "pxguardiantweaks.esm": "Starborn not Toddborn - Modular Spacesuit and buffed Guardian ship",
  "pxstarborntweaks.esm": "Starborn not Toddborn - Modular Spacesuit and buffed Guardian ship",
  "rabbits real lights anchor point.esm": "Rabbit's Real Lights Anchorpoint",
  "rabbits real lights new babylon.esm": "Rabbit's Real Lights New Babylon",
  "radmech.esm": "Mech Enemies",
  "raynetcockpit 2.esm": "RayNet Drake C8 Cockpit",
  "rbt_configurablesuitdisplay.esm": "Configurable Spacesuit Auto-Hide",
  "rbt_costofliving.esm": "Cost Of Living - Simple Taxes",
  "rbt_costofspacing.esm": "Cost Of Spacing",
  "rbt_gear.esm": "Starter - Background Gear",
  "rbt_sfe_ta.esm": "Spacefaring Economy",
  "rbt_spacefaringeconomy_values_ss.esm": "Spacefaring Economy",
  "rbt_spacefaringeconomy.esm": "Spacefaring Economy",
  "rbtnaapatch.esm": "Rabbit's Real Lights New Atlantis Patch",
  "realearthatmosphere.esm": "Real Earth Atmosphere With Tutorial",
  "realgravanom.esm": "Real Gravitational Anomalies- A GRiNDTerra Mod",
  "realistic recoil - terran armada.esm": "Realistic Recoil",
  "realistic recoil.esm": "Realistic Recoil-5770-1-11-1777419208",
  "realtitan.esm": "Real Accurate Titan",
  "realtitanatmosphere.esm": "Real Titan Atmosphere",
  "realvenusatmosphere.esm": "Real Venus Atmosphere",
  "red_mile_terror.esm": "Red Mile Terror",
  "redmile_newdawn.esm": "Red Mile - New Dawn",
  "redmile_terror_newdawn_compatibilitypatch.esm": "Red Mile Terror",
  "refinedreliantmedical.esm": "Refined Reliant Medical",
  "remove asteroids and debris in orbit.esm": "Remove Asteroids and Debris In Orbit",
  "respect my authority - ryujin.esm": "Respect My Authority - Ryujin",
  "rocksgverseppg.esm": "Dummys - Load Archive",
  "roleplayersalternatestart.esm": "Roleplayers Alternate Start",
  "ronin - mission board expansion.esm": "RONIN - Mission Board Expansion",
  "rosietannehill-anactualdoctor.esm": "Rosie Tannehill - An Actual Doctor",
  "royalaliens.esm": "Royal Aliens - Size Speed and Attack Variation for All Starfield's Creatures",
  "rrl objects - rabbit's real lights landing pads.esm": "Rabbit's Real Lights Landing Pads",
  "rrlac - rabbit's real lights akila city.esm": "Rabbit's REAL LIGHTS Akila City",
  "rrlc - rabbit's real lights cydonia.esm": "Rabbit's Real Lights Cydonia",
  "rrlht - rabbit's real lights hopetown.esm": "Rabbit's Real Lights HopeTown",
  "rrlhte - rabbit's real lights hopetown expanded.esm": "Rabbits's Real Lights HopeTown expanded",
  "rrlna - rabbit's real lights new atlantis.esm": "Rabbit's REAL LIGHTS New Atlantis",
  "rrlp - rabbit's real lights paradiso.esm": "Rabbit's Real Lights Paradiso",
  "rtm - apparel variety expanded.esm": "RTM's Apparel Variety Expanded",
  "rtm - safes redone.esm": "RTM's Safes Redone",
  "rugseamfix.esm": "Rug Seam Fix",
  "runningwithhands.esm": "First Person Running with Hands",
  "rvexplore.esm": "Tiny Reasons to Explore... Too!",
  "rvnomadcave.esm": "Akila Nomad Cave",
  "rvscav.esm": "Tiny Reasons to Scavenge",
  "rvspace.esm": "Tiny Reasons to Explore Space",
  "rvulpack.esm": "Tiny Reasons to Explore",
  "ryujin_radiant_quest_enhancement-access.esm": "Ryujin Radiant Quest Enhancements - Access",
  "samantha says - dynamic medical bill.esm": "Dynamic Medical Bill - A doctor heal cost modifier",
  "samantha says - dynamic repair bill.esm": "Dynamic Ship Repair Bill - Modified (Expensive)",
  "samcowboy.esm": "Sam The Cowboy - A Visual Replacer",
  "satou_crimson_van01.esm": "Crimson Gang Van (Standalone)",
  "satou_warthog01.esm": "M12B FAV (Warthog) (Standalone)",
  "savrenstone.esm": "Dummys - Load Archive",
  "sbd_ship_chair_anim.esm": "Furniture with Animations",
  "sbrl- neonexpansion patch.esm": "Slightly Better Ryujin Tower Lobby + NeonExpansion",
  "scientificgorillabettergalbankshiploot.esm": "Better Piracy - GalBank Ships Have More Loot",
  "scrolls of quest-fixing.esm": "Scroll of Quest Fixing",
  "sdp_hotelnaapatch.esm": "New Atlantis - Viewport Hotel Patch",
  "sdp_hotelnaapatchfinal.esm": "New Atlantis - Viewport Hotel Patch 2",
  "sdp_viewporthotel.esm": "New Atlantis - Viewport Hotel",
  "secret staryard ship - echoes 101.esm": "Secret Shipyards Echoes",
  "secretstaryards_signal-jam_vol_0-free.esm": "Secret Staryards Signal Jam",
  "secretstaryardships-dirtylaundry2.esm": "Secret Shipyards Dirty Laundry",
  "secretstaryardships-treasureisland1.esm": "Secret Staryards Treasure Island",
  "secsyh20_tutorial.esm": "Secret Shipyards Tutorial",
  "security checkpoints dialog fix.esm": "Security Checkpoints Dialog Fixes",
  "seeyourselfsleep.esm": "ImmerSleep - See Yourself Sleeping",
  "sense_robots_and_turrets_too.esm": "Sense Robots And Turrets Too",
  "seraphim ship.esm": "Seraphim - UC Themed Ship",
  "seti_shiplights_by_bosdragon.esm": "SETI - Ship Exterior True Illumination",
  "sfbgs00b.esm": "Escape",
  "sfbgs00c.esm": "The Perfect Recipe",
  "sfbgs019.esm": "Deimog",
  "sfbgs021.esm": "Observatory",
  "sfta01.esm": "Trackers Alliance Complete",
  "sfta02.esm": "Trackers Alliance Complete",
  "sfta03.esm": "Trackers Alliance Complete",
  "sfta04.esm": "Trackers Alliance Complete",
  "sfta05.esm": "Trackers Alliance Complete",
  "sfta06.esm": "Trackers Alliance Complete",
  "shades_glowy_stuff.esm": "Shades Glowy Stuff",
  "shades_immersive_looting.esm": "Shades Immersive Looting",
  "shades_skillpoints_for_credits.esm": "Shades Skill Points for Credits or Essence (Buy Skill Points Immersively)",
  "shades_stealth_takedowns.esm": "Shades Stealth Takedowns (Knock-out or Lethal)",
  "shape castings bgs vehicles aio.esm": "Shape Casting Deimog",
  "sharpercloudsforstarfield.esm": "Sharper Clouds for Starfield",
  "shatteredspacedelayed.esm": "Shattered Space Delayed Start",
  "ship power fix.esm": "Power Allocation Fix - Revert Unwanted Power Changes",
  "shipbuildercategories.esm": "Builder Categories",
  "shipcolorize.esm": "Colorize Redux",
  "shiprammingdamage.esm": "Deadly Ramming and Debris Fields - Ship Collisions Do More Damage",
  "shipvendorfix.esm": "Ship Vendor Fix",
  "shipvendorframework.esm": "Vendor Framework",
  "shopkeeperschedules.esm": "Routines Expanded - Robot Vendors",
  "shopkeeperschedulesdazra.esm": "Routines Expanded - Dazra",
  "shutupcora.esm": "Shut Up Cora - Less Chatter While Flying",
  "sih-shatteredspacepatch.esm": "SIH Shattered Space Patch",
  "simpleimmersivehelmets.esm": "Simple Immersive Helmets",
  "skkshiptools.esm": "Management Tools (Hack Call Teleport)",
  "skysuitefurnished.esm": "Neon - Sky Suite Expanded and Furnished",
  "slightly better rowland arms.esm": "Slightly Better Rowland Arms",
  "slightly better shepherd's store - npc routines.esm": "Slightly Better Shepherd's Store + NPC Routines Patch",
  "slightly better shepherd's store.esm": "Slightly Better Shepherd's Store",
  "smartgrenades.esm": "Smart Grenades and Mines - No More Inventory Management",
  "smartheal.esm": "Smart Heal",
  "smartinventory-legendarymodulerecycler-patch.esm": "Legendary Module Recycler Patch",
  "smartinventory-munitionsexpansionframework-patch.esm": "Munitions Expansion Framework Patch",
  "smartinventory-shatteredspace-patch.esm": "SI - Smart Inventory",
  "smartinventory-terranarmada-patch.esm": "SI - Terran Armada Patch",
  "smartinventory-variablecontrabandpricesredux-patch.esm": "Variable Contraband Prices - Redux Patch",
  "smartinventory.esm": "Smart Inventory",
  "smr gts patch - factions.esm": "Patch Factions by SMRIAZ",
  "smrreplacerandreja_v3.esm": "Vanilla Faces Tweaked - Andreja",
  "smrreplacerdonna.esm": "SMR Replacers - Shadowpryo's Donna and Tony",
  "smrreplacersarah_v2a.esm": "Vanilla Faces Tweaked - Sarah Morgan",
  "smrreplacertony.esm": "SMR Replacers - Shadowpryo's Donna and Tony",
  "sp2_affinityenhanced.esm": "Affinity Enhanced",
  "sp2_allcockpitsnavconsoles.esm": "All Cockpits Have Nav Consoles",
  "sp2_capitalplanetdesktopglobes.esm": "Capital Planet Desktop Globes",
  "sp2_craftableprimersanddiodes.esm": "Craftable Primers And Diodes",
  "sp2_factionrequisitionkiosks.esm": "Faction Requisition Kiosks",
  "sp2_immersivecompanionportraits.esm": "Immersive Companion Portraits",
  "sp2_immersivelandingramps.esm": "Immersive Landing Ramps",
  "sp2_landingbaycargoaccess.esm": "Landing Bay Cargo Access",
  "sp2_mirroredstarfieldfixed.esm": "Mirrored Starfield Fixed",
  "sp2_realisticsundisksize.esm": "Realistic Sun Disk Size",
  "sp2_simpleimmersivemusicplayers.esm": "Simple Immersive Music Players",
  "sp2_vascorecognizesmoreplayernames.esm": "Vasco Recognizes More Player Names",
  "spacesuitlegendaryeffects_withoutenv.esm": "More Spacesuit Legendary Effects",
  "spenavpatch.esm": "SPENavPatch",
  "squid_nails.esm": "Squid's Nails",
  "squid_pmcexo.esm": "Bio-Tech Armor",
  "squid_revolver.esm": "Renegade Armor - Peacekeeper",
  "squidcobjyeet.esm": "GTSpatchSquid",
  "squidkhorneaxe.esm": "Blades of the Immaterium",
  "sr_cj.esm": "CJ's Store Improved",
  "sr_jemisonmercantile npc routines patch.esm": "Slightly Better Jemison Mercantile - No Boxes - NPC Routines PATCH",
  "sr_jemisonmercantile.esm": "Slightly Better Jemison Mercantile - No Boxes",
  "sr_laredofirearms.esm": "Slightly Better Laredo Firearms",
  "sr_ryujinlobby.esm": "Slightly Better Ryujin Tower Lobby",
  "sr_ucsecurity.esm": "Slightly Better UC Security Office",
  "stairs-neon.esm": "Stairs - Neon",
  "starborn archives eternal patch.esm": "Starborn Archive Eternal Patch",
  "starborn archives.esm": "Starborn Archives",
  "starbreaker.esm": "Starbreaker",
  "starfield completed - unusualsosfix.esm": "Unusual SOS Fix - Quest Completed",
  "starfield little bits - lasers only when aiming.esm": "Starfield Little Bits - Lasers Sights Only When Aiming",
  "starfield_crowd_overhaul_z.esm": "Starfield Crowd Overhaul",
  "starfield_disciples_overhaul_z.esm": "Starfield Disciples Overhaul",
  "starfield_gadgets_z.esm": "Dummys - Load Archive",
  "starfield_hair+beards_z.esm": "Starfield Hair and Beards",
  "starfield_melee_weapons_z.esm": "Melee Madness",
  "starfield_spacer_overhaul_z.esm": "Starfield Spacer Overhaul",
  "starfieldfleetexpansion.esm": "Starfield Fleet Expansion",
  "stargym - one more rep.esm": "StarGym - One More Rep",
  "starqueen.esm": "Dummys - Load Archive",
  "starshards.esm": "Starshards",
  "statesofmatter.esm": "States of Matter - Environment-depending States for Resources",
  "stingray_standalone.esm": "The Stingray Standalone",
  "stlazarusawakened.esm": "Lazarus Awakened - New Version 2.0",
  "stregretsquest.esm": "Regrets",
  "stretchapartmentsold.esm": "Stretch Apartment Sold",
  "stroudpremiumedition.esm": "Stroud Premium Edition",
  "sts_sinkthatsink.esm": "Sink that Sink",
  "suitpowercores.esm": "Avontech Suit Power Cores",
  "suitregen.esm": "Spacesuit Hazard Restoration",
  "supervisor lin clean.esm": "Supervisor Lin Clean",
  "svf-darkstarastrodynamics-patch.esm": "Vendor Framework",
  "svf-deadalus-patch.esm": "Vendor Framework",
  "svf-dominion-patch.esm": "Vendor Framework",
  "svf-falklandsystems-patch.esm": "Falkland Systems + SVF Patch",
  "svf-iconicships-patch.esm": "Vendor Framework",
  "svf-lkships-patch.esm": "Vendor Framework",
  "svf-lowerlandingpad-patch.esm": "Vendor Framework",
  "svf-outpostvendornewships-patch.esm": "Vendor Framework",
  "svf-shatteredspace-patch.esm": "Vendor Framework",
  "svf-starvival-patch.esm": "Vendor Framework",
  "svf-thedenastrodynamics-patch.esm": "Vendor Framework",
  "svf-watchtower-patch.esm": "Watchtower + SVF Patch",
  "sylvspoi.esm": "Sylv's POI Field Research Outpost",
  "takeablecompanionoutfits.esm": "Visible Unequippable Takeable Companion Outfits",
  "taliohs_hairboosterpack.esm": "Taliohs Hair Booster Pack",
  "taliohs_haircollection.esm": "Taliohs Hair Collection",
  "talltrees.esm": "Tall Trees Variety",
  "tauwing.esm": "Tau Wing Decorative Modules",
  "testing toilet sink 1.esm": "Immersive Play - Usable Toilets and Coffee Machines",
  "the lodge awakened.esm": "The Lodge Awakened - Collection Only",
  "the rock refit.esm": "The Rock - Refit",
  "the_headhunter_z.esm": "The Headhunter",
  "thecorefurnished.esm": "Akila - The Core Expanded and Furnished",
  "thedreamlands.esm": "The Dreamlands",
  "theencoglasses.esm": "Glasses",
  "thetrackersalliancedelayed.esm": "The Trackers Alliance Delayed Start",
  "thewellapartmentfurnished.esm": "The Well - Apartment Furnished",
  "tig_shipyards.esm": "Tiger Shipyards Overhaul",
  "tn_textile_shatteredspace.esm": "TN's Textile Perk - Shattered Space",
  "tnearthbiomes.esm": "TN's Earth's Biomes",
  "tnfasttravelcontrol.esm": "TN's Fast Travel Control",
  "tntextileperkrestored.esm": "TN's Textile Perk Restored (Clothing System Overhaul)",
  "trackers alliance mission board plus.esm": "Trackers Alliance Mission Board at Major City Spaceport",
  "trackersalliancespacebounties.esm": "Trackers Alliance Space Bounties Fix",
  "trippy_unlocklodgespacesuitcase.esm": "Lodge Space Suit Display Case Unlocked",
  "truevision.esm": "Starfield TrueVision LUT",
  "truevisionshatteredspace.esm": "TrueVision Shattered Space DLC",
  "uc_vanguard_factionkiosks_patch.esm": "United Closet - Vanguard Apparel",
  "uc_vanguard.esm": "United Closet - Vanguard Apparel",
  "ucvanguard_expandedpresence.esm": "UC Vanguard - Expanded Presence",
  "unarmedweapon.esm": "Unarmed Weapon",
  "unevasivestealthdrive.esm": "Evasive Stealth Drive Fix",
  "uniquepoinames.esm": "Unique POI Names",
  "useful brigs.esm": "Useful Brigs",
  "utilitymodules_bays.esm": "Utility Landing Bays",
  "vacuumsilence.esm": "Vacuum Silence",
  "vanilla flashlight improved.esm": "Vanilla Flashlight Improved",
  "varchar_hopetown_expanded.esm": "HopeTown expanded",
  "varchar_neon_distant_platforms.esm": "Neon - Distant platforms",
  "variouscrewuniv.esm": "Various Crew",
  "varuun dlc items in base game.esm": "Varuun DLC items in base game",
  "varuun heretic writings and contraband.esm": "Varuun Heretic Writings and contraband",
  "varuuntechnicalinstituteshiphabs.esm": "Va'ruun Technical Institute Ship Habs",
  "varuunvendors.esm": "Va'ruun Vendors",
  "vehiclehazardprotection.esm": "Vehicle Hazard Protection",
  "vehicles.esm": "Parked Vehicles",
  "vehiclevendor.esm": "Rev-8 Ship Vendor Fix",
  "versionmanager.esm": "Version Manager",
  "vigilancecombatstyle.esm": "UC Vigilance Unleashed",
  "vigilancevo.esm": "UC Vigilance Visual Overhaul",
  "vivs_furnishyourfleet.esm": "Furnish Your Fleet",
  "vndp_patch.esm": "Neon Distant platforms Random Junk Fixes",
  "voiddrinker.esm": "Void Drinker",
  "vpcd_elevator.esm": "VPCD Elevator",
  "waggonerfarm-extended.esm": "The Waggoner Farm - Extended",
  "waitmeinship.esm": "Wait For Me in Ship",
  "weapondisplaysenhanced.esm": "Weapon Displays Enhanced",
  "weaponswapstutterfix.esm": "Weapon Swap Stutter Fix",
  "welcometoarinya.esm": "Defying Fire Welcome to Arinya",
  "winds of akila.esm": "Akila City Rises",
  "winds of gagarin.esm": "Winds of Gagarin",
  "windsofakilarisespatch.esm": "Akila City Rises",
  "windsofcydonia.esm": "Winds of Cydonia",
  "ws_variablecontrabandprices.esm": "Variable Contraband Prices - Redux",
  "x2357creatorhats.esm": "X2357's Content Creator Appreciation Hat Skins",
  "x2357factionweaponskinsconstellation.esm": "X2357's Faction Weapon Skins - Constellation",
  "x2357factionweaponskinscrimsonfleet.esm": "X2357's Faction Weapon Skins - Crimson Fleet",
  "x2357factionweaponskinsfreestar.esm": "X2357's Faction Weapon Skins - Freestar Collective",
  "x2357factionweaponskinsryujin.esm": "X2357's Faction Weapon Skins - Ryujin Industries",
  "x2357factionweaponskinsuc.esm": "X2357's Faction Weapon Skins - United Colonies",
  "x2357factionweaponskinsvaruun.esm": "X2357's Faction Weapon Skins - House Va'Ruun",
  "x2357primearmorskinsmark1.esm": "X2357's Prime Armor Skins - Mark 1 Constellation Spacesuit",
  "x2357primearmorskinsterranarmada.esm": "X2357's Prime Skins - Terran Armada AIO",
  "x2357primearmorskinsuniqueoutfits.esm": "X2357's Prime Armor Skins - Unique Outfits",
  "x2357primeweaponskinsbigbang.esm": "X2357's Prime Weapon Skins - Big Bang",
  "x2357primeweaponskinscutter.esm": "X2357's Prime Weapon Skins - Cutter",
  "x2357primeweaponskinsdrumbeat.esm": "X2357's Prime Weapon Skins - DrumBeat",
  "x2357primeweaponskinsequinox.esm": "X2357's Prime Weapon Skins - Equinox",
  "x2357primeweaponskinsgrendel.esm": "X2357's Prime Weapon Skins - Grendel",
  "x2357primeweaponskinskodama.esm": "X2357's Prime Weapon Skins - Kodama",
  "x2357primeweaponskinsmelee.esm": "X2357's Prime Weapon Skins - Melee Weapons",
  "x2357primeweaponskinsorion.esm": "X2357's Prime Weapon Skins - Orion",
  "x2357primeweaponskinspacifier.esm": "X2357's Prime Weapon Skins - Pacifier",
  "x2357primeweaponskinspumpshotgun.esm": "X2357's Prime Weapon Skins - Pump Shotgun",
  "x2357primeweaponskinsrazorback.esm": "X2357's Prime Weapon Skins - Razorback",
  "x2357primeweaponskinsshotty.esm": "X2357's Prime Weapon Skins - Shotty",
  "x2357primeweaponskinstombstone.esm": "X2357's Prime Weapon Skins - Tombstone",
  "x2357primeweaponskinsurbaneagle.esm": "X2357's Prime Weapon Skins - Urban Eagle",
  "zonescityhomes_z.esm": "Zone's City Homes",
  "zoomforperfectlanding.esm": "Zoom for Perfect Landing",
  "zswairlocks.esm": "ZSW - Airlocks",
  "zy4_uc_navy_officer_uniforms.esm": "ENHANCE UC Military Uniform Skirts (Apparel and Spacesuits)",
  "zy5_tanktop_and_skirts.esm": "ENHANCE Outfits - Tank Tops and Mini Skirts",
  "zyj_screensaver.esm": "Outpost Monitors with Screensavers",
  "zyl_headlamps.esm": "Headlamps",
  "zyp_battlegroundniira.esm": "Battleground Niira - Biome Visual Transformation",
  "zyp_crevassefield.esm": "Crevasse Field - Biome Visual Transformation",
  "zyp_frozenmountains_fog.esm": "Real Frozen Mountains - Biome Visual Transformation",
  "zyp_icy_swamp_porrimaivd.esm": "Icy Moon - Porrima IV-d - Biome Visual Transformation",
  "zyp_mossyplateau.esm": "Mossy Plateau - Biome Visual Transformation",
  "zyp_sandydesert01.esm": "Real Sandy Deserts - Biome Visual Transformation",
  "zyp_snowyvolcanicbiome.esm": "Snowy Volcanic Landscape - Biome Visual Transformation",
  "zyp_vibrantvolcanicbiome.esm": "Vibrant Volcanic Landscapes - Biome Visual Transformation",
  "zyp_wildcoasts.esm": "Wild Coasts - Biome Visual Transformation",
};

export function modDisplayName(pluginName: string, fallback: string): string {
  return MOD_DISPLAY_NAMES[pluginName.toLowerCase()] ?? fallback;
}
