import type { CommandDefinition } from './commands';

const referenceInput = (key: string, label: string): NonNullable<CommandDefinition['inputs']>[number] => ({
  key,
  label,
  type: 'text',
  placeholder: '00000000',
  pattern: '^[0-9A-Fa-f]{1,8}$',
  hint: '1–8 hexadecimal characters',
});

const EFFECT_UNCONFIRMED_TOGGLE_IDS = [
  'toggle-wireframe',
  'toggle-collision-geometry',
  'toggle-motion-blur',
  'toggle-taa',
  'toggle-fsr2',
  'toggle-vrs',
  'toggle-rain-occlusion',
  'toggle-lens-flare',
  'toggle-markers',
];

// Newly discovered commands stay here until an in-game test establishes their
// behavior. Moving a command into its normal category is part of verification.
export const UNTESTED_COMMANDS: CommandDefinition[] = [
  {
    id: 'toggle-first-person-hands',
    title: 'Toggle First-Person Hands',
    category: 'Camera',
    description: 'Hide or restore the first-person hands and held weapon.',
    command: 'ToggleHandsCulled',
    tags: ['camera', 'first person', 'hands', 'weapon', 'toggle'],
    warning: 'Run this command again to restore the first-person hands and held weapon.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'show-first-person-model',
    title: 'Show First-Person Model in Third Person',
    category: 'Camera',
    description: 'Show the first-person arms and weapon model while using the third-person camera.',
    command: 'Show1stPerson',
    tags: ['camera', 'first person', 'third person', 'arms', 'weapon'],
    warning: 'This intentionally overlaps the first-person model with the third-person character and can look visually incorrect.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'toggle-all-animations',
    title: 'Toggle All Actor Animations',
    category: 'World',
    description: 'Freeze or resume actor animations throughout the loaded area.',
    command: 'ToggleAnimations',
    tags: ['actor', 'animation', 'freeze', 'resume', 'toggle'],
    warning: 'Run this command again to resume animations before continuing normal play.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'select-next-actor',
    title: 'Select Next Actor',
    category: 'Targets',
    description: 'Select the next actor near the center of the screen for console targeting.',
    command: 'PickNextActor',
    tags: ['actor', 'select', 'console', 'target', 'next'],
    testStatus: 'verified',
  },
  {
    id: 'select-next-reference',
    title: 'Select Next Reference',
    category: 'Targets',
    description: 'Select the next reference near the center of the screen for console targeting.',
    command: 'PickNextRef',
    tags: ['reference', 'select', 'console', 'target', 'next'],
    testStatus: 'verified',
  },
  {
    id: 'untested-force-speech-fail',
    title: 'Speech Challenge Failure',
    category: 'Untested',
    description: 'Force speech challenges to fail, or restore normal failure rules.',
    command: 'setforcespeechchallengealwaysfail 1',
    executeLabel: 'Always Fail',
    secondaryAction: {
      label: 'Restore Normal',
      title: 'Restore Normal Speech Failure Rules',
      command: 'setforcespeechchallengealwaysfail 0',
    },
    tags: ['speech', 'persuasion', 'fail', 'always fail', 'restore normal'],
    warning: 'This changes all speech challenges until the matching restore command is run.',
    risk: 'caution',
    testStatus: 'untested',
  },
  {
    id: 'untested-sexchange',
    title: 'Change Player Body Type',
    category: 'Untested',
    description: 'Switch the player body type and return the character to a default appearance.',
    command: 'sexchange',
    tags: ['player', 'appearance', 'body', 'character'],
    warning: 'Published reports say this can reset the current appearance. Make a manual save first.',
    risk: 'danger',
    testStatus: 'untested',
  },
  {
    id: 'untested-kill-player',
    title: 'Kill Player',
    category: 'Untested',
    description: 'Kill the player character immediately.',
    command: 'player.kill',
    tags: ['player', 'kill', 'death'],
    warning: 'This immediately kills the player and may trigger a reload or death sequence.',
    risk: 'danger',
    testStatus: 'untested',
  },
  {
    id: 'untested-start-all-quests',
    title: 'Start All Quests',
    category: 'Untested',
    description: 'Attempt to start every quest in the game.',
    command: 'saq',
    tags: ['quest', 'all quests', 'saq'],
    warning: 'Starting every quest can break progression, overload scripts, or crash the game. Use only on a disposable save.',
    risk: 'danger',
    testStatus: 'untested',
  },
  {
    id: 'untested-complete-all-quests',
    title: 'Complete All Quest Stages',
    category: 'Untested',
    description: 'Attempt to complete all quest stages globally.',
    command: 'caqs',
    tags: ['quest', 'all quests', 'complete', 'caqs'],
    warning: 'This can irreversibly damage quest state, skip story content, or crash the game. Use only on a disposable save.',
    risk: 'danger',
    testStatus: 'untested',
  },
  {
    id: 'untested-camera-fov',
    title: 'Set Camera Field of View',
    category: 'Untested',
    description: 'Set the camera field of view in degrees. Previous in-game testing produced no visible change.',
    command: 'SetCameraFOV {degrees}',
    inputs: [{ key: 'degrees', label: 'Field of View', type: 'number', defaultValue: 75, min: 30, max: 160, step: 1, hint: 'Reported default: 75' }],
    tags: ['camera', 'fov', 'field of view'],
    warning: 'Extreme field-of-view values can distort the image or make menus and weapons appear incorrect.',
    risk: 'caution',
    testStatus: 'inconclusive',
    intakeGroup: 'Executed — Effect Unconfirmed',
  },
  ...[
    ['toggle-wireframe', 'Toggle Wireframe', 'ToggleWireframe', 'Toggle wireframe rendering.', ['wireframe', 'rendering']],
    ['toggle-collision-geometry', 'Toggle Collision Geometry', 'tcg', 'Show or hide collision geometry.', ['collision', 'geometry', 'debug']],
    ['toggle-motion-blur', 'Toggle Motion Blur', 'ToggleMotionBlur', 'Toggle motion-blur rendering.', ['motion blur', 'rendering']],
    ['toggle-taa', 'Toggle Temporal Anti-Aliasing', 'ToggleTAA', 'Toggle temporal anti-aliasing.', ['taa', 'anti-aliasing', 'rendering']],
    ['toggle-fsr2', 'Toggle FSR2', 'ToggleFSR2', 'Toggle FSR2 rendering.', ['fsr2', 'upscaling', 'rendering']],
    ['toggle-vrs', 'Toggle Variable Rate Shading', 'ToggleVRS', 'Toggle variable-rate shading.', ['vrs', 'rendering']],
    ['toggle-rain-occlusion', 'Toggle Rain Occlusion', 'ToggleRainOcclusion', 'Toggle rain occlusion.', ['rain', 'weather', 'rendering']],
    ['toggle-lens-flare', 'Toggle Lens Flare', 'lf', 'Toggle lens-flare rendering.', ['lens flare', 'rendering']],
    ['toggle-markers', 'Toggle World Markers', 'ToggleMarkers', 'Show or hide world markers.', ['markers', 'world', 'rendering']],
  ].map(([id, title, command, description, tags]) => ({
    id: `untested-${id as string}`,
    title: title as string,
    category: 'Untested' as const,
    description: EFFECT_UNCONFIRMED_TOGGLE_IDS.includes(id as string)
      ? `${description as string} In-game testing executed without an error, but produced no confirmed visible change.`
      : description as string,
    command: command as string,
    tags: tags as string[],
    warning: 'This is an unverified rendering or debug toggle. Run it again to attempt to restore the previous state.',
    risk: 'caution' as const,
    testStatus: (EFFECT_UNCONFIRMED_TOGGLE_IDS.includes(id as string) ? 'inconclusive' : 'untested') as 'inconclusive' | 'untested',
    intakeGroup: (EFFECT_UNCONFIRMED_TOGGLE_IDS.includes(id as string) ? 'Executed — Effect Unconfirmed' : 'Ready to Test') as NonNullable<CommandDefinition['intakeGroup']>,
  })),
  {
    id: 'untested-show-subtitles',
    title: 'Always Show Subtitles',
    category: 'Untested',
    description: 'Attempt to force all dialogue subtitles to display. Previous in-game testing produced no visible override.',
    command: 'ShowSubtitle 1',
    tags: ['subtitle', 'dialogue', 'accessibility'],
    testStatus: 'inconclusive',
    intakeGroup: 'Executed — Effect Unconfirmed',
  },
  {
    id: 'untested-restore-subtitles',
    title: 'Restore Subtitle Override',
    category: 'Untested',
    description: 'Disable the forced subtitle-display override.',
    command: 'ShowSubtitle 0',
    tags: ['subtitle', 'dialogue', 'restore'],
    testStatus: 'untested',
  },
  {
    id: 'untested-step-frame',
    title: 'Advance One Frame',
    category: 'Untested',
    description: 'Advance the paused game simulation by one frame. In-game testing executed without an error but produced no noticeable movement.',
    command: 'StepOneFrame',
    tags: ['frame', 'pause', 'debug'],
    testStatus: 'inconclusive',
    intakeGroup: 'Executed — Effect Unconfirmed',
  },
  {
    id: 'untested-nearest-door',
    title: 'Use Nearest Teleport Door',
    category: 'World',
    description: 'Use the teleport door nearest to the player.',
    command: 'UseNearestTeleportDoor',
    tags: ['door', 'teleport', 'stuck'],
    warning: 'This may move the player through an unintended transition or bypass a scripted trigger.',
    risk: 'caution',
    testStatus: 'verified',
  },
  {
    id: 'untested-kill-projectiles',
    title: 'Remove All Projectiles',
    category: 'Untested',
    description: 'Remove all active projectiles from the loaded area.',
    command: 'kap',
    tags: ['projectiles', 'combat', 'cleanup'],
    warning: 'This may interfere with active combat or scripted projectile events.',
    risk: 'caution',
    testStatus: 'untested',
  },
  {
    id: 'untested-reload-weather',
    title: 'Reload Current Weather',
    category: 'Untested',
    description: 'Reload the currently active weather data. In-game testing executed without an error, but produced no confirmed visible change.',
    command: 'ReloadCurrentWeather',
    tags: ['weather', 'reload', 'visual'],
    testStatus: 'inconclusive',
    intakeGroup: 'Executed — Effect Unconfirmed',
  },
  {
    id: 'untested-reload-climate',
    title: 'Reload Current Climate',
    category: 'Untested',
    description: 'Reload the current climate data. In-game testing on Starfield 1.16.244 crashed during sky and weather processing.',
    command: 'ReloadCurrentClimate',
    tags: ['climate', 'weather', 'reload'],
    warning: 'This command caused a repeatable-risk game crash path in Starfield sky and weather processing.',
    risk: 'danger',
    testStatus: 'failed',
    unavailableReason: 'Disabled after an in-game v1.0 test crashed Starfield 1.16.244. The crash log shows an access violation in sky and weather processing.',
    intakeGroup: 'Blocked — Known Crash',
  },
  {
    id: 'untested-workshop',
    title: 'Enter Workshop Mode',
    category: 'Untested',
    description: 'Attempt to enter Workshop mode while inside a buildable area.',
    command: 'workshop',
    tags: ['outpost', 'workshop', 'build'],
    warning: 'This is intended for buildable areas and may behave incorrectly elsewhere.',
    risk: 'caution',
    testStatus: 'untested',
    closeBeforeExecute: true,
  },
  {
    id: 'untested-takeoff',
    title: 'Take Off to Space',
    category: 'Untested',
    description: 'Attempt to make the player ship take off into space.',
    command: 'TakeOffToSpace',
    tags: ['ship', 'takeoff', 'space'],
    warning: 'Running this outside the expected landed-ship state may break travel or leave the player in an invalid state.',
    risk: 'danger',
    testStatus: 'untested',
    closeBeforeExecute: true,
  },
  {
    id: 'untested-land-marker',
    title: 'Land at Current Planet Marker',
    category: 'Untested',
    description: 'Attempt to land at a marker on the current planet.',
    command: 'LandOnPlanetMarker',
    tags: ['ship', 'land', 'planet', 'marker'],
    warning: 'Running this without a valid planetary marker or travel context may fail or leave travel state inconsistent.',
    risk: 'danger',
    testStatus: 'untested',
    closeBeforeExecute: true,
  },
  {
    id: 'untested-pick-ref',
    title: 'Select Console Reference by ID',
    category: 'Targets',
    description: 'Set the console selection to a specific Reference ID.',
    command: 'PickRefByID {refId}',
    inputs: [referenceInput('refId', 'Reference ID')],
    tags: ['reference', 'select', 'console', 'target'],
    testStatus: 'verified',
  },
  {
    id: 'untested-pick-closest-ship',
    title: 'Select Closest Ship',
    category: 'Untested',
    description: 'Set the console selection to the ship closest to the player ship. Testing inside and outside the player ship produced no confirmed selection.',
    command: 'PickClosestShip',
    tags: ['ship', 'select', 'console', 'target'],
    testStatus: 'inconclusive',
    intakeGroup: 'Executed — Effect Unconfirmed',
  },
  {
    id: 'untested-set-at-start',
    title: 'Return Reference to Starting Position',
    category: 'Untested',
    description: 'Move a reference back to its original position and rotation.',
    command: '{refId}.setatstart',
    inputs: [referenceInput('refId', 'Reference ID')],
    tags: ['reference', 'position', 'reset', 'setatstart'],
    warning: 'Moving scripted references can disrupt quests, scenes, ownership, or world state.',
    risk: 'danger',
    testStatus: 'untested',
  },
  {
    id: 'untested-start-combat',
    title: 'Force Actor to Start Combat',
    category: 'Untested',
    description: 'Force one actor reference to begin combat with another.',
    command: '{actorRef}.startcombat {targetRef}',
    inputs: [referenceInput('actorRef', 'Actor Reference ID'), referenceInput('targetRef', 'Target Reference ID')],
    tags: ['actor', 'combat', 'startcombat', 'reference'],
    warning: 'Forced combat can alter hostility, crime, companion, and quest states.',
    risk: 'danger',
    testStatus: 'untested',
  },
  {
    id: 'untested-reset-dialogue',
    title: 'Reset Dialogue Flags',
    category: 'Untested',
    description: 'Reset dialogue flags such as one-time lines and talked-to-player state.',
    command: 'ResetDialogueFlags',
    tags: ['dialogue', 'reset', 'npc', 'debug'],
    warning: 'Resetting dialogue flags can repeat conversations or disrupt dialogue and quest progression.',
    risk: 'danger',
    testStatus: 'untested',
  },
  {
    id: 'untested-screenshot',
    title: 'Take Screenshot',
    category: 'Untested',
    description: 'Ask the game to capture a screenshot. Testing executed without an error, but gave no confirmation and the output file was not located.',
    command: 'Screenshot',
    tags: ['screenshot', 'photo', 'capture'],
    testStatus: 'inconclusive',
    intakeGroup: 'Executed — Effect Unconfirmed',
  },
  {
    id: 'untested-save-game',
    title: 'Save Game by Name',
    category: 'Untested',
    description: 'Attempt to create a save using a simple filename. Two in-game tests were rejected even when normal quicksave and full-save controls worked.',
    command: 'save {filename}',
    inputs: [{ key: 'filename', label: 'Save Name', type: 'text', defaultValue: 'CCC_Test', pattern: '^[A-Za-z0-9_-]{1,64}$', hint: 'Letters, numbers, underscore, or hyphen' }],
    tags: ['save', 'savegame', 'file'],
    warning: 'Starfield rejected this command during repeated testing even though its normal save controls worked in the same location.',
    risk: 'caution',
    testStatus: 'failed',
    unavailableReason: 'Disabled after repeated in-game tests returned “The Game Cannot Be Saved Now” while normal quicksave and full-save controls still worked.',
    intakeGroup: 'Executed — Issues',
  },
  {
    id: 'untested-load-game',
    title: 'Load Game by Name',
    category: 'Untested',
    description: 'Attempt to load a save using its filename. Testing with an existing displayed save name closed CCC without loading the save.',
    command: 'load {filename}',
    inputs: [{ key: 'filename', label: 'Save Name', type: 'text', defaultValue: 'CCC_Test', pattern: '^[A-Za-z0-9_-]{1,64}$', hint: 'Letters, numbers, underscore, or hyphen' }],
    tags: ['load', 'loadgame', 'file'],
    warning: 'The game may require an internal filename rather than the displayed save name; the tested command did not load an existing save.',
    risk: 'danger',
    testStatus: 'failed',
    unavailableReason: 'Disabled after an in-game test with an existing displayed save name closed CCC without loading the save.',
    intakeGroup: 'Executed — Issues',
    closeBeforeExecute: true,
  },
];
